import type { DestinationIntelligence } from "../../src/types/knowledge";
import { buildMonths, dest, TOURISM_BOARD_SOURCE } from "./builders";

export const DESTINATIONS_2: DestinationIntelligence[] = [
  dest({
    slug: "japan",
    name: "Japan",
    countryIso2: "JP",
    countryName: "Japan",
    region: "East Asia",
    summary:
      "Tokyo's neon, Kyoto's temples, bullet trains and seasonal spectacle — cherry blossoms in spring, fiery maples in autumn.",
    positioningLine: "A one-of-a-kind blend of tradition and future.",
    idealTraveller: "Culture-first travellers and teens-and-up families who enjoy walking and trains.",
    minimumNights: 6, idealNights: 8, maximumNights: 14,
    suitablePaces: ["balanced", "active"],
    interests: { culture: 98, city: 95, food: 95, history: 92, nature: 80, shopping: 88, themeparks: 80, adventure: 60, snow: 70, romance: 80, nightlife: 78, relaxation: 60, beach: 30, wildlife: 45 },
    suitability: { family: 80, toddlers: 65, children5To10: 78, teenagers: 90, seniors: 75, honeymoon: 88, solo: 95, firstInternationalTrip: 65 },
    food: { vegetarianFriendly: 55, indianFoodAvailability: 55, halalFriendly: 45, localCuisineScore: 98, streetFoodScore: 85, fineDiningScore: 98 },
    travelPracticality: { averageFlightHoursFromIndia: 8.5, walkingIntensity: "high", publicTransportEase: 98, roadTransferBurden: "low", accessibilityScore: 85, medicalAccessScore: 92 },
    budgetBands: ["premium", "luxury"],
    climateTags: ["temperate", "four-seasons", "humid-summer"],
    monthlyIntelligence: buildMonths({
      scores: [60, 62, 85, 92, 80, 60, 55, 55, 65, 85, 90, 70],
      temps: "temperateNorth",
      veryRainy: [6], rainy: [7, 9], humid: [6, 7, 8],
      crowded: [3, 4, 10, 11], quiet: [1, 2],
      highlights: { 4: ["Cherry blossom season (peak timing varies — verify)"], 11: ["Autumn foliage at its peak"] },
      warnings: { 6: ["Rainy season (tsuyu)"], 8: ["Hot, humid and typhoon-prone"] },
    }),
    commonTripCombinations: ["Tokyo + Kyoto + Osaka golden route", "Japan + Hakone/Mt Fuji", "Winter Hokkaido add-on"],
    commonMistakes: ["Cramming too many cities into a week", "Skipping rail-pass planning until arrival"],
    packingConsiderations: ["Excellent walking shoes — 15k+ steps daily is normal", "Layers for big day-night temperature swings", "Cash still useful in small establishments"],
    practicalWarnings: ["Vegetarian dining needs planning outside big cities — dashi (fish stock) is ubiquitous"],
    tradeOffs: ["Higher budget than Southeast Asia", "Vegetarian dining needs planning outside big cities"],
    whoShouldAvoid: ["Travellers wanting a low-walking, resort-style holiday"],
    extraSources: [TOURISM_BOARD_SOURCE("Japan National Tourism Organization")],
    confidence: 88,
  }),

  dest({
    slug: "south-korea",
    name: "South Korea",
    countryIso2: "KR",
    countryName: "South Korea",
    region: "East Asia",
    summary:
      "Seoul's pop culture, palaces and street food, plus Jeju island and autumn hiking — modern Asia with deep tradition.",
    positioningLine: "K-culture energy with palace-town charm.",
    idealTraveller: "Teens, K-culture fans and city explorers who like efficient transit and street food.",
    minimumNights: 5, idealNights: 7, maximumNights: 10,
    suitablePaces: ["balanced", "active"],
    interests: { city: 90, culture: 85, food: 88, shopping: 90, history: 78, nature: 70, nightlife: 82, themeparks: 72, snow: 60, romance: 72, adventure: 60, relaxation: 55, beach: 40, wildlife: 35 },
    suitability: { family: 72, toddlers: 60, children5To10: 70, teenagers: 92, seniors: 68, honeymoon: 75, solo: 90, firstInternationalTrip: 65 },
    food: { vegetarianFriendly: 50, indianFoodAvailability: 50, halalFriendly: 45, localCuisineScore: 92, streetFoodScore: 92, fineDiningScore: 85 },
    travelPracticality: { averageFlightHoursFromIndia: 8, walkingIntensity: "high", publicTransportEase: 95, roadTransferBurden: "low", accessibilityScore: 82, medicalAccessScore: 90 },
    budgetBands: ["comfort", "premium"],
    climateTags: ["temperate", "four-seasons", "monsoon-jul"],
    monthlyIntelligence: buildMonths({
      scores: [55, 58, 75, 88, 85, 70, 55, 55, 75, 90, 85, 60],
      temps: "temperateNorth",
      veryRainy: [7], rainy: [6, 8], humid: [6, 7, 8], dry: [10, 11, 1],
      crowded: [4, 10], quiet: [1, 2],
      highlights: { 4: ["Spring blossoms across Seoul's palaces"], 10: ["Autumn colours and festival season"] },
      warnings: { 7: ["Monsoon downpours"], 1: ["Sub-zero temperatures — pack for real winter"] },
    }),
    commonTripCombinations: ["Seoul + Busan", "Seoul + Jeju", "Japan + South Korea"],
    commonMistakes: ["Underestimating walking and stairs in palaces and markets", "Assuming easy vegetarian options everywhere"],
    packingConsiderations: ["Serious winter layers Dec–Feb", "Comfortable walking shoes", "T-money transit card on arrival"],
    practicalWarnings: ["Language barrier outside tourist cores — translation apps help"],
    tradeOffs: ["Language barrier outside tourist cores", "Vegetarian options need planning"],
    whoShouldAvoid: ["Travellers wanting warm beaches year-round"],
    extraSources: [TOURISM_BOARD_SOURCE("Korea Tourism Organization")],
    confidence: 84,
  }),

  dest({
    slug: "sri-lanka",
    name: "Sri Lanka",
    countryIso2: "LK",
    countryName: "Sri Lanka",
    region: "South Asia",
    summary:
      "Tea hills, leopard safaris, ancient citadels and palm-backed beaches packed into one compact island a short hop from India.",
    positioningLine: "Maximum variety, minimum flight time.",
    idealTraveller: "Variety seekers who want wildlife, hills, culture and beach in one short-haul trip.",
    minimumNights: 4, idealNights: 6, maximumNights: 10,
    suitablePaces: ["relaxed", "balanced", "active"],
    interests: { nature: 90, wildlife: 90, beach: 85, culture: 82, history: 85, relaxation: 80, adventure: 75, food: 75, romance: 78, city: 45, shopping: 45, nightlife: 40, themeparks: 20, snow: 0 },
    suitability: { family: 80, toddlers: 68, children5To10: 80, teenagers: 78, seniors: 75, honeymoon: 85, solo: 80, firstInternationalTrip: 88 },
    food: { vegetarianFriendly: 88, indianFoodAvailability: 90, halalFriendly: 75, localCuisineScore: 85, streetFoodScore: 75, fineDiningScore: 65 },
    travelPracticality: { averageFlightHoursFromIndia: 2, walkingIntensity: "medium", publicTransportEase: 55, roadTransferBurden: "high", accessibilityScore: 50, medicalAccessScore: 65 },
    budgetBands: ["value", "comfort", "premium"],
    climateTags: ["tropical", "two-monsoons", "regional-contrast"],
    monthlyIntelligence: buildMonths({
      scores: [90, 90, 85, 75, 60, 60, 65, 70, 65, 55, 60, 80],
      temps: "tropical",
      veryRainy: [10, 11], rainy: [5, 9, 12], humid: [4, 5, 6, 9, 10, 11],
      crowded: [12, 1, 2], quiet: [5, 9],
      highlights: { 1: ["Perfect south-west beach season"], 8: ["Kandy Esala Perahera festival (verify dates); east-coast beaches shine"] },
      warnings: { 10: ["Inter-monsoon rains island-wide"], 5: ["South-west monsoon begins"] },
    }),
    commonTripCombinations: ["Cultural triangle + tea country + south beaches", "Sri Lanka + Maldives"],
    commonMistakes: ["Judging distances by kilometres — hill roads are slow", "Booking west-coast beaches in monsoon months"],
    packingConsiderations: ["Layers for cool tea-country evenings", "Modest wear for temples", "Leech socks for rainforest walks (seasonal)"],
    practicalWarnings: ["Road journeys are slow — 100 km can take three hours in the hills"],
    tradeOffs: ["Road journeys are slow — distances deceive", "Two monsoons split the island's beach seasons"],
    whoShouldAvoid: ["Travellers wanting nightlife and big-city shopping"],
    extraSources: [TOURISM_BOARD_SOURCE("Sri Lanka Tourism")],
    confidence: 86,
  }),

  dest({
    slug: "maldives",
    name: "Maldives",
    countryIso2: "MV",
    countryName: "Maldives",
    region: "Indian Ocean",
    summary:
      "Overwater villas, house reefs and blue lagoons. The definitive fly-and-flop honeymoon, now also open to families and value seekers via guesthouse islands.",
    positioningLine: "The ultimate barefoot-luxury lagoon escape.",
    idealTraveller: "Honeymooners and anyone whose perfect day is lagoon, snorkel, spa, repeat.",
    minimumNights: 3, idealNights: 5, maximumNights: 7,
    suitablePaces: ["relaxed"],
    interests: { beach: 100, relaxation: 100, romance: 98, adventure: 55, nature: 70, food: 65, wildlife: 70, nightlife: 30, culture: 25, city: 5, shopping: 20, history: 15, themeparks: 0, snow: 0 },
    suitability: { family: 70, toddlers: 60, children5To10: 72, teenagers: 70, seniors: 78, honeymoon: 100, solo: 55, firstInternationalTrip: 85 },
    food: { vegetarianFriendly: 75, indianFoodAvailability: 80, halalFriendly: 95, localCuisineScore: 70, streetFoodScore: 40, fineDiningScore: 90 },
    travelPracticality: { averageFlightHoursFromIndia: 2.5, walkingIntensity: "low", publicTransportEase: 40, roadTransferBurden: "low", accessibilityScore: 60, medicalAccessScore: 55 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["tropical", "warm-all-year", "dry-season-dec-apr"],
    monthlyIntelligence: buildMonths({
      scores: [95, 95, 92, 85, 65, 55, 55, 60, 55, 60, 75, 88],
      temps: "tropical",
      veryRainy: [6, 9], rainy: [5, 7, 8, 10], humid: [5, 6, 7, 8, 9, 10],
      crowded: [12, 1, 2], quiet: [6, 9],
      highlights: { 2: ["Calm, glassy lagoons and best visibility"], 8: ["Manta and whale-shark season at Hanifaru Bay (verify)"] },
      warnings: { 6: ["South-west monsoon — brief squalls likely"], 9: ["Wettest weeks; seaplane delays possible"] },
    }),
    commonTripCombinations: ["Maldives + Sri Lanka", "Maldives + Dubai"],
    commonMistakes: ["Booking distant atolls with tight return flights — seaplane schedules shift", "Expecting sightseeing variety beyond the resort"],
    packingConsiderations: ["Reef-safe sunscreen", "Snorkel mask if you prefer your own fit", "Modest wear for local (non-resort) islands"],
    practicalWarnings: ["Alcohol only on resort islands, not local islands"],
    tradeOffs: ["One-island stays can feel small after five nights", "Premium resorts price everything à la carte"],
    whoShouldAvoid: ["Travellers who need sightseeing variety and city energy"],
    extraSources: [TOURISM_BOARD_SOURCE("Visit Maldives")],
    confidence: 88,
  }),

  dest({
    slug: "mauritius",
    name: "Mauritius",
    countryIso2: "MU",
    countryName: "Mauritius",
    region: "Indian Ocean",
    summary:
      "Lagoon beaches plus real island life — waterfalls, tea estates, sega music and a big Indian-origin culture. A honeymoon classic that families love too.",
    positioningLine: "Lagoon luxury with an island to explore.",
    idealTraveller: "Honeymooners and families who want beach-plus — lagoons and land adventures.",
    minimumNights: 5, idealNights: 6, maximumNights: 9,
    suitablePaces: ["relaxed", "balanced"],
    interests: { beach: 95, relaxation: 92, romance: 90, nature: 80, adventure: 70, food: 75, culture: 65, wildlife: 60, city: 30, shopping: 50, nightlife: 45, history: 50, themeparks: 25, snow: 0 },
    suitability: { family: 85, toddlers: 78, children5To10: 85, teenagers: 78, seniors: 85, honeymoon: 95, solo: 60, firstInternationalTrip: 85 },
    food: { vegetarianFriendly: 90, indianFoodAvailability: 92, halalFriendly: 85, localCuisineScore: 82, streetFoodScore: 75, fineDiningScore: 80 },
    travelPracticality: { averageFlightHoursFromIndia: 6.5, walkingIntensity: "low", publicTransportEase: 50, roadTransferBurden: "medium", accessibilityScore: 65, medicalAccessScore: 70 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["tropical", "southern-hemisphere", "cyclone-risk-jan-mar"],
    monthlyIntelligence: buildMonths({
      scores: [70, 65, 70, 80, 85, 80, 78, 80, 88, 90, 88, 78],
      temps: "temperateSouth", tempOverrides: { 5: "mild", 6: "mild", 7: "mild", 8: "mild", 9: "mild" },
      veryRainy: [1, 2], rainy: [3, 12], humid: [12, 1, 2, 3],
      crowded: [12, 10], quiet: [6],
      highlights: { 10: ["Warm, dry and flamboyant-tree bloom"], 5: ["Calm seas and green interiors"] },
      warnings: { 1: ["Cyclone season possibility"], 2: ["Cyclone season possibility"], 7: ["Windy on the east coast; cooler evenings"] },
    }),
    commonTripCombinations: ["Mauritius + Dubai stopover", "Mauritius + Rodrigues"],
    commonMistakes: ["Never leaving the resort — the island's south and west deserve a day each"],
    packingConsiderations: ["Light layers for breezy winter evenings (Jun–Aug)", "Reef shoes for lagoon walking", "Sun protection"],
    practicalWarnings: ["East coast is windy June–September — pick west/north stays then"],
    tradeOffs: ["Longer flight than Southeast Asian beach rivals", "Jan–Feb carries cyclone risk"],
    whoShouldAvoid: ["Travellers seeking buzzing nightlife"],
    extraSources: [TOURISM_BOARD_SOURCE("Mauritius Tourism Promotion Authority")],
    confidence: 86,
  }),

  dest({
    slug: "seychelles",
    name: "Seychelles",
    countryIso2: "SC",
    countryName: "Seychelles",
    region: "Indian Ocean",
    summary:
      "Granite boulders, jungle-backed coves and giant tortoises across Mahé, Praslin and La Digue — wilder and quieter than its rivals.",
    positioningLine: "Nature-first island romance, beautifully unpolished.",
    idealTraveller: "Couples who want raw beauty and quiet over resort polish and entertainment.",
    minimumNights: 5, idealNights: 7, maximumNights: 10,
    suitablePaces: ["relaxed"],
    interests: { beach: 98, nature: 90, romance: 92, relaxation: 95, wildlife: 80, adventure: 60, food: 65, culture: 40, city: 10, shopping: 25, nightlife: 25, history: 30, themeparks: 0, snow: 0 },
    suitability: { family: 68, toddlers: 60, children5To10: 70, teenagers: 65, seniors: 72, honeymoon: 95, solo: 55, firstInternationalTrip: 70 },
    food: { vegetarianFriendly: 65, indianFoodAvailability: 70, halalFriendly: 60, localCuisineScore: 78, streetFoodScore: 50, fineDiningScore: 80 },
    travelPracticality: { averageFlightHoursFromIndia: 5.5, walkingIntensity: "medium", publicTransportEase: 45, roadTransferBurden: "medium", accessibilityScore: 50, medicalAccessScore: 60 },
    budgetBands: ["premium", "luxury"],
    climateTags: ["tropical", "warm-all-year", "trade-wind-seasons"],
    monthlyIntelligence: buildMonths({
      scores: [70, 72, 80, 88, 85, 75, 70, 72, 80, 88, 85, 72],
      temps: "tropical",
      veryRainy: [1, 12], rainy: [2, 11], humid: [12, 1, 2, 3],
      crowded: [12, 4, 8], quiet: [6, 9],
      highlights: { 4: ["Glass-calm seas between trade winds"], 10: ["Second calm window — superb snorkelling"] },
      warnings: { 12: ["Wettest weeks of the north-west monsoon"], 7: ["South-east trades bring seaweed to some east-facing beaches"] },
    }),
    commonTripCombinations: ["Mahé + Praslin + La Digue island-hop", "Seychelles + Dubai stopover"],
    commonMistakes: ["Staying only on Mahé — La Digue is the postcard", "Expecting resort-style entertainment programmes"],
    packingConsiderations: ["Reef shoes for granite-and-coral entries", "Snorkel gear", "Light rain layer Nov–Jan"],
    practicalWarnings: ["Currents can be strong at some beaches — heed local advice"],
    tradeOffs: ["Highest price band of the Indian Ocean trio", "Limited nightlife and shopping"],
    whoShouldAvoid: ["Travellers wanting resort mega-facilities and entertainment programmes"],
    extraSources: [TOURISM_BOARD_SOURCE("Tourism Seychelles")],
    confidence: 82,
  }),

  dest({
    slug: "turkey",
    name: "Turkey",
    countryIso2: "TR",
    countryName: "Turkey",
    region: "Europe & Anatolia",
    summary:
      "Istanbul's minarets and bazaars, Cappadocia's balloon-filled dawns and a turquoise coast — east-meets-west drama at fair prices.",
    positioningLine: "Two continents of drama in one trip.",
    idealTraveller: "History and food lovers who enjoy multi-stop journeys and dramatic scenery.",
    minimumNights: 5, idealNights: 7, maximumNights: 12,
    suitablePaces: ["balanced", "active"],
    interests: { history: 95, culture: 92, food: 88, city: 82, adventure: 78, romance: 80, beach: 70, shopping: 80, nature: 75, relaxation: 60, nightlife: 65, wildlife: 30, themeparks: 30, snow: 40 },
    suitability: { family: 75, toddlers: 60, children5To10: 72, teenagers: 82, seniors: 70, honeymoon: 88, solo: 80, firstInternationalTrip: 75 },
    food: { vegetarianFriendly: 70, indianFoodAvailability: 55, halalFriendly: 95, localCuisineScore: 92, streetFoodScore: 88, fineDiningScore: 85 },
    travelPracticality: { averageFlightHoursFromIndia: 6.5, walkingIntensity: "high", publicTransportEase: 75, roadTransferBurden: "medium", accessibilityScore: 60, medicalAccessScore: 75 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["mediterranean", "continental-interior", "four-seasons"],
    monthlyIntelligence: buildMonths({
      scores: [55, 58, 70, 85, 90, 85, 75, 75, 90, 88, 72, 58],
      temps: "mediterranean", tempOverrides: { 1: "cold", 2: "cold", 12: "cold" },
      rainy: [1, 2, 12, 11], dry: [7, 8], humid: [7, 8],
      crowded: [7, 8], quiet: [1, 2],
      highlights: { 5: ["Ideal weather everywhere, Cappadocia at its best"], 9: ["Warm seas and thinning crowds"] },
      warnings: { 1: ["Cold and wet in Istanbul; snow inland"], 8: ["Interior heat peaks; book balloons early"] },
    }),
    commonTripCombinations: ["Istanbul + Cappadocia", "Istanbul + Antalya coast", "Turkey + Greece"],
    commonMistakes: ["Skipping the internal flight and losing a day on buses", "Booking balloons for a single morning with no weather buffer"],
    packingConsiderations: ["Layers — Istanbul, Cappadocia and the coast differ sharply", "Modest wear for mosques", "Sturdy shoes for cobblestones and valleys"],
    practicalWarnings: ["Balloon flights are weather-dependent — keep two mornings free"],
    tradeOffs: ["Ambitious multi-stop routings mean internal flights", "Summer interior heat can be intense"],
    whoShouldAvoid: ["Travellers wanting a single-resort, low-movement holiday"],
    extraSources: [TOURISM_BOARD_SOURCE("Go Türkiye")],
    confidence: 85,
  }),

  dest({
    slug: "georgia",
    name: "Georgia",
    countryIso2: "GE",
    countryName: "Georgia",
    region: "Caucasus",
    summary:
      "Tbilisi's balconied old town, Caucasus mountain drives, ancient wine country and monasteries — Europe-adjacent charm at gentle prices.",
    positioningLine: "Mountains, wine and old-world charm, visa-easy.",
    idealTraveller: "Adventurous couples and friends who like mountains, wine and unpolished charm.",
    minimumNights: 4, idealNights: 6, maximumNights: 9,
    suitablePaces: ["balanced", "active"],
    interests: { nature: 90, culture: 82, food: 85, history: 80, adventure: 80, city: 65, romance: 72, relaxation: 60, snow: 65, shopping: 45, nightlife: 60, beach: 35, wildlife: 40, themeparks: 15 },
    suitability: { family: 70, toddlers: 58, children5To10: 68, teenagers: 78, seniors: 65, honeymoon: 78, solo: 85, firstInternationalTrip: 72 },
    food: { vegetarianFriendly: 75, indianFoodAvailability: 50, halalFriendly: 55, localCuisineScore: 90, streetFoodScore: 70, fineDiningScore: 70 },
    travelPracticality: { averageFlightHoursFromIndia: 5, walkingIntensity: "high", publicTransportEase: 55, roadTransferBurden: "high", accessibilityScore: 45, medicalAccessScore: 60 },
    budgetBands: ["value", "comfort", "premium"],
    climateTags: ["continental", "mountain", "four-seasons"],
    monthlyIntelligence: buildMonths({
      scores: [50, 52, 65, 80, 88, 85, 78, 78, 88, 85, 65, 55],
      temps: "temperateNorth",
      rainy: [4, 5, 10], dry: [7, 8], humid: [7],
      crowded: [7, 8], quiet: [1, 2, 11],
      highlights: { 5: ["Green valleys and perfect mountain-road conditions"], 9: ["Rtveli grape-harvest season in Kakheti"] },
      warnings: { 1: ["High mountain passes may close (ski areas open)"], 12: ["Short daylight; icy mountain roads"] },
    }),
    commonTripCombinations: ["Tbilisi + Kazbegi + Kakheti", "Georgia + Azerbaijan"],
    commonMistakes: ["Day-tripping Kazbegi on a tight schedule — the road deserves time", "Expecting Western-Europe infrastructure"],
    packingConsiderations: ["Layers for mountain temperature swings", "Sturdy shoes for cobbles and trails", "Motion-sickness tablets for winding roads"],
    practicalWarnings: ["Mountain excursions involve long, winding drives"],
    tradeOffs: ["Mountain excursions involve long, winding drives", "Infrastructure is simpler than Western Europe"],
    whoShouldAvoid: ["Travellers needing step-free access throughout"],
    extraSources: [TOURISM_BOARD_SOURCE("Georgia Travel")],
    confidence: 80,
  }),

  dest({
    slug: "azerbaijan",
    name: "Azerbaijan",
    countryIso2: "AZ",
    countryName: "Azerbaijan",
    region: "Caucasus",
    summary:
      "Baku's flame towers beside a medieval walled city, mud volcanoes, burning hillsides and quick mountain escapes — a compact, offbeat city break.",
    positioningLine: "Futuristic Baku with fire-country day trips.",
    idealTraveller: "City-breakers who want somewhere genuinely different within five flight hours.",
    minimumNights: 3, idealNights: 5, maximumNights: 7,
    suitablePaces: ["relaxed", "balanced"],
    interests: { city: 85, culture: 75, history: 72, food: 78, adventure: 60, nature: 60, shopping: 65, nightlife: 70, romance: 65, relaxation: 55, snow: 30, beach: 30, wildlife: 20, themeparks: 20 },
    suitability: { family: 72, toddlers: 62, children5To10: 70, teenagers: 75, seniors: 75, honeymoon: 72, solo: 80, firstInternationalTrip: 80 },
    food: { vegetarianFriendly: 65, indianFoodAvailability: 60, halalFriendly: 90, localCuisineScore: 82, streetFoodScore: 65, fineDiningScore: 75 },
    travelPracticality: { averageFlightHoursFromIndia: 4.5, walkingIntensity: "medium", publicTransportEase: 70, roadTransferBurden: "medium", accessibilityScore: 60, medicalAccessScore: 65 },
    budgetBands: ["value", "comfort", "premium"],
    climateTags: ["semi-arid", "windy-caspian", "four-seasons"],
    monthlyIntelligence: buildMonths({
      scores: [55, 58, 68, 82, 88, 82, 70, 70, 85, 88, 70, 58],
      temps: "temperateNorth",
      rainy: [3, 4, 11], dry: [7, 8], humid: [7, 8],
      crowded: [6, 7], quiet: [1, 2],
      highlights: { 5: ["Mild Caspian spring — best city-walking weather"], 10: ["Golden autumn in the Caucasus foothills"] },
      warnings: { 7: ["Baku's summer winds and heat"], 1: ["Cold snaps; mountain roads icy"] },
    }),
    commonTripCombinations: ["Baku + Gabala", "Baku + Sheki", "Georgia + Azerbaijan"],
    commonMistakes: ["Allocating a week when five nights covers the highlights"],
    packingConsiderations: ["Windproof layer — Baku is the 'city of winds'", "Modest wear for mosques", "Comfortable shoes for old-city cobbles"],
    practicalWarnings: ["Caspian beach scene is limited — this is a city-and-culture trip"],
    tradeOffs: ["Fewer marquee sights beyond five nights", "Beach scene on the Caspian is limited"],
    whoShouldAvoid: ["Travellers expecting a classic beach holiday"],
    extraSources: [TOURISM_BOARD_SOURCE("Azerbaijan Tourism Board")],
    confidence: 78,
  }),

  dest({
    slug: "egypt",
    name: "Egypt",
    countryIso2: "EG",
    countryName: "Egypt",
    region: "North Africa",
    summary:
      "The Pyramids and the Sphinx, Nile cruises past ancient temples, and Red Sea reefs at Hurghada — five thousand years of wonder at approachable prices.",
    positioningLine: "The world's greatest ancient wonders, plus Red Sea blue.",
    idealTraveller: "History enthusiasts and families with school-age kids who dream of pharaohs.",
    minimumNights: 5, idealNights: 7, maximumNights: 10,
    suitablePaces: ["balanced", "active"],
    interests: { history: 98, culture: 90, adventure: 70, beach: 65, nature: 55, food: 65, romance: 68, city: 65, shopping: 60, relaxation: 55, wildlife: 40, nightlife: 45, themeparks: 15, snow: 0 },
    suitability: { family: 78, toddlers: 55, children5To10: 80, teenagers: 85, seniors: 68, honeymoon: 72, solo: 72, firstInternationalTrip: 70 },
    food: { vegetarianFriendly: 70, indianFoodAvailability: 45, halalFriendly: 98, localCuisineScore: 80, streetFoodScore: 75, fineDiningScore: 70 },
    travelPracticality: { averageFlightHoursFromIndia: 6, walkingIntensity: "medium", publicTransportEase: 45, roadTransferBurden: "high", accessibilityScore: 45, medicalAccessScore: 60 },
    budgetBands: ["value", "comfort", "premium"],
    climateTags: ["desert", "dry", "mild-winter"],
    monthlyIntelligence: buildMonths({
      scores: [88, 88, 85, 75, 60, 45, 40, 40, 55, 78, 88, 90],
      temps: "desert",
      dry: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      crowded: [12, 1], quiet: [6, 7, 8],
      highlights: { 12: ["Perfect temple-touring temperatures"], 2: ["Abu Simbel sun alignment (22 Feb — verify)"] },
      warnings: { 7: ["Upper Egypt exceeds 40°C — dawn starts only"], 8: ["Extreme heat at open-air sites"] },
    }),
    commonTripCombinations: ["Cairo + Nile cruise (Luxor–Aswan)", "Cairo + Hurghada", "Egypt + Jordan"],
    commonMistakes: ["Visiting open-air temples at midday in summer", "Skipping Luxor — Cairo alone misses the best temples"],
    packingConsiderations: ["Sun hat and high-SPF sunscreen", "Modest, breathable clothing", "Scarf for dust and sun"],
    practicalWarnings: ["Expect persistent vendors at major sites; a firm, polite no works"],
    tradeOffs: ["Summer heat is punishing at open-air sites", "Touting at major monuments requires patience"],
    whoShouldAvoid: ["Travellers wanting a polished, hassle-free resort experience only"],
    extraSources: [TOURISM_BOARD_SOURCE("Egyptian Tourism Authority")],
    confidence: 80,
  }),
];
