import type { DestinationIntelligence } from "../../src/types/knowledge";
import { buildMonths, dest, TOURISM_BOARD_SOURCE } from "./builders";

/** India domestic — Klar's home-ground expertise. Flight hours are typical
 *  domestic sector times from major metros. */
export const DESTINATIONS_7: DestinationIntelligence[] = [
  dest({
    slug: "goa",
    name: "Goa",
    countryIso2: "IN",
    countryName: "India",
    region: "India",
    summary:
      "Palm-fringed beaches from party-bright Baga to serene Palolem, Portuguese lanes and seafood shacks at sunset — India's easiest exhale.",
    positioningLine: "Beaches, shacks and susegad — India's favourite unwind.",
    idealTraveller: "Friends, couples and families who want beach ease without a passport.",
    minimumNights: 3, idealNights: 4, maximumNights: 7,
    suitablePaces: ["relaxed", "balanced"],
    interests: { beach: 95, relaxation: 90, nightlife: 85, food: 82, romance: 78, culture: 60, history: 62, nature: 55, adventure: 55, city: 30, shopping: 55, wildlife: 25, themeparks: 15, snow: 0 },
    suitability: { family: 80, toddlers: 70, children5To10: 78, teenagers: 85, seniors: 72, honeymoon: 82, solo: 80, firstInternationalTrip: 60 },
    food: { vegetarianFriendly: 75, indianFoodAvailability: 100, halalFriendly: 70, localCuisineScore: 88, streetFoodScore: 75, fineDiningScore: 72 },
    travelPracticality: { averageFlightHoursFromIndia: 1.5, walkingIntensity: "low", publicTransportEase: 40, roadTransferBurden: "medium", accessibilityScore: 55, medicalAccessScore: 70 },
    budgetBands: ["value", "comfort", "premium", "luxury"],
    climateTags: ["tropical-coast", "monsoon-jun-sep", "dry-winter"],
    monthlyIntelligence: buildMonths({
      scores: [90, 88, 75, 60, 45, 30, 30, 35, 50, 70, 85, 92],
      temps: "tropical",
      veryRainy: [6, 7, 8], rainy: [9, 10], humid: [4, 5, 6, 7, 8, 9], dry: [12, 1, 2],
      crowded: [12, 1], quiet: [6, 7, 8],
      highlights: { 12: ["Peak season sparkle — beach shacks, markets and festive nights"], 11: ["Sea calm again, crowds not yet peak — the connoisseur's window"] },
      warnings: { 6: ["Monsoon lashes the coast — most shacks shut, swimming unsafe"], 5: ["Pre-monsoon heat and humidity build"] },
    }),
    commonTripCombinations: ["North Goa + South Goa split", "Goa + Gokarna", "Extended weekend from any metro"],
    commonMistakes: ["Judging Goa by Baga alone — the south is a different island of calm", "Monsoon bookings expecting beach weather"],
    packingConsiderations: ["Reef-safe sunscreen", "Light cottons", "One smart-casual outfit for beach clubs"],
    practicalWarnings: ["Rent scooters only with helmets and licence checks; taxis are negotiation-heavy"],
    tradeOffs: ["Peak-season crowds and prices in December", "Public transport is thin — you'll need taxis or a scooter"],
    whoShouldAvoid: ["Travellers seeking mountain air or cultural depth as the main course"],
    extraSources: [TOURISM_BOARD_SOURCE("Goa Tourism")],
    confidence: 86,
  }),

  dest({
    slug: "kerala",
    name: "Kerala",
    countryIso2: "IN",
    countryName: "India",
    region: "India",
    summary:
      "Houseboats drifting the backwaters, mist over Munnar's tea, Ayurveda by the beach and food worth the trip alone — God's Own Country earns the name.",
    positioningLine: "Backwaters, tea hills and Ayurveda — India at its most serene.",
    idealTraveller: "Honeymooners, families and anyone whose ideal holiday is green, gentle and delicious.",
    minimumNights: 4, idealNights: 6, maximumNights: 10,
    suitablePaces: ["relaxed", "balanced"],
    interests: { nature: 92, relaxation: 90, romance: 85, food: 85, culture: 75, wildlife: 65, beach: 70, history: 60, adventure: 50, city: 30, shopping: 45, nightlife: 25, themeparks: 10, snow: 0 },
    suitability: { family: 85, toddlers: 72, children5To10: 80, teenagers: 75, seniors: 82, honeymoon: 92, solo: 75, firstInternationalTrip: 60 },
    food: { vegetarianFriendly: 85, indianFoodAvailability: 100, halalFriendly: 85, localCuisineScore: 92, streetFoodScore: 78, fineDiningScore: 70 },
    travelPracticality: { averageFlightHoursFromIndia: 2, walkingIntensity: "low", publicTransportEase: 50, roadTransferBurden: "medium", accessibilityScore: 55, medicalAccessScore: 75 },
    budgetBands: ["value", "comfort", "premium", "luxury"],
    climateTags: ["tropical", "double-monsoon", "hill-cool-munnar"],
    monthlyIntelligence: buildMonths({
      scores: [90, 88, 80, 65, 50, 35, 40, 45, 60, 75, 85, 90],
      temps: "tropical", tempOverrides: { 1: "warm", 12: "warm" },
      veryRainy: [6, 7], rainy: [5, 8, 10, 11], humid: [4, 5, 6, 7, 8, 9, 10],
      crowded: [12, 1], quiet: [6, 7],
      highlights: { 1: ["Perfect backwater mornings and temple-festival season"], 12: ["Peak houseboat weather; Munnar crisp and clear"] },
      warnings: { 6: ["Southwest monsoon in full force — an Ayurveda season, not a sightseeing one"], 10: ["Northeast monsoon brings afternoon downpours"] },
    }),
    commonTripCombinations: ["Kochi + Munnar + Alleppey classic triangle", "Add Thekkady wildlife or Kovalam beach", "Kerala + Kanyakumari"],
    commonMistakes: ["One-night houseboat bookings that spend half the time docking", "Underestimating hill-road hours to Munnar"],
    packingConsiderations: ["Light layers — Munnar evenings are genuinely cool", "Mosquito repellent for the backwaters"],
    practicalWarnings: ["Book quality houseboats well ahead for December–January"],
    tradeOffs: ["Distances are slow, winding hours — three bases minimum for the classic loop", "Nightlife is near-absent by design"],
    whoShouldAvoid: ["Party seekers", "Travellers who measure holidays in monuments per day"],
    extraSources: [TOURISM_BOARD_SOURCE("Kerala Tourism")],
    confidence: 86,
  }),

  dest({
    slug: "rajasthan",
    name: "Rajasthan",
    countryIso2: "IN",
    countryName: "India",
    region: "India",
    summary:
      "Amber forts glowing at sunset, blue Jodhpur and golden Jaisalmer, palace hotels and desert nights — the India of every imagination, real.",
    positioningLine: "Forts, palaces and desert gold — royal India, alive.",
    idealTraveller: "Culture lovers, photographers and celebration trips that deserve a palace.",
    minimumNights: 5, idealNights: 7, maximumNights: 12,
    suitablePaces: ["balanced", "active"],
    interests: { history: 96, culture: 94, romance: 82, food: 78, shopping: 80, adventure: 55, nature: 50, city: 60, wildlife: 45, relaxation: 50, nightlife: 35, beach: 0, themeparks: 5, snow: 0 },
    suitability: { family: 78, toddlers: 60, children5To10: 72, teenagers: 78, seniors: 72, honeymoon: 85, solo: 78, firstInternationalTrip: 60 },
    food: { vegetarianFriendly: 95, indianFoodAvailability: 100, halalFriendly: 75, localCuisineScore: 88, streetFoodScore: 85, fineDiningScore: 78 },
    travelPracticality: { averageFlightHoursFromIndia: 1.5, walkingIntensity: "high", publicTransportEase: 45, roadTransferBurden: "high", accessibilityScore: 45, medicalAccessScore: 65 },
    budgetBands: ["value", "comfort", "premium", "luxury"],
    climateTags: ["desert", "fierce-summer", "mild-winter"],
    monthlyIntelligence: buildMonths({
      scores: [92, 88, 70, 50, 35, 30, 40, 45, 60, 80, 90, 92],
      temps: "desert", tempOverrides: { 12: "mild", 1: "mild", 2: "mild" },
      rainy: [7, 8], dry: [10, 11, 12, 1, 2, 3],
      crowded: [12, 1, 2, 10], quiet: [5, 6],
      highlights: { 11: ["Pushkar fair season and flawless fort weather (verify fair dates)"], 1: ["Cool mornings, golden light — photography's favourite month"] },
      warnings: { 5: ["45°C afternoons make sightseeing genuinely unsafe by noon"], 6: ["Peak desert heat continues"] },
    }),
    commonTripCombinations: ["Jaipur + Jodhpur + Udaipur golden triangle-plus", "Add Jaisalmer desert overnight", "Rajasthan + Agra"],
    commonMistakes: ["Trying five cities in six nights — the roads eat your hours", "April–June visits without a heat plan"],
    packingConsiderations: ["Sun cover and serious hydration", "Modest wear for temples", "A warm layer for desert winter nights"],
    practicalWarnings: ["Fort visits are steep, cobbled and long — pace the elders"],
    tradeOffs: ["Winter is peak-priced and busy at headline forts", "Distances between cities are long road days"],
    whoShouldAvoid: ["Beach-first relaxers", "Anyone travelling April–June who dislikes extreme heat"],
    extraSources: [TOURISM_BOARD_SOURCE("Rajasthan Tourism")],
    confidence: 86,
  }),

  dest({
    slug: "himachal-pradesh",
    name: "Himachal Pradesh",
    countryIso2: "IN",
    countryName: "India",
    region: "India",
    summary:
      "Snow peaks over Manali, colonial Shimla, paragliders above Bir and cafés in Kasol — the Himalaya with a road to every mood.",
    positioningLine: "Hill stations, snow adventures and Himalayan calm.",
    idealTraveller: "Mountain-hungry families, honeymooners and friend groups chasing snow or slow.",
    minimumNights: 4, idealNights: 6, maximumNights: 10,
    suitablePaces: ["relaxed", "balanced", "active"],
    interests: { nature: 95, adventure: 85, snow: 85, romance: 80, relaxation: 75, food: 60, culture: 60, wildlife: 40, history: 55, city: 25, shopping: 45, nightlife: 30, beach: 0, themeparks: 5 },
    suitability: { family: 80, toddlers: 62, children5To10: 78, teenagers: 85, seniors: 68, honeymoon: 88, solo: 82, firstInternationalTrip: 60 },
    food: { vegetarianFriendly: 90, indianFoodAvailability: 100, halalFriendly: 60, localCuisineScore: 70, streetFoodScore: 65, fineDiningScore: 50 },
    travelPracticality: { averageFlightHoursFromIndia: 1.5, walkingIntensity: "medium", publicTransportEase: 35, roadTransferBurden: "high", accessibilityScore: 40, medicalAccessScore: 55 },
    budgetBands: ["value", "comfort", "premium"],
    climateTags: ["himalayan", "snow-winter", "monsoon-landslides-jul-aug"],
    monthlyIntelligence: buildMonths({
      scores: [58, 60, 70, 85, 90, 80, 50, 50, 70, 88, 80, 62],
      temps: "alpine",
      veryRainy: [7, 8], rainy: [6, 9],
      crowded: [5, 6, 12], quiet: [8, 2],
      highlights: { 5: ["Rohtang and high valleys open; orchards in fruit"], 10: ["Crystal post-monsoon views — the photographer's month"], 1: ["Reliable snow at Solang and Narkanda for first-snow joy"] },
      warnings: { 7: ["Monsoon landslides disrupt hill roads — build buffer days"], 8: ["Rains continue; valley views often clouded"] },
    }),
    commonTripCombinations: ["Shimla + Manali circuit", "Manali + Kasol + Bir", "Add Amritsar en route"],
    commonMistakes: ["Driving Chandigarh–Manali and sightseeing the same day — the road is the day", "Expecting snow in October — it's views, not snowfall"],
    packingConsiderations: ["True warm layers October–March", "Motion-sickness tablets for hairpin roads", "Sunscreen — mountain sun burns fast"],
    practicalWarnings: ["Winter snowfall can close Atal Tunnel approaches — keep plans flexible"],
    tradeOffs: ["Hill roads make every hop a half-day", "Peak May–June brings plains-escape crowds to Mall Roads"],
    whoShouldAvoid: ["Travellers who can't handle winding roads", "Step-free access needs"],
    extraSources: [TOURISM_BOARD_SOURCE("Himachal Tourism")],
    confidence: 84,
  }),

  dest({
    slug: "kashmir",
    name: "Kashmir",
    countryIso2: "IN",
    countryName: "India",
    region: "India",
    summary:
      "Shikaras gliding Dal Lake at dawn, Gulmarg's gondola into the snowline, saffron fields and chinar autumns — beauty that explains every poem.",
    positioningLine: "Dal Lake mornings, Gulmarg snows — the fabled valley.",
    idealTraveller: "Honeymooners and families chasing the classic houseboat-and-meadows dream.",
    minimumNights: 4, idealNights: 6, maximumNights: 9,
    suitablePaces: ["relaxed", "balanced"],
    interests: { nature: 96, romance: 90, snow: 80, relaxation: 80, culture: 65, food: 70, adventure: 65, history: 55, wildlife: 30, city: 25, shopping: 60, nightlife: 10, beach: 0, themeparks: 0 },
    suitability: { family: 80, toddlers: 62, children5To10: 78, teenagers: 80, seniors: 70, honeymoon: 95, solo: 70, firstInternationalTrip: 55 },
    food: { vegetarianFriendly: 60, indianFoodAvailability: 100, halalFriendly: 98, localCuisineScore: 85, streetFoodScore: 60, fineDiningScore: 55 },
    travelPracticality: { averageFlightHoursFromIndia: 1.5, walkingIntensity: "medium", publicTransportEase: 30, roadTransferBurden: "medium", accessibilityScore: 40, medicalAccessScore: 60 },
    budgetBands: ["value", "comfort", "premium", "luxury"],
    climateTags: ["himalayan-valley", "snow-winter", "mild-summer"],
    monthlyIntelligence: buildMonths({
      scores: [55, 60, 70, 88, 92, 85, 75, 75, 85, 88, 70, 58],
      temps: "alpine", tempOverrides: { 5: "mild", 6: "warm", 7: "warm", 8: "warm", 9: "mild" },
      rainy: [3, 4], dry: [9, 10, 11],
      crowded: [5, 6, 12], quiet: [2, 11],
      highlights: { 4: ["Tulip garden bloom against snow peaks (verify festival dates)"], 10: ["Chinar trees turn the valley copper and gold"], 1: ["Gulmarg's powder season — Asia's highest gondola into snow"] },
      warnings: { 1: ["Srinagar–Jammu highway can close in heavy snow — fly, and keep buffers"], 7: ["Warm-season crowds at headline gardens"] },
    }),
    commonTripCombinations: ["Srinagar + Gulmarg + Pahalgam classic", "Add Sonamarg day", "Kashmir + Vaishno Devi"],
    commonMistakes: ["Day-tripping Gulmarg in winter without booking gondola slots", "Treating a houseboat as just a hotel — sunset on the lake is the point"],
    packingConsiderations: ["Serious winter kit December–February", "Layers all year — valley evenings cool fast"],
    practicalWarnings: ["Weather and situational advisories can change plans — your Klar expert confirms current conditions before travel"],
    tradeOffs: ["Weather can rearrange itineraries at short notice", "Advisory checks are part of responsible planning here"],
    whoShouldAvoid: ["Travellers who need certainty over serendipity"],
    extraSources: [TOURISM_BOARD_SOURCE("Jammu & Kashmir Tourism")],
    confidence: 80,
  }),

  dest({
    slug: "andaman-islands",
    name: "Andaman Islands",
    countryIso2: "IN",
    countryName: "India",
    region: "India",
    summary:
      "Radhanagar's blue-white perfection, snorkelling straight off the beach, bioluminescent kayaking and cellular-jail history — India's island paradise without a passport.",
    positioningLine: "India's own island paradise — Maldives-blue, home-easy.",
    idealTraveller: "Honeymooners and families who want tropical-island beauty on Indian soil.",
    minimumNights: 4, idealNights: 6, maximumNights: 8,
    suitablePaces: ["relaxed", "balanced"],
    interests: { beach: 96, relaxation: 88, romance: 88, adventure: 75, nature: 80, wildlife: 55, history: 60, food: 60, culture: 40, city: 15, shopping: 25, nightlife: 20, themeparks: 0, snow: 0 },
    suitability: { family: 78, toddlers: 62, children5To10: 78, teenagers: 82, seniors: 62, honeymoon: 92, solo: 70, firstInternationalTrip: 60 },
    food: { vegetarianFriendly: 65, indianFoodAvailability: 100, halalFriendly: 70, localCuisineScore: 70, streetFoodScore: 50, fineDiningScore: 55 },
    travelPracticality: { averageFlightHoursFromIndia: 2.5, walkingIntensity: "low", publicTransportEase: 25, roadTransferBurden: "medium", accessibilityScore: 40, medicalAccessScore: 50 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["tropical-island", "monsoon-may-sep", "calm-dec-apr"],
    monthlyIntelligence: buildMonths({
      scores: [90, 90, 85, 75, 55, 35, 35, 40, 50, 65, 80, 88],
      temps: "tropical",
      veryRainy: [5, 6, 7, 8], rainy: [9, 10], humid: [4, 5, 6, 7, 8, 9, 10, 11],
      crowded: [12, 1], quiet: [6, 7, 8],
      highlights: { 1: ["Glass-calm seas — peak snorkelling and dive visibility"], 12: ["Postcard weather across Havelock and Neil"] },
      warnings: { 6: ["Monsoon swells cancel ferries and water sports"], 5: ["Season winding down; sea states unpredictable"] },
    }),
    commonTripCombinations: ["Port Blair + Havelock (Swaraj) + Neil classic", "Add Baratang limestone caves"],
    commonMistakes: ["Booking tight flight connections around ferry schedules", "Skipping advance ferry booking in peak season"],
    packingConsiderations: ["Reef-safe sunscreen and snorkel mask", "Light rain shell even in season", "Cash — ATMs are scarce on smaller islands"],
    practicalWarnings: ["Certain tribal-area and foreign-national permits differ — your Klar expert confirms the current rules"],
    tradeOffs: ["Reaching the islands takes a full travel day each way", "Connectivity and nightlife are minimal — that's the charm"],
    whoShouldAvoid: ["Travellers needing constant connectivity or urban buzz"],
    extraSources: [TOURISM_BOARD_SOURCE("Andaman & Nicobar Tourism")],
    confidence: 82,
  }),

  dest({
    slug: "ladakh",
    name: "Ladakh",
    countryIso2: "IN",
    countryName: "India",
    region: "India",
    summary:
      "Moonscape passes above 5,000m, Pangong's impossible blues, monasteries on crags and roads that became legends — India's great high-altitude adventure.",
    positioningLine: "High passes, Pangong blues — the adventure of a lifetime.",
    idealTraveller: "Adventurers, riders and landscape addicts ready to respect altitude.",
    minimumNights: 5, idealNights: 7, maximumNights: 12,
    suitablePaces: ["balanced", "active"],
    interests: { adventure: 96, nature: 96, culture: 70, snow: 60, romance: 65, history: 60, wildlife: 45, relaxation: 40, food: 50, city: 10, shopping: 35, nightlife: 5, beach: 0, themeparks: 0 },
    suitability: { family: 55, toddlers: 25, children5To10: 45, teenagers: 78, seniors: 45, honeymoon: 72, solo: 88, firstInternationalTrip: 40 },
    food: { vegetarianFriendly: 80, indianFoodAvailability: 100, halalFriendly: 60, localCuisineScore: 65, streetFoodScore: 50, fineDiningScore: 35 },
    travelPracticality: { averageFlightHoursFromIndia: 1.5, walkingIntensity: "high", publicTransportEase: 15, roadTransferBurden: "high", accessibilityScore: 25, medicalAccessScore: 45 },
    budgetBands: ["value", "comfort", "premium"],
    climateTags: ["high-altitude-desert", "season-jun-sep", "extreme-winter"],
    monthlyIntelligence: buildMonths({
      scores: [30, 30, 35, 55, 75, 90, 92, 90, 88, 70, 40, 30],
      temps: "alpine", tempOverrides: { 6: "mild", 7: "mild", 8: "mild", 12: "cold", 1: "cold", 2: "cold" },
      dry: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      crowded: [7, 8], quiet: [11, 12, 1, 2, 3],
      highlights: { 7: ["Every pass open — Pangong, Nubra and Khardung La in full glory"], 9: ["Golden light, thinning crowds, roads still open"], 1: ["Chadar frozen-river trek season for the truly hardy (expert-led only)"] },
      warnings: { 1: ["-20°C and closed roads — flights only, specialist trips only"], 4: ["High passes still snowed shut; itineraries limited"] },
    }),
    commonTripCombinations: ["Leh + Nubra + Pangong circuit", "Manali–Leh or Srinagar–Leh road journeys", "Add Turtuk village"],
    commonMistakes: ["No acclimatisation day in Leh — altitude sickness ruins more trips than weather", "Cramming Pangong as a day trip — stay the night"],
    packingConsiderations: ["Altitude medication after doctor's advice", "Sun protection — UV is fierce at 3,500m", "Warm layers even in July nights"],
    practicalWarnings: ["Inner Line Permits apply for several areas — your Klar expert arranges current requirements"],
    tradeOffs: ["Altitude is a real medical consideration — this trip is earned", "Comforts are simple outside Leh"],
    whoShouldAvoid: ["Travellers with heart/respiratory conditions without medical clearance", "Toddler families", "Comfort-first travellers"],
    extraSources: [TOURISM_BOARD_SOURCE("Ladakh Tourism")],
    confidence: 82,
  }),

  dest({
    slug: "sikkim-darjeeling",
    name: "Sikkim & Darjeeling",
    countryIso2: "IN",
    countryName: "India",
    region: "India",
    summary:
      "Kanchenjunga filling the dawn sky, toy-train whistles through tea gardens, monastery valleys and momos done right — the gentle Himalaya of the east.",
    positioningLine: "Kanchenjunga dawns, tea gardens and monastery calm.",
    idealTraveller: "Tea-and-mountains romantics, families and slow travellers.",
    minimumNights: 4, idealNights: 6, maximumNights: 9,
    suitablePaces: ["relaxed", "balanced"],
    interests: { nature: 92, culture: 78, relaxation: 78, romance: 75, food: 70, adventure: 60, history: 60, wildlife: 40, snow: 45, city: 20, shopping: 45, nightlife: 15, beach: 0, themeparks: 0 },
    suitability: { family: 78, toddlers: 60, children5To10: 75, teenagers: 75, seniors: 70, honeymoon: 82, solo: 80, firstInternationalTrip: 55 },
    food: { vegetarianFriendly: 80, indianFoodAvailability: 100, halalFriendly: 55, localCuisineScore: 80, streetFoodScore: 75, fineDiningScore: 45 },
    travelPracticality: { averageFlightHoursFromIndia: 2, walkingIntensity: "medium", publicTransportEase: 30, roadTransferBurden: "high", accessibilityScore: 35, medicalAccessScore: 55 },
    budgetBands: ["value", "comfort", "premium"],
    climateTags: ["eastern-himalaya", "monsoon-jun-sep", "clear-oct-nov"],
    monthlyIntelligence: buildMonths({
      scores: [60, 65, 80, 88, 80, 50, 40, 40, 65, 90, 85, 65],
      temps: "alpine", tempOverrides: { 4: "mild", 5: "mild", 6: "mild", 9: "mild", 10: "mild" },
      veryRainy: [6, 7, 8], rainy: [5, 9],
      crowded: [4, 5, 10], quiet: [7, 8, 1],
      highlights: { 10: ["Post-monsoon Kanchenjunga views at their sharpest"], 4: ["Rhododendrons and magnolias paint the ridges"], 3: ["Tea first-flush season around Darjeeling"] },
      warnings: { 7: ["Monsoon hides the peaks and loosens hill roads"], 1: ["Cold and occasionally snow-blocked in North Sikkim"] },
    }),
    commonTripCombinations: ["Darjeeling + Gangtok classic", "Add Pelling or Lachung/Yumthang", "Tie in Kalimpong"],
    commonMistakes: ["Monsoon visits hoping for mountain views", "Skipping the 4am Tiger Hill sunrise — it's the whole point"],
    packingConsiderations: ["Layers year-round; real warmth November–February", "Rain shell in any month"],
    practicalWarnings: ["North Sikkim requires permits arranged via registered operators — your Klar expert handles it"],
    tradeOffs: ["Hill roads are slow and weather-dependent", "Luxury inventory is limited outside a few heritage stays"],
    whoShouldAvoid: ["Step-free access needs", "Beach-and-pool holidaymakers"],
    extraSources: [TOURISM_BOARD_SOURCE("Sikkim Tourism"), TOURISM_BOARD_SOURCE("West Bengal Tourism")],
    confidence: 82,
  }),
];
