import type { DestinationIntelligence } from "../../src/types/knowledge";
import { buildMonths, dest, TOURISM_BOARD_SOURCE } from "./builders";

export const DESTINATIONS_4: DestinationIntelligence[] = [
  dest({
    slug: "hong-kong",
    name: "Hong Kong",
    countryIso2: "HK",
    countryName: "Hong Kong",
    region: "East Asia",
    summary:
      "Skyline drama over Victoria Harbour, Disneyland, dim sum and mountain trams — a dense, thrilling city break that families and foodies both love.",
    positioningLine: "Vertical city energy with Disney magic and dim sum.",
    idealTraveller: "City-break families and food lovers who want maximum spectacle in few days.",
    minimumNights: 3, idealNights: 4, maximumNights: 6,
    suitablePaces: ["balanced", "active"],
    interests: { city: 95, food: 90, shopping: 90, themeparks: 85, culture: 70, nightlife: 78, history: 60, nature: 60, relaxation: 45, romance: 65, adventure: 55, beach: 35, wildlife: 25, snow: 0 },
    suitability: { family: 85, toddlers: 75, children5To10: 88, teenagers: 88, seniors: 75, honeymoon: 70, solo: 85, firstInternationalTrip: 80 },
    food: { vegetarianFriendly: 60, indianFoodAvailability: 70, halalFriendly: 55, localCuisineScore: 95, streetFoodScore: 92, fineDiningScore: 95 },
    travelPracticality: { averageFlightHoursFromIndia: 6, walkingIntensity: "high", publicTransportEase: 96, roadTransferBurden: "low", accessibilityScore: 85, medicalAccessScore: 92 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["subtropical", "humid-summer", "typhoon-season-jul-sep"],
    monthlyIntelligence: buildMonths({
      scores: [72, 70, 75, 78, 70, 60, 55, 55, 60, 85, 90, 85],
      temps: "mediterranean", tempOverrides: { 6: "hot", 7: "hot", 8: "hot", 9: "hot", 12: "mild", 1: "mild", 2: "mild" },
      veryRainy: [6, 7, 8], rainy: [4, 5, 9], humid: [4, 5, 6, 7, 8, 9],
      crowded: [12, 10], quiet: [6, 9],
      highlights: { 11: ["Clear, dry hiking and harbour weather — the city's best month"], 12: ["Winter light shows over the harbour"] },
      warnings: { 8: ["Typhoon season — outdoor plans need backups"], 7: ["Hot, humid and stormy"] },
    }),
    commonTripCombinations: ["Hong Kong + Macau", "Hong Kong + Disneyland day", "Hong Kong stopover"],
    commonMistakes: ["Cramming Disneyland and the Peak into one day", "Skipping the islands and trails entirely"],
    packingConsiderations: ["Comfortable shoes for steep streets", "Compact umbrella", "A layer for icy indoor air-conditioning"],
    practicalWarnings: ["Octopus card makes all transport effortless — get one on arrival"],
    tradeOffs: ["Dense and fast-paced — not a resort-style rest", "Hotel rooms are famously compact"],
    whoShouldAvoid: ["Travellers wanting space, calm and beach mornings"],
    extraSources: [TOURISM_BOARD_SOURCE("Hong Kong Tourism Board")],
    confidence: 84,
  }),

  dest({
    slug: "nepal",
    name: "Nepal",
    countryIso2: "NP",
    countryName: "Nepal",
    region: "South Asia",
    summary:
      "Everest views without climbing, Pokhara's lakeside calm, Kathmandu's living temples and some of Earth's best trekking — the Himalaya next door.",
    positioningLine: "The Himalaya next door — epic views, easy visas, gentle prices.",
    idealTraveller: "Mountain lovers, trekkers and culture seekers on any budget.",
    minimumNights: 4, idealNights: 6, maximumNights: 12,
    suitablePaces: ["relaxed", "balanced", "active"],
    interests: { nature: 95, adventure: 92, culture: 85, history: 78, wildlife: 65, relaxation: 60, food: 65, romance: 60, snow: 70, city: 50, shopping: 50, nightlife: 40, beach: 0, themeparks: 5 },
    suitability: { family: 70, toddlers: 55, children5To10: 68, teenagers: 82, seniors: 62, honeymoon: 72, solo: 90, firstInternationalTrip: 85 },
    food: { vegetarianFriendly: 90, indianFoodAvailability: 92, halalFriendly: 60, localCuisineScore: 80, streetFoodScore: 72, fineDiningScore: 55 },
    travelPracticality: { averageFlightHoursFromIndia: 2, walkingIntensity: "high", publicTransportEase: 35, roadTransferBurden: "high", accessibilityScore: 40, medicalAccessScore: 55 },
    budgetBands: ["value", "comfort", "premium"],
    climateTags: ["mountain", "monsoon-jun-sep", "clear-autumn"],
    monthlyIntelligence: buildMonths({
      scores: [70, 75, 85, 88, 75, 50, 45, 45, 60, 92, 90, 78],
      temps: "temperateNorth", tempOverrides: { 6: "warm", 7: "warm", 8: "warm" },
      veryRainy: [7, 8], rainy: [6, 9], humid: [6, 7, 8],
      crowded: [10, 11, 4], quiet: [7, 8],
      highlights: { 10: ["Crystal Himalayan visibility — the classic trekking window"], 4: ["Rhododendron bloom on the trails"] },
      warnings: { 7: ["Monsoon — mountains hidden, trails leech-prone"], 8: ["Monsoon continues; domestic flights disrupted"] },
    }),
    commonTripCombinations: ["Kathmandu + Pokhara", "Kathmandu + Chitwan safari", "Short Annapurna treks"],
    commonMistakes: ["Expecting to see Everest from Kathmandu — take the mountain flight or go to viewpoints", "Underestimating road journey times"],
    packingConsiderations: ["Layers — valley warm, viewpoints cold", "Sturdy walking shoes", "Motion-sickness tablets for hill roads"],
    practicalWarnings: ["Domestic mountain flights are weather-dependent — build buffer days"],
    tradeOffs: ["Infrastructure is basic outside main hubs", "Monsoon months hide the mountains entirely"],
    whoShouldAvoid: ["Travellers needing step-free access or luxury polish throughout"],
    extraSources: [TOURISM_BOARD_SOURCE("Nepal Tourism Board")],
    confidence: 82,
  }),

  dest({
    slug: "bhutan",
    name: "Bhutan",
    countryIso2: "BT",
    countryName: "Bhutan",
    region: "South Asia",
    summary:
      "Cliffside monasteries, prayer flags over pine valleys and a kingdom that measures happiness — travel's most serene bucket-list stamp.",
    positioningLine: "The happiness kingdom — serene, sacred, unforgettable.",
    idealTraveller: "Seekers of calm, culture and mountain beauty who value depth over checklists.",
    minimumNights: 4, idealNights: 6, maximumNights: 9,
    suitablePaces: ["relaxed", "balanced"],
    interests: { culture: 95, nature: 92, history: 85, relaxation: 85, adventure: 70, romance: 75, wildlife: 45, food: 60, snow: 40, city: 25, shopping: 30, nightlife: 10, beach: 0, themeparks: 0 },
    suitability: { family: 68, toddlers: 55, children5To10: 65, teenagers: 75, seniors: 70, honeymoon: 85, solo: 78, firstInternationalTrip: 75 },
    food: { vegetarianFriendly: 85, indianFoodAvailability: 85, halalFriendly: 45, localCuisineScore: 72, streetFoodScore: 45, fineDiningScore: 60 },
    travelPracticality: { averageFlightHoursFromIndia: 2.5, walkingIntensity: "medium", publicTransportEase: 30, roadTransferBurden: "high", accessibilityScore: 45, medicalAccessScore: 55 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["mountain", "monsoon-jun-aug", "clear-spring-autumn"],
    monthlyIntelligence: buildMonths({
      scores: [65, 72, 85, 90, 80, 55, 50, 55, 75, 92, 88, 70],
      temps: "temperateNorth",
      veryRainy: [7], rainy: [6, 8], humid: [6, 7, 8],
      crowded: [4, 10], quiet: [7, 8, 1],
      highlights: { 4: ["Paro Tshechu festival season and valley blossoms (verify dates)"], 10: ["Thimphu Tshechu and flawless mountain skies (verify dates)"] },
      warnings: { 7: ["Monsoon clouds hide the Himalaya"], 1: ["High passes cold; some hotels minimally heated"] },
    }),
    commonTripCombinations: ["Paro + Thimphu + Punakha", "Bhutan + Nepal"],
    commonMistakes: ["Attempting Tiger's Nest on arrival day before acclimatising", "Over-packing the itinerary — Bhutan rewards slowness"],
    packingConsiderations: ["Modest layers for dzongs and temples", "Broken-in walking shoes for the Tiger's Nest climb", "Warm evening layers year-round"],
    practicalWarnings: ["Sustainable Development Fee and guided-travel rules apply — your Klar expert will confirm current requirements"],
    tradeOffs: ["Daily tourism fees make it a premium trip", "Winding mountain roads between valleys"],
    whoShouldAvoid: ["Nightlife seekers and tight-budget travellers"],
    extraSources: [TOURISM_BOARD_SOURCE("Department of Tourism, Bhutan")],
    confidence: 80,
  }),

  dest({
    slug: "oman",
    name: "Oman",
    countryIso2: "OM",
    countryName: "Oman",
    region: "Middle East",
    summary:
      "Wadis of turquoise water, dune camps under the Milky Way, forts and a gracious capital — Arabia's most authentic, uncrowded escape.",
    positioningLine: "Authentic Arabia — wadis, dunes and genuine welcome.",
    idealTraveller: "Couples and families who want Gulf ease without Gulf glitz.",
    minimumNights: 4, idealNights: 6, maximumNights: 9,
    suitablePaces: ["relaxed", "balanced"],
    interests: { nature: 88, adventure: 82, culture: 80, history: 75, beach: 70, relaxation: 75, romance: 78, food: 65, wildlife: 55, city: 55, shopping: 50, nightlife: 25, themeparks: 10, snow: 0 },
    suitability: { family: 82, toddlers: 70, children5To10: 82, teenagers: 82, seniors: 75, honeymoon: 85, solo: 72, firstInternationalTrip: 78 },
    food: { vegetarianFriendly: 70, indianFoodAvailability: 90, halalFriendly: 98, localCuisineScore: 75, streetFoodScore: 55, fineDiningScore: 75 },
    travelPracticality: { averageFlightHoursFromIndia: 3, walkingIntensity: "medium", publicTransportEase: 35, roadTransferBurden: "medium", accessibilityScore: 65, medicalAccessScore: 80 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["desert", "mild-winter", "khareef-monsoon-south"],
    monthlyIntelligence: buildMonths({
      scores: [90, 88, 82, 70, 50, 40, 45, 50, 60, 78, 88, 90],
      temps: "desert",
      dry: [10, 11, 12, 1, 2, 3], humid: [6, 7, 8],
      crowded: [12, 1], quiet: [5, 6],
      highlights: { 12: ["Perfect wadi-swimming and desert-camp weather"], 7: ["Khareef season turns Salalah green (regional exception)"] },
      warnings: { 6: ["Extreme heat away from the Salalah monsoon belt"], 7: ["Muscat is very hot; Salalah is the summer story"] },
    }),
    commonTripCombinations: ["Muscat + Wahiba Sands + Nizwa", "Oman + Dubai", "Salalah khareef escape"],
    commonMistakes: ["Day-tripping the desert — the overnight camp is the magic", "Skipping travel insurance for wadi and dune driving"],
    packingConsiderations: ["Modest, breathable clothing", "Water shoes for wadis", "A warm layer for desert nights"],
    practicalWarnings: ["Wadi swimming depends on flash-flood conditions — heed local advice"],
    tradeOffs: ["Self-drive or private driver is near-essential", "Quiet evenings — nightlife is minimal"],
    whoShouldAvoid: ["Travellers wanting buzzing city nights and malls-first holidays"],
    extraSources: [TOURISM_BOARD_SOURCE("Experience Oman")],
    confidence: 82,
  }),

  dest({
    slug: "qatar",
    name: "Qatar",
    countryIso2: "QA",
    countryName: "Qatar",
    region: "Middle East",
    summary:
      "The Museum of Islamic Art, a futuristic skyline, souq lanes and inland-sea dunes — a polished long-weekend stopover that grew into a destination.",
    positioningLine: "Polished Gulf stopover with world-class museums.",
    idealTraveller: "Stopover travellers and culture-curious families on short breaks.",
    minimumNights: 2, idealNights: 4, maximumNights: 5,
    suitablePaces: ["relaxed", "balanced"],
    interests: { city: 85, culture: 80, shopping: 82, food: 75, history: 60, beach: 60, adventure: 60, relaxation: 65, romance: 65, nightlife: 45, nature: 40, wildlife: 20, themeparks: 45, snow: 0 },
    suitability: { family: 85, toddlers: 78, children5To10: 85, teenagers: 82, seniors: 82, honeymoon: 70, solo: 75, firstInternationalTrip: 85 },
    food: { vegetarianFriendly: 75, indianFoodAvailability: 92, halalFriendly: 98, localCuisineScore: 78, streetFoodScore: 60, fineDiningScore: 88 },
    travelPracticality: { averageFlightHoursFromIndia: 3.5, walkingIntensity: "low", publicTransportEase: 85, roadTransferBurden: "low", accessibilityScore: 90, medicalAccessScore: 92 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["desert", "dry-winter", "extreme-summer"],
    monthlyIntelligence: buildMonths({
      scores: [90, 88, 80, 68, 50, 35, 32, 32, 45, 70, 85, 90],
      temps: "desert",
      humid: [6, 7, 8, 9], dry: [11, 12, 1, 2],
      crowded: [12, 2], quiet: [6, 7, 8],
      highlights: { 1: ["Corniche weather at its finest"], 11: ["Outdoor souq evenings return"] },
      warnings: { 7: ["Extreme heat — indoor itinerary only"], 8: ["Extreme heat and humidity"] },
    }),
    commonTripCombinations: ["Doha stopover en route to Europe", "Doha + desert inland sea day"],
    commonMistakes: ["Treating it as airport-only — the museums deserve a day each"],
    packingConsiderations: ["Modest wear for souqs and mosques", "Sun protection", "Light layers for fierce indoor air-conditioning"],
    practicalWarnings: ["Ramadan changes dining hours — check dates"],
    tradeOffs: ["Compact sight list — best under five nights", "Summer is brutally hot"],
    whoShouldAvoid: ["Travellers seeking nature, hiking or nightlife depth"],
    extraSources: [TOURISM_BOARD_SOURCE("Visit Qatar")],
    confidence: 80,
  }),

  dest({
    slug: "cambodia",
    name: "Cambodia",
    countryIso2: "KH",
    countryName: "Cambodia",
    region: "Southeast Asia",
    summary:
      "Angkor Wat's sunrise silhouette, floating villages and a gentle, resilient culture — one of travel's great wonders at everyday prices.",
    positioningLine: "Angkor's temples — the wonder that exceeds the hype.",
    idealTraveller: "Culture and history lovers pairing a wonder-of-the-world with easy value.",
    minimumNights: 3, idealNights: 5, maximumNights: 8,
    suitablePaces: ["relaxed", "balanced"],
    interests: { history: 95, culture: 92, nature: 65, food: 70, adventure: 60, relaxation: 60, romance: 70, wildlife: 45, city: 45, shopping: 45, nightlife: 55, beach: 40, themeparks: 5, snow: 0 },
    suitability: { family: 72, toddlers: 58, children5To10: 72, teenagers: 80, seniors: 68, honeymoon: 78, solo: 88, firstInternationalTrip: 75 },
    food: { vegetarianFriendly: 70, indianFoodAvailability: 55, halalFriendly: 50, localCuisineScore: 82, streetFoodScore: 80, fineDiningScore: 65 },
    travelPracticality: { averageFlightHoursFromIndia: 5.5, walkingIntensity: "high", publicTransportEase: 40, roadTransferBurden: "medium", accessibilityScore: 45, medicalAccessScore: 55 },
    budgetBands: ["value", "comfort", "premium"],
    climateTags: ["tropical", "monsoon-may-oct", "hot-all-year"],
    monthlyIntelligence: buildMonths({
      scores: [90, 88, 78, 65, 55, 52, 52, 55, 50, 60, 80, 90],
      temps: "equatorialHot", tempOverrides: { 12: "warm", 1: "warm" },
      veryRainy: [9, 10], rainy: [5, 6, 7, 8], humid: [4, 5, 6, 7, 8, 9, 10],
      crowded: [12, 1, 2], quiet: [9],
      highlights: { 12: ["Dry-season temple weather at its kindest"], 8: ["Lush green moats and fewer crowds (showers pass fast)"] },
      warnings: { 4: ["April is the hottest month — dawn starts essential"], 9: ["Heaviest rains; some rural roads flood"] },
    }),
    commonTripCombinations: ["Siem Reap + Phnom Penh", "Cambodia + Vietnam", "Cambodia + Bangkok"],
    commonMistakes: ["One-day Angkor sprints — three days reveals the magic", "Midday temple visits in the heat"],
    packingConsiderations: ["Temple-appropriate clothing (shoulders/knees)", "Serious sun protection", "Broken-in walking shoes for temple steps"],
    practicalWarnings: ["Temple steps are steep and uneven — take them slowly"],
    tradeOffs: ["Beyond the temples, sights are quieter and simpler", "Hot and humid most of the year"],
    whoShouldAvoid: ["Travellers uninterested in temples and history"],
    extraSources: [TOURISM_BOARD_SOURCE("Ministry of Tourism Cambodia")],
    confidence: 82,
  }),

  dest({
    slug: "kenya",
    name: "Kenya",
    countryIso2: "KE",
    countryName: "Kenya",
    region: "Africa",
    summary:
      "The Masai Mara's great migration, elephants beneath Kilimanjaro at Amboseli and Indian Ocean beaches at Diani — safari's beating heart.",
    positioningLine: "The classic safari — the Mara, up close.",
    idealTraveller: "Wildlife dreamers ready for early mornings and open-roof wonder.",
    minimumNights: 5, idealNights: 7, maximumNights: 12,
    suitablePaces: ["balanced", "active"],
    interests: { wildlife: 100, nature: 95, adventure: 85, romance: 78, relaxation: 55, culture: 65, beach: 60, food: 60, city: 40, history: 45, shopping: 35, nightlife: 35, themeparks: 0, snow: 5 },
    suitability: { family: 75, toddlers: 50, children5To10: 78, teenagers: 88, seniors: 70, honeymoon: 88, solo: 70, firstInternationalTrip: 60 },
    food: { vegetarianFriendly: 70, indianFoodAvailability: 80, halalFriendly: 70, localCuisineScore: 72, streetFoodScore: 55, fineDiningScore: 75 },
    travelPracticality: { averageFlightHoursFromIndia: 6.5, walkingIntensity: "low", publicTransportEase: 30, roadTransferBurden: "high", accessibilityScore: 50, medicalAccessScore: 65 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["equatorial-highland", "two-rain-seasons", "dry-jul-oct"],
    monthlyIntelligence: buildMonths({
      scores: [80, 82, 70, 55, 55, 75, 90, 95, 90, 78, 60, 78],
      temps: "highlandTropical",
      veryRainy: [4, 11], rainy: [3, 5, 12], humid: [4, 5, 11],
      crowded: [7, 8, 9], quiet: [4, 5, 11],
      highlights: { 8: ["Great migration river crossings in the Mara (timing varies — verify)"], 2: ["Calving season and superb predator action"] },
      warnings: { 4: ["Long rains — some camps close, roads challenging"], 11: ["Short rains; afternoon storms"] },
    }),
    commonTripCombinations: ["Masai Mara + Amboseli", "Safari + Diani Beach", "Kenya + Tanzania"],
    commonMistakes: ["Two-night safari sprints — three nights per park minimum", "Expecting guaranteed migration crossings on fixed dates"],
    packingConsiderations: ["Neutral-coloured layers (cold dawns, warm middays)", "Binoculars per person", "Soft duffel bags for light aircraft"],
    practicalWarnings: ["Yellow-fever and malaria precautions apply — confirm medical requirements with your doctor and Klar expert"],
    tradeOffs: ["Safari pricing is premium by nature", "Long, bumpy park transfers between reserves"],
    whoShouldAvoid: ["Travellers who dislike early starts and rustic remoteness"],
    extraSources: [TOURISM_BOARD_SOURCE("Magical Kenya")],
    confidence: 82,
  }),

  dest({
    slug: "morocco",
    name: "Morocco",
    countryIso2: "MA",
    countryName: "Morocco",
    region: "North Africa",
    summary:
      "Marrakech's drum-beating square, blue Chefchaouen, Sahara camel camps and riad courtyards — a sensory kaleidoscope three continents seem to share.",
    positioningLine: "A sensory kaleidoscope — souks, Sahara and blue cities.",
    idealTraveller: "Colour-and-culture chasers comfortable with delightful chaos.",
    minimumNights: 5, idealNights: 7, maximumNights: 12,
    suitablePaces: ["balanced", "active"],
    interests: { culture: 95, history: 85, adventure: 80, shopping: 85, food: 82, romance: 80, nature: 70, relaxation: 55, city: 70, nightlife: 45, beach: 45, wildlife: 20, themeparks: 0, snow: 20 },
    suitability: { family: 70, toddlers: 55, children5To10: 70, teenagers: 82, seniors: 65, honeymoon: 85, solo: 75, firstInternationalTrip: 65 },
    food: { vegetarianFriendly: 72, indianFoodAvailability: 40, halalFriendly: 98, localCuisineScore: 90, streetFoodScore: 85, fineDiningScore: 80 },
    travelPracticality: { averageFlightHoursFromIndia: 10, walkingIntensity: "high", publicTransportEase: 55, roadTransferBurden: "high", accessibilityScore: 45, medicalAccessScore: 65 },
    budgetBands: ["value", "comfort", "premium", "luxury"],
    climateTags: ["mediterranean-north", "desert-south", "hot-summer-interior"],
    monthlyIntelligence: buildMonths({
      scores: [70, 75, 85, 90, 85, 70, 55, 55, 78, 88, 82, 72],
      temps: "mediterranean", tempOverrides: { 7: "hot", 8: "hot" },
      rainy: [11, 12, 1, 3], dry: [6, 7, 8],
      crowded: [4, 10, 12], quiet: [1, 7],
      highlights: { 4: ["Perfect medina-and-mountains weather; roses bloom in the valleys"], 10: ["Warm days, cool Sahara nights — ideal desert-camp season"] },
      warnings: { 7: ["Marrakech regularly exceeds 40°C"], 8: ["Interior heat peaks; coastal cities stay pleasant"] },
    }),
    commonTripCombinations: ["Marrakech + Sahara circuit", "Marrakech + Fes + Chefchaouen", "Morocco + Spain"],
    commonMistakes: ["Underestimating Marrakech–Merzouga drive times (two long days)", "Souk navigation without a landmark strategy"],
    packingConsiderations: ["Modest layered clothing", "Scarf for sun and sand", "Warm layer — desert nights get genuinely cold"],
    practicalWarnings: ["Agree taxi fares or insist on meters; haggling in souks is expected and good-natured"],
    tradeOffs: ["Long road days link the highlights", "Sensory intensity isn't for everyone"],
    whoShouldAvoid: ["Travellers who dislike haggling and busy medina energy"],
    extraSources: [TOURISM_BOARD_SOURCE("Moroccan National Tourist Office")],
    confidence: 82,
  }),

  dest({
    slug: "portugal",
    name: "Portugal",
    countryIso2: "PT",
    countryName: "Portugal",
    region: "Europe",
    summary:
      "Lisbon's tiled hills and tram bells, Porto's port cellars, golden Algarve cliffs and Europe's friendliest prices for this much charm.",
    positioningLine: "Europe's sunniest charm-per-euro champion.",
    idealTraveller: "First-time and repeat Europe travellers who want charm, coast and value together.",
    minimumNights: 5, idealNights: 7, maximumNights: 12,
    suitablePaces: ["relaxed", "balanced"],
    interests: { culture: 88, food: 88, history: 85, city: 82, beach: 78, romance: 85, relaxation: 70, nature: 65, shopping: 65, nightlife: 70, adventure: 55, wildlife: 25, themeparks: 20, snow: 0 },
    suitability: { family: 80, toddlers: 68, children5To10: 78, teenagers: 82, seniors: 78, honeymoon: 88, solo: 85, firstInternationalTrip: 75 },
    food: { vegetarianFriendly: 65, indianFoodAvailability: 60, halalFriendly: 50, localCuisineScore: 90, streetFoodScore: 70, fineDiningScore: 88 },
    travelPracticality: { averageFlightHoursFromIndia: 10.5, walkingIntensity: "high", publicTransportEase: 80, roadTransferBurden: "low", accessibilityScore: 60, medicalAccessScore: 88 },
    budgetBands: ["value", "comfort", "premium"],
    climateTags: ["mediterranean-atlantic", "mild-winter", "dry-summer"],
    monthlyIntelligence: buildMonths({
      scores: [60, 62, 72, 82, 90, 90, 82, 80, 90, 85, 68, 62],
      temps: "mediterranean",
      rainy: [11, 12, 1, 2], dry: [7, 8],
      crowded: [7, 8], quiet: [1, 2, 11],
      highlights: { 6: ["Santos Populares street festivals fill Lisbon (verify dates)"], 9: ["Warm seas, harvest season in the Douro"] },
      warnings: { 8: ["Algarve at peak crowd and price"], 1: ["Atlantic rain spells; still mild"] },
    }),
    commonTripCombinations: ["Lisbon + Porto", "Lisbon + Sintra + Algarve", "Portugal + Spain"],
    commonMistakes: ["Driving in Lisbon's old town — walk, tram and metro instead", "Skipping Sintra or cramming it into a half day"],
    packingConsiderations: ["Cobblestone-and-hill-proof shoes", "Light layers — Atlantic evenings cool fast", "Sun protection"],
    practicalWarnings: ["Lisbon's hills are steep — trams and funiculars are your friends"],
    tradeOffs: ["Long flights with connections from India", "Peak-summer Algarve is crowded"],
    whoShouldAvoid: ["Travellers wanting short-haul convenience"],
    extraSources: [TOURISM_BOARD_SOURCE("Visit Portugal")],
    confidence: 82,
  }),

  dest({
    slug: "united-kingdom",
    name: "United Kingdom",
    countryIso2: "GB",
    countryName: "United Kingdom",
    region: "Europe",
    summary:
      "London's palaces, museums and West End, plus Stonehenge, the Cotswolds and Edinburgh's castle skyline — the classic that never stops delivering.",
    positioningLine: "London and beyond — pageantry, museums and green hills.",
    idealTraveller: "First big-Europe trips, families and culture lovers with mixed interests.",
    minimumNights: 5, idealNights: 7, maximumNights: 14,
    suitablePaces: ["balanced", "active"],
    interests: { city: 92, history: 92, culture: 90, shopping: 88, food: 75, themeparks: 55, nature: 60, romance: 75, nightlife: 75, relaxation: 50, adventure: 40, wildlife: 25, beach: 15, snow: 15 },
    suitability: { family: 85, toddlers: 72, children5To10: 85, teenagers: 90, seniors: 80, honeymoon: 78, solo: 88, firstInternationalTrip: 70 },
    food: { vegetarianFriendly: 85, indianFoodAvailability: 95, halalFriendly: 85, localCuisineScore: 78, streetFoodScore: 75, fineDiningScore: 92 },
    travelPracticality: { averageFlightHoursFromIndia: 9.5, walkingIntensity: "high", publicTransportEase: 92, roadTransferBurden: "low", accessibilityScore: 80, medicalAccessScore: 92 },
    budgetBands: ["premium", "luxury"],
    climateTags: ["temperate-oceanic", "changeable", "mild"],
    monthlyIntelligence: buildMonths({
      scores: [55, 58, 65, 75, 85, 88, 85, 82, 80, 70, 58, 65],
      temps: "temperateNorth", tempOverrides: { 7: "warm", 8: "warm" },
      rainy: [1, 2, 10, 11, 12], humid: [],
      crowded: [7, 8, 12], quiet: [1, 2, 11],
      highlights: { 6: ["Long golden evenings; parks and pageantry at their best"], 12: ["Christmas lights, markets and West End season"] },
      warnings: { 1: ["Short, grey days"], 8: ["Peak crowds at headline sights; book ahead"] },
    }),
    commonTripCombinations: ["London + Windsor/Stonehenge days", "London + Edinburgh by train", "UK + Paris by Eurostar"],
    commonMistakes: ["Planning around perfect weather — carry a layer and go regardless", "Not pre-booking the Eye, Tower and shows"],
    packingConsiderations: ["Rain-ready layers in every season", "Very comfortable walking shoes", "Smart-casual for shows and dining"],
    practicalWarnings: ["Contactless cards tap straight onto all London transport"],
    tradeOffs: ["Among Europe's priciest cities", "Weather is famously unpredictable"],
    whoShouldAvoid: ["Sunshine-guarantee seekers"],
    extraSources: [TOURISM_BOARD_SOURCE("VisitBritain")],
    confidence: 84,
  }),
];
