import type { DestinationIntelligence } from "../../src/types/knowledge";
import { buildMonths, dest, TOURISM_BOARD_SOURCE } from "./builders";

export const DESTINATIONS_3: DestinationIntelligence[] = [
  dest({
    slug: "switzerland",
    name: "Switzerland",
    countryIso2: "CH",
    countryName: "Switzerland",
    region: "Europe",
    summary:
      "Snow peaks, mirror lakes, scenic trains and storybook villages. The gold standard for honeymoon-grade alpine scenery.",
    positioningLine: "The Alps at their most cinematic.",
    idealTraveller: "Honeymooners and families who want jaw-dropping scenery with flawless logistics.",
    minimumNights: 5, idealNights: 7, maximumNights: 12,
    suitablePaces: ["relaxed", "balanced", "active"],
    interests: { nature: 98, snow: 95, romance: 92, adventure: 82, relaxation: 78, city: 60, culture: 65, food: 70, history: 60, shopping: 65, wildlife: 40, nightlife: 40, beach: 5, themeparks: 30 },
    suitability: { family: 85, toddlers: 75, children5To10: 85, teenagers: 85, seniors: 82, honeymoon: 98, solo: 75, firstInternationalTrip: 78 },
    food: { vegetarianFriendly: 75, indianFoodAvailability: 70, halalFriendly: 55, localCuisineScore: 80, streetFoodScore: 45, fineDiningScore: 88 },
    travelPracticality: { averageFlightHoursFromIndia: 9, walkingIntensity: "medium", publicTransportEase: 98, roadTransferBurden: "low", accessibilityScore: 88, medicalAccessScore: 95 },
    budgetBands: ["premium", "luxury"],
    climateTags: ["alpine", "four-seasons", "cool-summer"],
    monthlyIntelligence: buildMonths({
      scores: [70, 72, 65, 70, 85, 92, 95, 92, 88, 75, 60, 72],
      temps: "alpine",
      rainy: [5, 6, 8], dry: [2],
      crowded: [7, 8, 12], quiet: [11, 3],
      highlights: { 6: ["Green alpine meadows and full waterfalls"], 12: ["Christmas markets and snow-dusted villages"] },
      warnings: { 11: ["Between-season lull — some mountain lifts closed"], 4: ["Snowmelt slush at mid-altitudes"] },
    }),
    commonTripCombinations: ["Interlaken + Lucerne + Zermatt", "Switzerland + Paris", "Glacier Express route"],
    commonMistakes: ["Changing hotels daily — base in two hubs and day-trip by train", "Skipping the Swiss Travel Pass calculation"],
    packingConsiderations: ["Layers — summits are cold even in July", "Sunglasses and sunscreen for snow glare", "Comfortable waterproof shoes"],
    practicalWarnings: ["Mountain weather changes fast — check webcams before summit tickets"],
    tradeOffs: ["Among the highest daily costs in Europe", "Schengen visa lead time needs planning"],
    whoShouldAvoid: ["Value-focused travellers — costs compound quickly"],
    extraSources: [TOURISM_BOARD_SOURCE("Switzerland Tourism")],
    confidence: 88,
  }),

  dest({
    slug: "france",
    name: "France",
    countryIso2: "FR",
    countryName: "France",
    region: "Europe",
    summary:
      "Paris icons, Loire châteaux, Riviera glamour and the world's benchmark food culture — a layered classic for romantics and culture lovers.",
    positioningLine: "Romance, art and appetite — the classic done right.",
    idealTraveller: "Romantics, art lovers and food pilgrims happy to walk beautiful cities.",
    minimumNights: 5, idealNights: 7, maximumNights: 12,
    suitablePaces: ["relaxed", "balanced"],
    interests: { culture: 95, food: 95, romance: 95, history: 92, city: 90, shopping: 92, beach: 55, nature: 60, relaxation: 60, nightlife: 75, adventure: 45, themeparks: 70, wildlife: 20, snow: 45 },
    suitability: { family: 78, toddlers: 68, children5To10: 80, teenagers: 85, seniors: 78, honeymoon: 95, solo: 85, firstInternationalTrip: 70 },
    food: { vegetarianFriendly: 60, indianFoodAvailability: 65, halalFriendly: 60, localCuisineScore: 98, streetFoodScore: 70, fineDiningScore: 99 },
    travelPracticality: { averageFlightHoursFromIndia: 9, walkingIntensity: "high", publicTransportEase: 90, roadTransferBurden: "low", accessibilityScore: 75, medicalAccessScore: 90 },
    budgetBands: ["premium", "luxury"],
    climateTags: ["temperate", "four-seasons", "mediterranean-south"],
    monthlyIntelligence: buildMonths({
      scores: [55, 58, 68, 80, 88, 90, 85, 80, 90, 82, 62, 60],
      temps: "temperateNorth",
      rainy: [1, 2, 11, 12], dry: [7],
      crowded: [7, 8], quiet: [1, 11],
      highlights: { 5: ["Long spring evenings; gardens in bloom"], 9: ["Golden light, grape harvest and fewer queues"] },
      warnings: { 8: ["Parisian August closures; Riviera at peak crowd"], 1: ["Short, grey days in the north"] },
    }),
    commonTripCombinations: ["Paris + Riviera", "Paris + Switzerland", "Paris + Disneyland day"],
    commonMistakes: ["Queueing for headline sights without pre-booked slots", "Cramming Versailles and the Louvre into one day"],
    packingConsiderations: ["Smart-casual layers — Parisians dress up", "Very comfortable walking shoes", "Compact umbrella"],
    practicalWarnings: ["Pickpockets work major sights and metro lines — keep bags zipped"],
    tradeOffs: ["Peak-season queues at headline sights", "Higher budget; Schengen visa lead time"],
    whoShouldAvoid: ["Travellers who dislike walking-heavy city days"],
    extraSources: [TOURISM_BOARD_SOURCE("Atout France")],
    confidence: 87,
  }),

  dest({
    slug: "italy",
    name: "Italy",
    countryIso2: "IT",
    countryName: "Italy",
    region: "Europe",
    summary:
      "Rome's ruins, Florence's art, Venice's canals and the Amalfi Coast — history, food and romance stacked deeper than anywhere else.",
    positioningLine: "The grand tour: art, coastlines and unforgettable food.",
    idealTraveller: "Travellers who measure a trip in meals, masterpieces and golden-hour piazzas.",
    minimumNights: 6, idealNights: 8, maximumNights: 14,
    suitablePaces: ["balanced", "active"],
    interests: { history: 98, culture: 96, food: 96, romance: 92, city: 88, beach: 60, shopping: 85, nature: 60, relaxation: 55, nightlife: 65, adventure: 45, wildlife: 15, themeparks: 30, snow: 40 },
    suitability: { family: 76, toddlers: 62, children5To10: 75, teenagers: 85, seniors: 72, honeymoon: 95, solo: 82, firstInternationalTrip: 68 },
    food: { vegetarianFriendly: 80, indianFoodAvailability: 55, halalFriendly: 55, localCuisineScore: 99, streetFoodScore: 85, fineDiningScore: 95 },
    travelPracticality: { averageFlightHoursFromIndia: 8.5, walkingIntensity: "high", publicTransportEase: 80, roadTransferBurden: "medium", accessibilityScore: 60, medicalAccessScore: 88 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["mediterranean", "four-seasons", "hot-summer"],
    monthlyIntelligence: buildMonths({
      scores: [55, 58, 70, 82, 90, 88, 78, 75, 90, 85, 65, 60],
      temps: "mediterranean",
      rainy: [11, 12, 2], dry: [7, 8], humid: [7, 8],
      crowded: [6, 7, 8], quiet: [1, 2, 11],
      highlights: { 5: ["Warm days before the summer surge"], 9: ["Sea still warm; cities exhale after August"] },
      warnings: { 8: ["Ferragosto crowds on every coast"], 7: ["City heat makes midday sightseeing tough"] },
    }),
    commonTripCombinations: ["Rome + Florence + Venice", "Rome + Amalfi Coast", "Italy + Switzerland"],
    commonMistakes: ["Moving cities every night", "Arriving without timed tickets for the Vatican or Uffizi"],
    packingConsiderations: ["Modest wear for churches (shoulders covered)", "Cobblestone-proof shoes", "Light layers"],
    practicalWarnings: ["Headline sights need pre-booking days or weeks ahead"],
    tradeOffs: ["Multi-city routing means packing and moving every few days", "Headline sights need pre-booking"],
    whoShouldAvoid: ["Travellers wanting one base and minimal walking"],
    extraSources: [TOURISM_BOARD_SOURCE("ENIT — Italian National Tourist Board")],
    confidence: 87,
  }),

  dest({
    slug: "greece",
    name: "Greece",
    countryIso2: "GR",
    countryName: "Greece",
    region: "Europe",
    summary:
      "Athens' Acropolis then whitewashed Cyclades — Santorini sunsets, Mykonos beaches and slow island evenings. A honeymoon staple.",
    positioningLine: "Blue-and-white island romance with ancient roots.",
    idealTraveller: "Honeymooners and sunset-chasers comfortable with steps, ferries and island time.",
    minimumNights: 5, idealNights: 7, maximumNights: 12,
    suitablePaces: ["relaxed", "balanced"],
    interests: { beach: 88, romance: 95, history: 90, relaxation: 85, food: 85, culture: 85, nightlife: 75, city: 60, nature: 60, shopping: 60, adventure: 50, wildlife: 15, themeparks: 10, snow: 15 },
    suitability: { family: 72, toddlers: 60, children5To10: 72, teenagers: 80, seniors: 70, honeymoon: 97, solo: 78, firstInternationalTrip: 72 },
    food: { vegetarianFriendly: 80, indianFoodAvailability: 45, halalFriendly: 50, localCuisineScore: 92, streetFoodScore: 80, fineDiningScore: 85 },
    travelPracticality: { averageFlightHoursFromIndia: 8, walkingIntensity: "high", publicTransportEase: 65, roadTransferBurden: "medium", accessibilityScore: 50, medicalAccessScore: 78 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["mediterranean", "dry-summer", "island-winds"],
    monthlyIntelligence: buildMonths({
      scores: [45, 48, 58, 75, 88, 92, 85, 82, 92, 82, 58, 48],
      temps: "mediterranean",
      rainy: [1, 2, 12, 11], dry: [6, 7, 8],
      crowded: [7, 8], quiet: [1, 2, 3],
      highlights: { 6: ["Warm seas before peak crowds"], 9: ["Best month: warm water, soft light, fewer ferries missed"] },
      warnings: { 8: ["Meltemi winds and peak pricing in the Cyclades"], 12: ["Many island hotels close for winter"] },
    }),
    commonTripCombinations: ["Athens + Santorini + Mykonos", "Athens + Naxos + Paros", "Greece + Turkey"],
    commonMistakes: ["Booking tight ferry connections", "Only visiting Santorini — quieter islands are the magic"],
    packingConsiderations: ["Deck-friendly shoes for ferries", "Sun hat — shade is scarce at ruins", "Light layers for evening island winds"],
    practicalWarnings: ["Caldera towns mean steps everywhere — pack light"],
    tradeOffs: ["Ferry schedules shape the itinerary", "Santorini premiums in July–August are steep"],
    whoShouldAvoid: ["Travellers uncomfortable with steps and cliffside paths"],
    extraSources: [TOURISM_BOARD_SOURCE("Visit Greece")],
    confidence: 85,
  }),

  dest({
    slug: "spain",
    name: "Spain",
    countryIso2: "ES",
    countryName: "Spain",
    region: "Europe",
    summary:
      "Gaudí's Barcelona, royal Madrid, Moorish Andalusia and late-night tapas culture — Europe's most energetic classic.",
    positioningLine: "Art, tapas and fiesta energy from Barcelona to Seville.",
    idealTraveller: "Culture-and-food travellers who love cities that stay up late.",
    minimumNights: 5, idealNights: 7, maximumNights: 12,
    suitablePaces: ["balanced", "active"],
    interests: { culture: 92, food: 90, city: 90, history: 88, nightlife: 85, beach: 70, shopping: 80, romance: 82, relaxation: 60, nature: 55, adventure: 50, themeparks: 55, wildlife: 20, snow: 25 },
    suitability: { family: 78, toddlers: 65, children5To10: 78, teenagers: 85, seniors: 75, honeymoon: 85, solo: 85, firstInternationalTrip: 72 },
    food: { vegetarianFriendly: 65, indianFoodAvailability: 55, halalFriendly: 55, localCuisineScore: 95, streetFoodScore: 80, fineDiningScore: 92 },
    travelPracticality: { averageFlightHoursFromIndia: 9.5, walkingIntensity: "high", publicTransportEase: 88, roadTransferBurden: "low", accessibilityScore: 72, medicalAccessScore: 88 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["mediterranean", "hot-summer", "mild-winter-south"],
    monthlyIntelligence: buildMonths({
      scores: [58, 60, 70, 82, 90, 85, 72, 70, 88, 85, 68, 60],
      temps: "mediterranean",
      rainy: [11, 12, 1, 4], dry: [7, 8],
      crowded: [7, 8], quiet: [1, 2],
      highlights: { 5: ["Perfect city-walking weather everywhere"], 9: ["Warm seas, harvest menus, fewer crowds"] },
      warnings: { 8: ["Andalusia regularly exceeds 40°C"], 7: ["Interior heat — plan siesta-style days"] },
    }),
    commonTripCombinations: ["Barcelona + Madrid", "Madrid + Seville + Granada", "Spain + Portugal"],
    commonMistakes: ["Expecting dinner before 8:30pm", "Skipping Alhambra pre-booking — it sells out weeks ahead"],
    packingConsiderations: ["Light clothing plus a smart layer for evenings", "Walking shoes for old-town cobbles", "Sun protection for Andalusia"],
    practicalWarnings: ["Alhambra and Sagrada Família require timed tickets booked well ahead"],
    tradeOffs: ["Peak-summer heat in the south is intense", "Late dining rhythm takes adjustment"],
    whoShouldAvoid: ["Early-to-bed travellers who dislike late, lively evenings"],
    extraSources: [TOURISM_BOARD_SOURCE("Turespaña")],
    confidence: 84,
  }),

  dest({
    slug: "austria",
    name: "Austria",
    countryIso2: "AT",
    countryName: "Austria",
    region: "Europe",
    summary:
      "Vienna's imperial palaces and coffee houses, Salzburg's Sound-of-Music lanes and Hallstatt's lakeside postcard — elegant Alps without the rush.",
    positioningLine: "Imperial elegance and storybook alpine villages.",
    idealTraveller: "Couples and families who want European elegance at a gentler pace than the big-three capitals.",
    minimumNights: 5, idealNights: 6, maximumNights: 10,
    suitablePaces: ["relaxed", "balanced"],
    interests: { culture: 90, history: 88, nature: 85, romance: 85, city: 80, food: 75, snow: 70, relaxation: 70, shopping: 65, adventure: 55, nightlife: 50, themeparks: 30, wildlife: 25, beach: 5 },
    suitability: { family: 82, toddlers: 72, children5To10: 82, teenagers: 80, seniors: 85, honeymoon: 88, solo: 78, firstInternationalTrip: 75 },
    food: { vegetarianFriendly: 70, indianFoodAvailability: 60, halalFriendly: 55, localCuisineScore: 85, streetFoodScore: 60, fineDiningScore: 88 },
    travelPracticality: { averageFlightHoursFromIndia: 8.5, walkingIntensity: "medium", publicTransportEase: 92, roadTransferBurden: "low", accessibilityScore: 82, medicalAccessScore: 92 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["alpine", "four-seasons", "snowy-winter"],
    monthlyIntelligence: buildMonths({
      scores: [65, 65, 62, 72, 85, 90, 88, 85, 88, 78, 60, 75],
      temps: "temperateNorth",
      rainy: [5, 6, 7, 8], dry: [1, 2],
      crowded: [7, 8, 12], quiet: [3, 11],
      highlights: { 12: ["Vienna's Christmas markets — Europe's loveliest"], 6: ["Alpine lakes at their most swimmable"] },
      warnings: { 11: ["Grey between-season weeks"], 8: ["Salzburg festival crowds and prices"] },
    }),
    commonTripCombinations: ["Vienna + Salzburg + Hallstatt", "Austria + Switzerland", "Vienna + Prague + Budapest"],
    commonMistakes: ["Day-tripping Hallstatt at midday with the crowds — stay overnight or go early"],
    packingConsiderations: ["Smart-casual layers for concerts and coffee houses", "Warm coat Nov–Mar", "Comfortable walking shoes"],
    practicalWarnings: ["Sunday closures affect shops — plan grocery and shopping days"],
    tradeOffs: ["Quieter evenings than Europe's party capitals", "Peak Christmas-market season books out early"],
    whoShouldAvoid: ["Travellers chasing beach warmth or big nightlife"],
    extraSources: [TOURISM_BOARD_SOURCE("Austrian National Tourist Office")],
    confidence: 82,
  }),

  dest({
    slug: "czech-republic",
    name: "Czech Republic",
    countryIso2: "CZ",
    countryName: "Czech Republic",
    region: "Europe",
    summary:
      "Prague's fairy-tale skyline of spires and bridges, castle towns like Český Krumlov and Europe's best-value old-world charm.",
    positioningLine: "Fairy-tale Europe at the continent's best prices.",
    idealTraveller: "First-time Europe visitors and couples who want maximum old-world atmosphere per euro.",
    minimumNights: 4, idealNights: 5, maximumNights: 8,
    suitablePaces: ["relaxed", "balanced"],
    interests: { history: 92, culture: 88, city: 85, romance: 85, food: 70, nightlife: 70, shopping: 60, nature: 55, relaxation: 60, adventure: 40, snow: 40, themeparks: 20, wildlife: 15, beach: 0 },
    suitability: { family: 75, toddlers: 62, children5To10: 75, teenagers: 80, seniors: 78, honeymoon: 85, solo: 85, firstInternationalTrip: 78 },
    food: { vegetarianFriendly: 60, indianFoodAvailability: 55, halalFriendly: 45, localCuisineScore: 78, streetFoodScore: 70, fineDiningScore: 78 },
    travelPracticality: { averageFlightHoursFromIndia: 8.5, walkingIntensity: "high", publicTransportEase: 90, roadTransferBurden: "low", accessibilityScore: 65, medicalAccessScore: 85 },
    budgetBands: ["value", "comfort", "premium"],
    climateTags: ["continental", "four-seasons", "cold-winter"],
    monthlyIntelligence: buildMonths({
      scores: [60, 60, 65, 78, 88, 88, 82, 80, 88, 80, 60, 72],
      temps: "temperateNorth",
      rainy: [5, 6, 7, 8], dry: [1, 2],
      crowded: [7, 8, 12], quiet: [1, 2, 11],
      highlights: { 5: ["Blossoming parks and long golden evenings"], 12: ["Old Town Square Christmas market"] },
      warnings: { 7: ["Charles Bridge is shoulder-to-shoulder by 10am — go at dawn"], 1: ["Cold, grey and short days"] },
    }),
    commonTripCombinations: ["Prague + Vienna + Budapest", "Prague + Český Krumlov", "Prague + Karlovy Vary"],
    commonMistakes: ["Exchanging money on the street or at tourist-trap kiosks", "Only seeing Prague — Krumlov is two hours away"],
    packingConsiderations: ["Cobblestone-proof shoes — Prague is all stone", "Warm layers Oct–Apr", "Compact umbrella"],
    practicalWarnings: ["Use bank ATMs, never street exchange booths"],
    tradeOffs: ["Peak-season crowds swamp the old town core", "Winter days are short and cold"],
    whoShouldAvoid: ["Travellers seeking warm weather or beach time"],
    extraSources: [TOURISM_BOARD_SOURCE("CzechTourism")],
    confidence: 82,
  }),

  dest({
    slug: "australia",
    name: "Australia",
    countryIso2: "AU",
    countryName: "Australia",
    region: "Oceania",
    summary:
      "Sydney's harbour, the Great Barrier Reef and wildlife found nowhere else. A big-trip destination that rewards ten days or more.",
    positioningLine: "Bucket-list nature and easy-going city life.",
    idealTraveller: "Big-trip planners with 10+ nights who want reef, wildlife and city life in one journey.",
    minimumNights: 8, idealNights: 10, maximumNights: 16,
    suitablePaces: ["balanced", "active"],
    interests: { nature: 95, wildlife: 95, beach: 88, adventure: 88, city: 82, food: 80, relaxation: 60, romance: 75, culture: 65, nightlife: 70, shopping: 70, history: 45, themeparks: 65, snow: 25 },
    suitability: { family: 82, toddlers: 68, children5To10: 82, teenagers: 88, seniors: 72, honeymoon: 85, solo: 85, firstInternationalTrip: 60 },
    food: { vegetarianFriendly: 80, indianFoodAvailability: 78, halalFriendly: 65, localCuisineScore: 85, streetFoodScore: 65, fineDiningScore: 90 },
    travelPracticality: { averageFlightHoursFromIndia: 12, walkingIntensity: "medium", publicTransportEase: 80, roadTransferBurden: "medium", accessibilityScore: 85, medicalAccessScore: 95 },
    budgetBands: ["premium", "luxury"],
    climateTags: ["southern-hemisphere", "regional-contrast", "tropical-north"],
    monthlyIntelligence: buildMonths({
      scores: [80, 78, 82, 85, 78, 70, 68, 72, 85, 90, 88, 82],
      temps: "temperateSouth",
      veryRainy: [2], rainy: [1, 3, 11], humid: [1, 2, 12],
      crowded: [12, 1], quiet: [5, 6],
      highlights: { 10: ["Spring: whales, wildflowers and mild city days"], 4: ["Autumn calm — reef visibility excellent"] },
      warnings: { 1: ["Tropical north wet season and stingers"], 2: ["Cyclone season in Queensland's north"] },
    }),
    commonTripCombinations: ["Sydney + Cairns/Reef + Melbourne", "Australia + New Zealand", "Sydney + Gold Coast"],
    commonMistakes: ["Underestimating internal distances — Sydney–Cairns is a 3-hour flight", "Trying to see three coasts in ten days"],
    packingConsiderations: ["Layers — southern cities can be four seasons in a day", "Reef-safe sunscreen and stinger-suit hire in season", "High-SPF protection — the sun is fierce"],
    practicalWarnings: ["Swim between the flags at patrolled beaches only"],
    tradeOffs: ["Long-haul flights and internal distances", "Higher budget; visa lead time required"],
    whoShouldAvoid: ["Travellers with under a week to spare"],
    extraSources: [TOURISM_BOARD_SOURCE("Tourism Australia")],
    confidence: 85,
  }),

  dest({
    slug: "new-zealand",
    name: "New Zealand",
    countryIso2: "NZ",
    countryName: "New Zealand",
    region: "Oceania",
    summary:
      "Fiordland's misty peaks, Queenstown's adrenaline, glow-worm caves and Hobbiton — the world's most cinematic road-trip country.",
    positioningLine: "Middle-earth landscapes and the world's adventure capital.",
    idealTraveller: "Nature-obsessed couples and adventure seekers comfortable with self-drive touring.",
    minimumNights: 8, idealNights: 10, maximumNights: 16,
    suitablePaces: ["balanced", "active"],
    interests: { nature: 98, adventure: 95, romance: 85, wildlife: 75, relaxation: 65, snow: 60, food: 70, culture: 60, city: 55, beach: 50, history: 40, shopping: 45, nightlife: 45, themeparks: 20 },
    suitability: { family: 78, toddlers: 60, children5To10: 78, teenagers: 88, seniors: 70, honeymoon: 92, solo: 85, firstInternationalTrip: 60 },
    food: { vegetarianFriendly: 78, indianFoodAvailability: 72, halalFriendly: 60, localCuisineScore: 82, streetFoodScore: 55, fineDiningScore: 85 },
    travelPracticality: { averageFlightHoursFromIndia: 15, walkingIntensity: "medium", publicTransportEase: 55, roadTransferBurden: "high", accessibilityScore: 78, medicalAccessScore: 90 },
    budgetBands: ["premium", "luxury"],
    climateTags: ["southern-hemisphere", "temperate-oceanic", "changeable"],
    monthlyIntelligence: buildMonths({
      scores: [88, 88, 85, 78, 65, 60, 58, 62, 70, 78, 82, 88],
      temps: "temperateSouth",
      rainy: [6, 7, 8, 9], dry: [1, 2],
      crowded: [12, 1], quiet: [5, 6],
      highlights: { 2: ["Settled summer — best hiking and fiord cruising"], 11: ["Lupins bloom around Lake Tekapo"] },
      warnings: { 6: ["Alpine passes may need snow chains"], 7: ["Short days limit road-trip hours"] },
    }),
    commonTripCombinations: ["South Island loop (Christchurch–Queenstown)", "Auckland + Rotorua + Queenstown", "Australia + New Zealand"],
    commonMistakes: ["Planning Australia-style distances — NZ roads are slow and winding", "Booking Milford Sound with no weather buffer"],
    packingConsiderations: ["Waterproof layers in every season", "Sturdy walking shoes", "Sunscreen — UV is extreme even when cool"],
    practicalWarnings: ["Weather changes hourly in the fiords — build flex days"],
    tradeOffs: ["Very long flights from India", "Self-driving is near-essential outside cities"],
    whoShouldAvoid: ["Travellers who won't drive and dislike changeable weather"],
    extraSources: [TOURISM_BOARD_SOURCE("Tourism New Zealand")],
    confidence: 82,
  }),

  dest({
    slug: "south-africa",
    name: "South Africa",
    countryIso2: "ZA",
    countryName: "South Africa",
    region: "Africa",
    summary:
      "Big Five safaris in Kruger, Cape Town's Table Mountain and winelands, whales and penguins on the Garden Route — Africa's greatest variety show.",
    positioningLine: "Safari mornings, wineland afternoons, ocean sunsets.",
    idealTraveller: "Wildlife dreamers and scenery lovers who want safari plus city in one trip.",
    minimumNights: 7, idealNights: 9, maximumNights: 14,
    suitablePaces: ["balanced", "active"],
    interests: { wildlife: 98, nature: 95, adventure: 85, food: 80, romance: 80, beach: 65, culture: 70, city: 70, relaxation: 60, history: 65, shopping: 55, nightlife: 60, themeparks: 15, snow: 5 },
    suitability: { family: 80, toddlers: 60, children5To10: 82, teenagers: 88, seniors: 72, honeymoon: 90, solo: 70, firstInternationalTrip: 60 },
    food: { vegetarianFriendly: 70, indianFoodAvailability: 78, halalFriendly: 70, localCuisineScore: 85, streetFoodScore: 65, fineDiningScore: 90 },
    travelPracticality: { averageFlightHoursFromIndia: 11, walkingIntensity: "medium", publicTransportEase: 40, roadTransferBurden: "high", accessibilityScore: 60, medicalAccessScore: 75 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["southern-hemisphere", "dry-winter-safari", "mediterranean-cape"],
    monthlyIntelligence: buildMonths({
      scores: [78, 78, 80, 78, 75, 78, 80, 82, 85, 85, 82, 80],
      temps: "temperateSouth",
      rainy: [11, 12, 1, 2], dry: [6, 7, 8],
      crowded: [12, 1], quiet: [5, 6],
      highlights: { 8: ["Peak dry-season game viewing in Kruger; whales arrive at Hermanus"], 2: ["Cape Town's driest, warmest beach weather"] },
      warnings: { 1: ["Kruger is hot and green — animals harder to spot"], 6: ["Cape Town's rainy season"] },
    }),
    commonTripCombinations: ["Cape Town + Garden Route + Kruger", "South Africa + Victoria Falls", "Cape Town + Winelands"],
    commonMistakes: ["Expecting one season countrywide — Cape Town and Kruger are opposites", "Self-driving safari with no early-morning starts"],
    packingConsiderations: ["Neutral-coloured layers for safari; mornings are cold", "Binoculars", "Sun protection year-round"],
    practicalWarnings: ["Take local safety advice seriously in cities — use recommended transport at night"],
    tradeOffs: ["Cape Town and Kruger have opposite best seasons", "Urban safety requires sensible precautions"],
    whoShouldAvoid: ["Travellers wanting carefree late-night city wandering"],
    extraSources: [TOURISM_BOARD_SOURCE("South African Tourism")],
    confidence: 82,
  }),
];
