import type { DestinationIntelligence } from "../../src/types/knowledge";
import { buildMonths, dest, TOURISM_BOARD_SOURCE } from "./builders";

export const DESTINATIONS_1: DestinationIntelligence[] = [
  dest({
    slug: "singapore",
    name: "Singapore",
    countryIso2: "SG",
    countryName: "Singapore",
    region: "Southeast Asia",
    summary:
      "A compact, spotless city-state that mixes gardens, theme parks, hawker food and skyline views. One of the easiest first international trips from India.",
    positioningLine: "Effortless city break with world-class family attractions.",
    idealTraveller: "Families with children, first international trips, and anyone who wants maximum wow with minimum friction.",
    minimumNights: 3, idealNights: 5, maximumNights: 7,
    suitablePaces: ["relaxed", "balanced", "active"],
    interests: { city: 95, food: 90, themeparks: 92, shopping: 88, culture: 70, nature: 60, beach: 40, nightlife: 75, relaxation: 55, romance: 65, history: 55, adventure: 55, wildlife: 65, snow: 0 },
    suitability: { family: 95, toddlers: 90, children5To10: 95, teenagers: 88, seniors: 90, honeymoon: 60, solo: 80, firstInternationalTrip: 95 },
    food: { vegetarianFriendly: 90, indianFoodAvailability: 95, halalFriendly: 90, localCuisineScore: 92, streetFoodScore: 95, fineDiningScore: 90 },
    travelPracticality: { averageFlightHoursFromIndia: 4.5, walkingIntensity: "medium", publicTransportEase: 95, roadTransferBurden: "low", accessibilityScore: 92, medicalAccessScore: 95 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["tropical", "humid", "warm-all-year"],
    monthlyIntelligence: buildMonths({
      scores: [78, 80, 80, 75, 72, 72, 74, 74, 72, 70, 65, 70],
      temps: "tropical",
      veryRainy: [11, 12], rainy: [1, 4, 10], humid: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      crowded: [6, 12], quiet: [3, 9],
      highlights: { 12: ["Year-end light-ups along Orchard Road"], 6: ["Great Singapore Sale shopping season"] },
      warnings: { 11: ["North-east monsoon showers — keep afternoons flexible"], 12: ["Peak holiday crowds at major attractions"] },
    }),
    commonTripCombinations: ["Singapore + Bali", "Singapore + Kuala Lumpur", "Singapore + cruise"],
    commonMistakes: ["Packing too many attractions into one day in the humidity", "Skipping hawker centres for hotel dining"],
    packingConsiderations: ["Light breathable clothing", "Umbrella or light rain jacket year-round", "Comfortable walking shoes"],
    practicalWarnings: ["Strict fines for littering and eating on public transport"],
    tradeOffs: ["Compact itinerary options — fewer 'new' sights beyond five nights", "Higher daily costs than most of Southeast Asia"],
    whoShouldAvoid: ["Travellers wanting raw nature or long beach stays as the main event"],
    extraSources: [TOURISM_BOARD_SOURCE("Singapore Tourism Board")],
    confidence: 88,
  }),

  dest({
    slug: "dubai",
    name: "Dubai",
    countryIso2: "AE",
    countryName: "United Arab Emirates",
    region: "Middle East",
    summary:
      "Desert glamour, record-breaking architecture, malls, theme parks and beach resorts — a short flight from India with excellent Indian food availability.",
    positioningLine: "Big-ticket wow factor within a short flight.",
    idealTraveller: "Families and groups who want spectacle, shopping and easy logistics close to home.",
    minimumNights: 4, idealNights: 5, maximumNights: 8,
    suitablePaces: ["relaxed", "balanced", "active"],
    interests: { city: 92, shopping: 95, themeparks: 88, beach: 70, food: 80, adventure: 78, nightlife: 80, relaxation: 65, culture: 60, romance: 70, history: 50, nature: 45, wildlife: 30, snow: 20 },
    suitability: { family: 90, toddlers: 85, children5To10: 92, teenagers: 90, seniors: 85, honeymoon: 75, solo: 75, firstInternationalTrip: 92 },
    food: { vegetarianFriendly: 85, indianFoodAvailability: 95, halalFriendly: 98, localCuisineScore: 78, streetFoodScore: 70, fineDiningScore: 92 },
    travelPracticality: { averageFlightHoursFromIndia: 3.5, walkingIntensity: "low", publicTransportEase: 85, roadTransferBurden: "low", accessibilityScore: 90, medicalAccessScore: 92 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["desert", "dry-winter", "extreme-summer"],
    monthlyIntelligence: buildMonths({
      scores: [88, 88, 82, 72, 55, 40, 35, 35, 50, 70, 85, 90],
      temps: "desert",
      humid: [6, 7, 8, 9], dry: [11, 12, 1, 2, 3],
      crowded: [12, 1], quiet: [6, 7, 8],
      highlights: { 1: ["Dubai Shopping Festival"], 12: ["Pleasant outdoor weather for desert safaris"] },
      warnings: { 6: ["Extreme heat — outdoor plans limited to mornings and evenings"], 7: ["Extreme heat — indoor-focused itinerary recommended"], 8: ["Extreme heat — indoor-focused itinerary recommended"] },
    }),
    commonTripCombinations: ["Dubai + Abu Dhabi", "Dubai + Maldives", "Dubai stopover en route to Europe"],
    commonMistakes: ["Visiting in peak summer expecting outdoor sightseeing", "Underestimating time needed at mega-malls and parks"],
    packingConsiderations: ["Light layers plus a warm layer for icy indoor air-conditioning", "Modest wear for mosques and heritage areas", "Sun protection"],
    practicalWarnings: ["Respect local norms in public spaces; check Ramadan timings if applicable"],
    tradeOffs: ["Summer months are extremely hot outdoors", "Feels commercial rather than cultural for some travellers"],
    whoShouldAvoid: ["Travellers seeking historic old-world charm or lush landscapes"],
    extraSources: [TOURISM_BOARD_SOURCE("Dubai Department of Economy and Tourism")],
    confidence: 88,
  }),

  dest({
    slug: "abu-dhabi",
    name: "Abu Dhabi",
    countryIso2: "AE",
    countryName: "United Arab Emirates",
    region: "Middle East",
    summary:
      "The UAE's calmer capital: the Sheikh Zayed Grand Mosque, Louvre Abu Dhabi, Ferrari World and family beaches — grand, gracious and easy to pair with Dubai.",
    positioningLine: "Grand culture and family thrills at a gentler pace than Dubai.",
    idealTraveller: "Families and culture-curious travellers who want UAE spectacle with more breathing room.",
    minimumNights: 3, idealNights: 4, maximumNights: 6,
    suitablePaces: ["relaxed", "balanced"],
    interests: { city: 85, culture: 78, themeparks: 90, shopping: 75, beach: 72, food: 75, adventure: 65, relaxation: 72, romance: 68, history: 55, nightlife: 55, nature: 45, wildlife: 35, snow: 0 },
    suitability: { family: 92, toddlers: 85, children5To10: 92, teenagers: 90, seniors: 88, honeymoon: 70, solo: 70, firstInternationalTrip: 90 },
    food: { vegetarianFriendly: 82, indianFoodAvailability: 92, halalFriendly: 98, localCuisineScore: 76, streetFoodScore: 60, fineDiningScore: 88 },
    travelPracticality: { averageFlightHoursFromIndia: 3.5, walkingIntensity: "low", publicTransportEase: 65, roadTransferBurden: "low", accessibilityScore: 90, medicalAccessScore: 92 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["desert", "dry-winter", "extreme-summer"],
    monthlyIntelligence: buildMonths({
      scores: [88, 88, 82, 70, 52, 38, 34, 34, 48, 70, 85, 90],
      temps: "desert",
      humid: [6, 7, 8, 9], dry: [11, 12, 1, 2, 3],
      crowded: [12, 1], quiet: [6, 7, 8],
      highlights: { 12: ["Perfect Corniche weather"], 11: ["F1 Abu Dhabi Grand Prix energy on Yas Island"] },
      warnings: { 7: ["Extreme heat — plan indoor attractions"], 8: ["Extreme heat — plan indoor attractions"] },
    }),
    commonTripCombinations: ["Abu Dhabi + Dubai", "Abu Dhabi + Maldives"],
    commonMistakes: ["Treating it as a half-day trip from Dubai — Yas Island alone needs a full day"],
    packingConsiderations: ["Modest clothing for the Grand Mosque (coverings provided)", "Sun protection", "Light layers for air-conditioning"],
    practicalWarnings: ["Grand Mosque dress code is strictly enforced"],
    tradeOffs: ["Quieter nightlife and street energy than Dubai", "Attractions are spread out — taxis or transfers needed"],
    whoShouldAvoid: ["Travellers wanting walkable old-town streets and bustle"],
    extraSources: [TOURISM_BOARD_SOURCE("Experience Abu Dhabi")],
    confidence: 82,
  }),

  dest({
    slug: "bali",
    name: "Bali",
    countryIso2: "ID",
    countryName: "Indonesia",
    region: "Southeast Asia",
    summary:
      "Temples, rice terraces, surf beaches and wellness retreats. Equally suited to honeymoons, friends' trips and slow family holidays.",
    positioningLine: "Tropical island escape with soul and style.",
    idealTraveller: "Honeymooners, wellness seekers and easy-going groups who value atmosphere over efficiency.",
    minimumNights: 4, idealNights: 6, maximumNights: 10,
    suitablePaces: ["relaxed", "balanced"],
    interests: { beach: 92, relaxation: 95, romance: 92, nature: 88, culture: 85, adventure: 78, food: 80, nightlife: 70, city: 40, shopping: 60, history: 65, themeparks: 35, wildlife: 60, snow: 0 },
    suitability: { family: 75, toddlers: 60, children5To10: 72, teenagers: 78, seniors: 65, honeymoon: 95, solo: 85, firstInternationalTrip: 80 },
    food: { vegetarianFriendly: 85, indianFoodAvailability: 60, halalFriendly: 60, localCuisineScore: 85, streetFoodScore: 80, fineDiningScore: 82 },
    travelPracticality: { averageFlightHoursFromIndia: 8, walkingIntensity: "medium", publicTransportEase: 40, roadTransferBurden: "high", accessibilityScore: 55, medicalAccessScore: 65 },
    budgetBands: ["value", "comfort", "premium", "luxury"],
    climateTags: ["tropical", "humid", "dry-season-jun-sep"],
    monthlyIntelligence: buildMonths({
      scores: [55, 58, 65, 75, 85, 90, 90, 90, 88, 80, 65, 55],
      temps: "tropical",
      veryRainy: [1, 2, 12], rainy: [3, 11], humid: [1, 2, 3, 4, 10, 11, 12],
      crowded: [7, 8, 12], quiet: [2, 3],
      highlights: { 6: ["Dry-season perfection for beaches and waterfalls"], 4: ["Green landscapes right after the rains"] },
      warnings: { 1: ["Wet season — expect daily downpours"], 12: ["Wet season and holiday crowds around Christmas"] },
    }),
    commonTripCombinations: ["Bali + Nusa Penida", "Bali + Gili Islands", "Singapore + Bali"],
    commonMistakes: ["Basing in one area and commuting daily across the island through traffic", "Underestimating transfer times between south-coast beaches and Ubud"],
    packingConsiderations: ["Sarong or cover-up for temples", "Reef-safe sunscreen", "Light rain layer outside dry season"],
    practicalWarnings: ["Traffic between areas can eat hours — plan by zone, not by distance"],
    tradeOffs: ["Traffic between areas can eat into short trips", "Monsoon months (Dec–Feb) bring daily rain"],
    whoShouldAvoid: ["Travellers who want efficient public transport and city polish"],
    extraSources: [TOURISM_BOARD_SOURCE("Wonderful Indonesia")],
    confidence: 85,
  }),

  dest({
    slug: "bangkok",
    name: "Bangkok",
    countryIso2: "TH",
    countryName: "Thailand",
    region: "Southeast Asia",
    summary:
      "Golden temples beside mega-malls, the best street food in Asia and a river that ties it all together. The classic big-energy city break from India.",
    positioningLine: "Street food, temples and city buzz — superb value.",
    idealTraveller: "Food lovers, shoppers and first-timers who want maximum energy per rupee.",
    minimumNights: 3, idealNights: 4, maximumNights: 6,
    suitablePaces: ["balanced", "active"],
    interests: { food: 95, city: 90, shopping: 90, nightlife: 88, culture: 80, history: 65, themeparks: 60, relaxation: 50, romance: 65, beach: 20, nature: 40, adventure: 55, wildlife: 40, snow: 0 },
    suitability: { family: 78, toddlers: 65, children5To10: 78, teenagers: 85, seniors: 70, honeymoon: 70, solo: 90, firstInternationalTrip: 90 },
    food: { vegetarianFriendly: 75, indianFoodAvailability: 80, halalFriendly: 70, localCuisineScore: 96, streetFoodScore: 98, fineDiningScore: 85 },
    travelPracticality: { averageFlightHoursFromIndia: 4.5, walkingIntensity: "medium", publicTransportEase: 80, roadTransferBurden: "medium", accessibilityScore: 60, medicalAccessScore: 85 },
    budgetBands: ["value", "comfort", "premium", "luxury"],
    climateTags: ["tropical", "humid", "hot-all-year"],
    monthlyIntelligence: buildMonths({
      scores: [90, 88, 78, 68, 60, 58, 58, 58, 52, 62, 82, 90],
      temps: "equatorialHot", tempOverrides: { 12: "warm", 1: "warm" },
      veryRainy: [9, 10], rainy: [5, 6, 7, 8], humid: [3, 4, 5, 6, 7, 8, 9, 10],
      crowded: [12, 1], quiet: [9],
      highlights: { 11: ["Loy Krathong lantern festival on the river"], 12: ["Coolest, driest sightseeing weather"] },
      warnings: { 4: ["Hottest month; Songkran water festival crowds"], 9: ["Peak monsoon — plan indoor fallbacks"] },
    }),
    commonTripCombinations: ["Bangkok + Phuket", "Bangkok + Krabi", "Bangkok + Pattaya"],
    commonMistakes: ["Trying to see temples at midday heat", "Booking a hotel far from BTS/MRT lines"],
    packingConsiderations: ["Breathable clothing", "Modest wear for temples (shoulders and knees covered)", "Comfortable sandals"],
    practicalWarnings: ["Agree taxi meters or use ride-hailing; tuk-tuk prices are negotiable"],
    tradeOffs: ["Hot and humid nearly all year", "Traffic can be intense outside train corridors"],
    whoShouldAvoid: ["Travellers wanting quiet, slow-paced surroundings"],
    extraSources: [TOURISM_BOARD_SOURCE("Tourism Authority of Thailand")],
    confidence: 88,
  }),

  dest({
    slug: "phuket",
    name: "Phuket",
    countryIso2: "TH",
    countryName: "Thailand",
    region: "Southeast Asia",
    summary:
      "Thailand's biggest island: long beaches, island-hopping to Phi Phi and James Bond Island, family resorts and lively nightlife zones you can opt into or avoid.",
    positioningLine: "Full-service beach holiday with legendary island day trips.",
    idealTraveller: "Beach-first families and groups who want resorts, boat days and plenty of dining choice.",
    minimumNights: 4, idealNights: 5, maximumNights: 8,
    suitablePaces: ["relaxed", "balanced"],
    interests: { beach: 95, relaxation: 88, nightlife: 80, adventure: 75, food: 80, romance: 78, nature: 70, shopping: 60, culture: 50, city: 40, themeparks: 55, history: 30, wildlife: 55, snow: 0 },
    suitability: { family: 85, toddlers: 75, children5To10: 85, teenagers: 85, seniors: 75, honeymoon: 85, solo: 80, firstInternationalTrip: 88 },
    food: { vegetarianFriendly: 72, indianFoodAvailability: 80, halalFriendly: 75, localCuisineScore: 88, streetFoodScore: 85, fineDiningScore: 80 },
    travelPracticality: { averageFlightHoursFromIndia: 4.5, walkingIntensity: "low", publicTransportEase: 45, roadTransferBurden: "medium", accessibilityScore: 60, medicalAccessScore: 80 },
    budgetBands: ["value", "comfort", "premium", "luxury"],
    climateTags: ["tropical", "humid", "dry-season-nov-apr"],
    monthlyIntelligence: buildMonths({
      scores: [92, 92, 85, 72, 55, 50, 48, 48, 45, 55, 75, 90],
      temps: "tropical",
      veryRainy: [9, 10], rainy: [5, 6, 7, 8], humid: [4, 5, 6, 7, 8, 9, 10],
      crowded: [12, 1, 2], quiet: [9, 10],
      highlights: { 12: ["Calm seas — best island-hopping window"], 2: ["Dry, sunny beach perfection"] },
      warnings: { 9: ["Monsoon seas — boat trips often cancelled"], 6: ["Rough west-coast swimming; watch flag warnings"] },
    }),
    commonTripCombinations: ["Bangkok + Phuket", "Phuket + Krabi", "Phuket + Phi Phi overnight"],
    commonMistakes: ["Booking beach plans in September without weather buffers", "Staying in Patong when seeking quiet (or vice versa)"],
    packingConsiderations: ["Reef-safe sunscreen", "Motion-sickness tablets for speedboat days", "Water shoes for rocky coves"],
    practicalWarnings: ["Respect red-flag swimming warnings in monsoon months"],
    tradeOffs: ["Very touristy in peak zones", "Monsoon (May–Oct) limits island hopping"],
    whoShouldAvoid: ["Travellers seeking an untouched, crowd-free island feel"],
    extraSources: [TOURISM_BOARD_SOURCE("Tourism Authority of Thailand")],
    confidence: 86,
  }),

  dest({
    slug: "krabi",
    name: "Krabi",
    countryIso2: "TH",
    countryName: "Thailand",
    region: "Southeast Asia",
    summary:
      "Limestone karsts rising from emerald water, Railay's famous beaches and four-island boat days — Thailand's dramatic, calmer beach alternative.",
    positioningLine: "Thailand's most dramatic coastline, without Phuket's crowds.",
    idealTraveller: "Couples and nature-leaning families who want postcard scenery and a slower rhythm.",
    minimumNights: 3, idealNights: 5, maximumNights: 7,
    suitablePaces: ["relaxed", "balanced"],
    interests: { beach: 95, nature: 90, adventure: 80, relaxation: 88, romance: 85, food: 70, nightlife: 45, culture: 45, shopping: 35, city: 20, themeparks: 15, history: 25, wildlife: 55, snow: 0 },
    suitability: { family: 78, toddlers: 65, children5To10: 78, teenagers: 82, seniors: 68, honeymoon: 90, solo: 82, firstInternationalTrip: 80 },
    food: { vegetarianFriendly: 70, indianFoodAvailability: 65, halalFriendly: 80, localCuisineScore: 85, streetFoodScore: 78, fineDiningScore: 65 },
    travelPracticality: { averageFlightHoursFromIndia: 6, walkingIntensity: "medium", publicTransportEase: 35, roadTransferBurden: "medium", accessibilityScore: 50, medicalAccessScore: 65 },
    budgetBands: ["value", "comfort", "premium"],
    climateTags: ["tropical", "humid", "dry-season-nov-apr"],
    monthlyIntelligence: buildMonths({
      scores: [92, 92, 85, 72, 55, 50, 48, 48, 45, 55, 75, 90],
      temps: "tropical",
      veryRainy: [9, 10], rainy: [5, 6, 7, 8], humid: [4, 5, 6, 7, 8, 9, 10],
      crowded: [12, 1, 2], quiet: [9, 10],
      highlights: { 1: ["Glass-calm seas around the four islands"], 12: ["Best Railay conditions of the year"] },
      warnings: { 9: ["Monsoon — island trips frequently cancelled"], 10: ["Sea conditions unpredictable"] },
    }),
    commonTripCombinations: ["Krabi + Phuket", "Krabi + Koh Lanta", "Bangkok + Krabi"],
    commonMistakes: ["Expecting Railay access by road — it's boat-only", "Day-tripping Phi Phi from Krabi on a tight schedule"],
    packingConsiderations: ["Dry bag for longtail boat rides", "Water shoes", "Reef-safe sunscreen"],
    practicalWarnings: ["Longtail boats stop in rough weather; keep the last day flexible"],
    tradeOffs: ["Fewer dining and nightlife options than Phuket", "Beach access often involves boats"],
    whoShouldAvoid: ["Travellers wanting big-resort infrastructure and nightlife"],
    extraSources: [TOURISM_BOARD_SOURCE("Tourism Authority of Thailand")],
    confidence: 82,
  }),

  dest({
    slug: "kuala-lumpur",
    name: "Kuala Lumpur",
    countryIso2: "MY",
    countryName: "Malaysia",
    region: "Southeast Asia",
    summary:
      "The Petronas Towers skyline, Batu Caves, serious street food and huge malls — an easy, halal-friendly city break with great connections onward.",
    positioningLine: "Skyline, street food and shopping — remarkable value.",
    idealTraveller: "City-breakers and families who want an easy, affordable long weekend abroad.",
    minimumNights: 3, idealNights: 4, maximumNights: 5,
    suitablePaces: ["relaxed", "balanced"],
    interests: { city: 88, food: 88, shopping: 88, culture: 72, themeparks: 65, nightlife: 65, history: 55, relaxation: 55, romance: 60, nature: 50, beach: 10, adventure: 45, wildlife: 45, snow: 0 },
    suitability: { family: 85, toddlers: 78, children5To10: 85, teenagers: 82, seniors: 82, honeymoon: 65, solo: 82, firstInternationalTrip: 90 },
    food: { vegetarianFriendly: 80, indianFoodAvailability: 95, halalFriendly: 98, localCuisineScore: 92, streetFoodScore: 94, fineDiningScore: 80 },
    travelPracticality: { averageFlightHoursFromIndia: 4.5, walkingIntensity: "low", publicTransportEase: 80, roadTransferBurden: "low", accessibilityScore: 75, medicalAccessScore: 85 },
    budgetBands: ["value", "comfort", "premium"],
    climateTags: ["tropical", "humid", "warm-all-year"],
    monthlyIntelligence: buildMonths({
      scores: [80, 82, 78, 72, 72, 75, 78, 75, 65, 60, 58, 68],
      temps: "tropical",
      veryRainy: [10, 11], rainy: [3, 4, 9, 12], humid: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      crowded: [12, 6], quiet: [10],
      highlights: { 6: ["Mega Sale shopping season"], 1: ["Thaipusam at Batu Caves (verify dates)"] },
      warnings: { 11: ["Afternoon thunderstorms most days"] },
    }),
    commonTripCombinations: ["Kuala Lumpur + Langkawi", "Kuala Lumpur + Singapore", "Kuala Lumpur + Genting Highlands"],
    commonMistakes: ["Walking between districts in midday humidity instead of using the LRT/monorail"],
    packingConsiderations: ["Breathable clothing", "Compact umbrella — showers strike fast", "Modest wear for mosques and temples"],
    practicalWarnings: ["Afternoon downpours are routine; plan indoor slots after lunch"],
    tradeOffs: ["Humidity is constant year-round", "Fewer marquee sights beyond four days"],
    whoShouldAvoid: ["Travellers chasing beaches or a dry, temperate climate"],
    extraSources: [TOURISM_BOARD_SOURCE("Tourism Malaysia")],
    confidence: 85,
  }),

  dest({
    slug: "langkawi",
    name: "Langkawi",
    countryIso2: "MY",
    countryName: "Malaysia",
    region: "Southeast Asia",
    summary:
      "A duty-free island of jungle-backed beaches, the famous SkyBridge cable car and mangrove boat safaris — Malaysia's easy-going beach escape.",
    positioningLine: "Relaxed island beaches with a jungle heart.",
    idealTraveller: "Families and couples wanting calm beaches, nature days and resort value.",
    minimumNights: 3, idealNights: 4, maximumNights: 6,
    suitablePaces: ["relaxed", "balanced"],
    interests: { beach: 90, nature: 85, relaxation: 90, romance: 80, adventure: 65, food: 70, wildlife: 65, shopping: 55, culture: 40, nightlife: 40, city: 15, themeparks: 30, history: 25, snow: 0 },
    suitability: { family: 88, toddlers: 80, children5To10: 88, teenagers: 78, seniors: 82, honeymoon: 85, solo: 70, firstInternationalTrip: 85 },
    food: { vegetarianFriendly: 75, indianFoodAvailability: 85, halalFriendly: 98, localCuisineScore: 82, streetFoodScore: 78, fineDiningScore: 72 },
    travelPracticality: { averageFlightHoursFromIndia: 6, walkingIntensity: "low", publicTransportEase: 35, roadTransferBurden: "low", accessibilityScore: 65, medicalAccessScore: 70 },
    budgetBands: ["value", "comfort", "premium", "luxury"],
    climateTags: ["tropical", "humid", "dry-season-dec-mar"],
    monthlyIntelligence: buildMonths({
      scores: [90, 90, 85, 72, 60, 62, 62, 58, 45, 48, 60, 85],
      temps: "tropical",
      veryRainy: [9, 10], rainy: [4, 5, 8, 11], humid: [3, 4, 5, 6, 7, 8, 9, 10],
      crowded: [12, 1], quiet: [9, 10],
      highlights: { 1: ["Calm seas and clear island-hopping days"], 12: ["Best beach weather begins"] },
      warnings: { 9: ["Wettest month — expect daily rain"], 10: ["Sea activities frequently affected"] },
    }),
    commonTripCombinations: ["Kuala Lumpur + Langkawi", "Langkawi + Penang"],
    commonMistakes: ["Skipping the cable car on the one clear morning — go early when skies allow"],
    packingConsiderations: ["Reef-safe sunscreen", "Insect repellent for mangrove tours", "Light rain layer outside Dec–Mar"],
    practicalWarnings: ["Jellyfish occasionally present — heed beach notices"],
    tradeOffs: ["Quiet nightlife and limited shopping beyond duty-free", "Sea clarity varies by season"],
    whoShouldAvoid: ["Travellers wanting a lively boardwalk scene"],
    extraSources: [TOURISM_BOARD_SOURCE("Tourism Malaysia")],
    confidence: 82,
  }),

  dest({
    slug: "vietnam",
    name: "Vietnam",
    countryIso2: "VN",
    countryName: "Vietnam",
    region: "Southeast Asia",
    summary:
      "Ha Long Bay cruises, lantern-lit Hoi An, buzzing street food and dramatic caves — a rising favourite with excellent value.",
    positioningLine: "Story-rich landscapes at unbeatable value.",
    idealTraveller: "Curious travellers happy to move between regions for scenery, food and culture.",
    minimumNights: 5, idealNights: 7, maximumNights: 12,
    suitablePaces: ["balanced", "active"],
    interests: { culture: 90, food: 92, nature: 88, adventure: 82, history: 85, beach: 70, city: 75, relaxation: 60, romance: 75, shopping: 65, nightlife: 65, themeparks: 40, wildlife: 55, snow: 0 },
    suitability: { family: 70, toddlers: 55, children5To10: 68, teenagers: 80, seniors: 62, honeymoon: 80, solo: 88, firstInternationalTrip: 72 },
    food: { vegetarianFriendly: 70, indianFoodAvailability: 55, halalFriendly: 45, localCuisineScore: 95, streetFoodScore: 95, fineDiningScore: 75 },
    travelPracticality: { averageFlightHoursFromIndia: 5.5, walkingIntensity: "medium", publicTransportEase: 55, roadTransferBurden: "high", accessibilityScore: 50, medicalAccessScore: 65 },
    budgetBands: ["value", "comfort", "premium"],
    climateTags: ["tropical", "regional-contrast", "typhoon-season-aug-nov"],
    monthlyIntelligence: buildMonths({
      scores: [80, 82, 85, 82, 70, 60, 55, 55, 55, 65, 78, 80],
      temps: "tropical", tempOverrides: { 12: "mild", 1: "mild", 2: "mild" },
      veryRainy: [7, 8, 9], rainy: [5, 6, 10], humid: [4, 5, 6, 7, 8, 9],
      crowded: [12, 1], quiet: [9],
      highlights: { 2: ["Cool, clear weather in the north; Tet festival atmosphere (verify dates)"], 3: ["Best all-round month across regions"] },
      warnings: { 9: ["Typhoon season on the central coast"], 7: ["Hot and wet in the north"] },
    }),
    commonTripCombinations: ["Hanoi + Ha Long + Da Nang/Hoi An", "Ho Chi Minh City + Mekong Delta", "Vietnam + Cambodia"],
    commonMistakes: ["Planning one itinerary for the whole country — north and south have opposite weather", "Underestimating internal travel time"],
    packingConsiderations: ["Layers for the cooler north in winter", "Rain protection in monsoon months", "Comfortable shoes for old-quarter walking"],
    practicalWarnings: ["Cross roads slowly and predictably — scooter traffic flows around you"],
    tradeOffs: ["Regions have opposite weather patterns — routing matters", "Long distances between north and south"],
    whoShouldAvoid: ["Travellers wanting a single-base, no-transfers beach holiday"],
    extraSources: [TOURISM_BOARD_SOURCE("Vietnam National Authority of Tourism")],
    confidence: 84,
  }),
];
