import type { DestinationIntelligence } from "../../src/types/knowledge";
import { buildMonths, dest, TOURISM_BOARD_SOURCE } from "./builders";

export const DESTINATIONS_6: DestinationIntelligence[] = [
  dest({
    slug: "germany",
    name: "Germany",
    countryIso2: "DE",
    countryName: "Germany",
    region: "Western Europe",
    summary:
      "Fairy-tale castles above forested hills, Berlin's history and nightlife, beer halls, Christmas markets and trains that make it all effortless — Europe's most underrated all-rounder.",
    positioningLine: "Castles, Christmas markets and cities that work perfectly.",
    idealTraveller: "First-time Europe travellers, history lovers and families who value smooth logistics.",
    minimumNights: 5, idealNights: 8, maximumNights: 14,
    suitablePaces: ["balanced", "active"],
    interests: { history: 90, culture: 88, city: 85, nature: 75, food: 70, shopping: 70, romance: 68, nightlife: 75, relaxation: 50, adventure: 50, themeparks: 65, snow: 40, wildlife: 15, beach: 10 },
    suitability: { family: 82, toddlers: 70, children5To10: 80, teenagers: 82, seniors: 80, honeymoon: 70, solo: 85, firstInternationalTrip: 72 },
    food: { vegetarianFriendly: 65, indianFoodAvailability: 75, halalFriendly: 70, localCuisineScore: 75, streetFoodScore: 70, fineDiningScore: 80 },
    travelPracticality: { averageFlightHoursFromIndia: 9, walkingIntensity: "medium", publicTransportEase: 92, roadTransferBurden: "low", accessibilityScore: 88, medicalAccessScore: 92 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["temperate", "cold-winter", "mild-summer"],
    monthlyIntelligence: buildMonths({
      scores: [40, 42, 50, 68, 80, 85, 85, 82, 80, 70, 50, 72],
      temps: "temperateNorth",
      rainy: [6, 7, 8], humid: [7, 8],
      crowded: [7, 8, 12], quiet: [1, 2, 11],
      highlights: { 12: ["Christmas markets transform every town square"], 9: ["Beer-festival season and golden countryside (verify festival dates)"], 5: ["Long bright evenings, castles at their photogenic best"] },
      warnings: { 1: ["Short grey days — a cities-and-museums month"], 11: ["The dullest window: post-autumn, pre-markets"] },
    }),
    commonTripCombinations: ["Berlin + Munich + Neuschwanstein by rail", "Germany + Austria + Switzerland", "Rhine Valley + Cologne"],
    commonMistakes: ["Only doing Berlin and Munich — the small towns are the fairy tale", "Underestimating distances; use the trains"],
    packingConsiderations: ["Layers year-round", "Rain shell for summer showers", "Serious warmth for market evenings in December"],
    practicalWarnings: ["Many smaller shops close Sundays; card acceptance still trails cash in places"],
    tradeOffs: ["Food scene is hearty rather than dazzling for vegetarians outside big cities", "Winter daylight is short"],
    whoShouldAvoid: ["Beach-first travellers", "Anyone wanting tropical warmth"],
    extraSources: [TOURISM_BOARD_SOURCE("German National Tourist Board")],
    confidence: 82,
  }),

  dest({
    slug: "netherlands",
    name: "Netherlands",
    countryIso2: "NL",
    countryName: "Netherlands",
    region: "Western Europe",
    summary:
      "Canals under gabled houses, tulip fields to the horizon in spring, world-class art and villages where boats replace cars — compact, flat and endlessly photogenic.",
    positioningLine: "Canals, tulips and masterpieces — Europe at its prettiest.",
    idealTraveller: "Couples and culture lovers wanting maximum charm with minimum transit.",
    minimumNights: 3, idealNights: 5, maximumNights: 8,
    suitablePaces: ["relaxed", "balanced"],
    interests: { culture: 90, city: 85, history: 80, romance: 80, nature: 65, food: 65, shopping: 70, relaxation: 60, nightlife: 75, adventure: 35, themeparks: 50, wildlife: 10, beach: 20, snow: 5 },
    suitability: { family: 78, toddlers: 70, children5To10: 78, teenagers: 78, seniors: 82, honeymoon: 78, solo: 85, firstInternationalTrip: 75 },
    food: { vegetarianFriendly: 70, indianFoodAvailability: 72, halalFriendly: 72, localCuisineScore: 65, streetFoodScore: 65, fineDiningScore: 78 },
    travelPracticality: { averageFlightHoursFromIndia: 9, walkingIntensity: "medium", publicTransportEase: 94, roadTransferBurden: "low", accessibilityScore: 86, medicalAccessScore: 92 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["temperate-maritime", "mild", "rain-any-month"],
    monthlyIntelligence: buildMonths({
      scores: [42, 44, 55, 80, 82, 80, 82, 80, 72, 62, 48, 60],
      temps: "temperateNorth", tempOverrides: { 7: "warm", 8: "warm", 6: "mild" },
      rainy: [1, 10, 11, 12],
      crowded: [4, 5, 7, 8], quiet: [1, 2, 11],
      highlights: { 4: ["Tulip season — Keukenhof and the bulb fields in full colour (verify open dates)"], 12: ["Canal-side lights and cosy museum days"] },
      warnings: { 11: ["Grey, wet and windy — indoor plans essential"], 4: ["Tulip crowds are real; book everything early"] },
    }),
    commonTripCombinations: ["Amsterdam + Belgium", "Amsterdam + Paris by rail", "Netherlands + Germany"],
    commonMistakes: ["Visiting for tulips outside the spring window", "Staying only in central Amsterdam — day trips are effortless"],
    packingConsiderations: ["A rain layer every month of the year", "Comfortable shoes for cobbles and canals"],
    practicalWarnings: ["Book Keukenhof, Anne Frank House and canal-side restaurants well ahead in season"],
    tradeOffs: ["Weather is a lottery outside high summer", "Prices run high in tulip season"],
    whoShouldAvoid: ["Sun-guarantee seekers", "Travellers who hate cycling-dominated streets"],
    extraSources: [TOURISM_BOARD_SOURCE("Netherlands Board of Tourism")],
    confidence: 82,
  }),

  dest({
    slug: "croatia",
    name: "Croatia",
    countryIso2: "HR",
    countryName: "Croatia",
    region: "Southern Europe",
    summary:
      "Marble old towns dropping into a turquoise Adriatic, waterfall national parks and a thousand islands — Mediterranean beauty before the Mediterranean prices.",
    positioningLine: "The Adriatic's walled towns, waterfalls and island summers.",
    idealTraveller: "Couples and friends who want Mediterranean glamour, history and swimmable seas together.",
    minimumNights: 5, idealNights: 7, maximumNights: 12,
    suitablePaces: ["relaxed", "balanced"],
    interests: { beach: 82, history: 85, nature: 85, culture: 80, romance: 85, food: 72, relaxation: 78, city: 60, adventure: 60, nightlife: 70, shopping: 45, wildlife: 15, themeparks: 5, snow: 5 },
    suitability: { family: 75, toddlers: 60, children5To10: 72, teenagers: 80, seniors: 70, honeymoon: 86, solo: 78, firstInternationalTrip: 70 },
    food: { vegetarianFriendly: 60, indianFoodAvailability: 40, halalFriendly: 45, localCuisineScore: 78, streetFoodScore: 60, fineDiningScore: 72 },
    travelPracticality: { averageFlightHoursFromIndia: 10, walkingIntensity: "high", publicTransportEase: 55, roadTransferBurden: "medium", accessibilityScore: 55, medicalAccessScore: 75 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["mediterranean", "hot-dry-summer", "mild-winter"],
    monthlyIntelligence: buildMonths({
      scores: [40, 45, 55, 70, 85, 90, 88, 85, 90, 75, 50, 45],
      temps: "mediterranean",
      rainy: [10, 11, 12], dry: [6, 7, 8],
      crowded: [7, 8], quiet: [1, 2, 11, 12],
      highlights: { 6: ["Warm sea before peak crowds — the sweet spot"], 9: ["Sea still warm, crowds gone, light golden"] },
      warnings: { 8: ["Dubrovnik's walls at midday are a slow, hot queue"], 1: ["Many island hotels and ferries hibernate"] },
    }),
    commonTripCombinations: ["Dubrovnik + Split + Hvar", "Croatia + Slovenia + Plitvice", "Adriatic cruise add-on"],
    commonMistakes: ["August in Dubrovnik without dawn starts", "Trying five islands in a week — pick two"],
    packingConsiderations: ["Water shoes for pebble beaches", "Sun cover for stone streets that radiate heat", "A layer for sea breezes at night"],
    practicalWarnings: ["Old-town stays mean stairs and cobbles — pack light or choose hotels with porters"],
    tradeOffs: ["Peak summer is crowded and priced accordingly", "Beaches are pebble, not sand"],
    whoShouldAvoid: ["Travellers needing step-free stays — old towns are vertical", "White-sand purists"],
    extraSources: [TOURISM_BOARD_SOURCE("Croatian National Tourist Board")],
    confidence: 80,
  }),

  dest({
    slug: "hungary",
    name: "Hungary",
    countryIso2: "HU",
    countryName: "Hungary",
    region: "Central Europe",
    summary:
      "Budapest's parliament glowing over the Danube, thermal baths from the Ottoman age, ruin bars in crumbling courtyards and Europe's best-value grandeur.",
    positioningLine: "Danube grandeur, thermal baths and ruin-bar nights — at half Western prices.",
    idealTraveller: "Couples, friends and culture fans who want imperial Europe without imperial bills.",
    minimumNights: 3, idealNights: 4, maximumNights: 7,
    suitablePaces: ["relaxed", "balanced"],
    interests: { city: 88, culture: 85, history: 85, nightlife: 82, romance: 80, food: 72, relaxation: 75, shopping: 60, nature: 40, adventure: 30, wildlife: 5, beach: 5, themeparks: 10, snow: 15 },
    suitability: { family: 70, toddlers: 60, children5To10: 68, teenagers: 78, seniors: 78, honeymoon: 80, solo: 85, firstInternationalTrip: 72 },
    food: { vegetarianFriendly: 55, indianFoodAvailability: 55, halalFriendly: 45, localCuisineScore: 78, streetFoodScore: 70, fineDiningScore: 75 },
    travelPracticality: { averageFlightHoursFromIndia: 8.5, walkingIntensity: "medium", publicTransportEase: 85, roadTransferBurden: "low", accessibilityScore: 70, medicalAccessScore: 80 },
    budgetBands: ["value", "comfort", "premium"],
    climateTags: ["continental", "cold-winter", "warm-summer"],
    monthlyIntelligence: buildMonths({
      scores: [42, 45, 55, 72, 82, 85, 82, 80, 80, 70, 52, 68],
      temps: "temperateNorth", tempOverrides: { 7: "hot", 8: "hot" },
      rainy: [5, 6],
      crowded: [7, 8, 12], quiet: [1, 2],
      highlights: { 12: ["Christmas markets plus steaming outdoor thermal baths"], 5: ["Café terraces open, Danube cruises at golden hour"] },
      warnings: { 7: ["Heatwaves push mid-30s — baths and shade by afternoon"], 1: ["Cold and grey, though baths and cafés compensate"] },
    }),
    commonTripCombinations: ["Budapest + Vienna + Prague", "Budapest + Lake Balaton (summer)"],
    commonMistakes: ["Day-tripping the baths — go at opening or at night, unhurried", "Missing the Buda side entirely"],
    packingConsiderations: ["Swimwear and flip-flops for the baths", "Smart-casual layer for river-cruise dinners"],
    practicalWarnings: ["Validate public-transport tickets — inspectors fine tourists daily"],
    tradeOffs: ["Beyond Budapest, sights thin out quickly for short trips", "Hearty cuisine challenges strict vegetarians"],
    whoShouldAvoid: ["Nature-first travellers", "Beach seekers"],
    extraSources: [TOURISM_BOARD_SOURCE("Hungarian Tourism Agency")],
    confidence: 80,
  }),

  dest({
    slug: "norway",
    name: "Norway",
    countryIso2: "NO",
    countryName: "Norway",
    region: "Northern Europe",
    summary:
      "Fjords like flooded cathedrals, the midnight sun, hairpin railways and the northern lights — nature at a scale that rearranges your sense of the world.",
    positioningLine: "Fjords, midnight sun and northern lights — nature's grand opera.",
    idealTraveller: "Scenery chasers and honeymooners for whom the landscape is the destination.",
    minimumNights: 5, idealNights: 7, maximumNights: 12,
    suitablePaces: ["relaxed", "balanced"],
    interests: { nature: 98, romance: 82, adventure: 78, snow: 75, relaxation: 70, culture: 55, city: 50, history: 55, food: 60, wildlife: 55, nightlife: 40, shopping: 35, beach: 5, themeparks: 5 },
    suitability: { family: 72, toddlers: 58, children5To10: 70, teenagers: 80, seniors: 72, honeymoon: 88, solo: 80, firstInternationalTrip: 60 },
    food: { vegetarianFriendly: 55, indianFoodAvailability: 50, halalFriendly: 50, localCuisineScore: 70, streetFoodScore: 45, fineDiningScore: 78 },
    travelPracticality: { averageFlightHoursFromIndia: 10.5, walkingIntensity: "medium", publicTransportEase: 80, roadTransferBurden: "medium", accessibilityScore: 75, medicalAccessScore: 88 },
    budgetBands: ["premium", "luxury"],
    climateTags: ["nordic", "midnight-sun-summer", "polar-night-north"],
    monthlyIntelligence: buildMonths({
      scores: [50, 52, 55, 60, 75, 88, 90, 85, 72, 55, 48, 50],
      temps: ["cold", "cold", "cool", "cool", "mild", "mild", "warm", "warm", "mild", "cool", "cool", "cold"],
      veryRainy: [9, 10, 11], rainy: [1, 8, 12],
      crowded: [6, 7], quiet: [11, 1],
      highlights: { 6: ["Midnight sun over the fjords — surreal, endless days"], 7: ["Every trail, ferry and viewpoint open"], 1: ["Northern-lights season in the Arctic north (verify aurora forecasts)"] },
      warnings: { 11: ["Dark, wet shoulder — neither summer fjords nor reliable lights"], 9: ["Bergen's rainiest stretch begins"] },
    }),
    commonTripCombinations: ["Bergen + Flåm + Oslo 'Norway in a Nutshell'", "Tromsø northern-lights add-on", "Norway + Denmark/Sweden"],
    commonMistakes: ["Expecting northern lights in summer — midnight sun cancels them", "Underbudgeting: Norway is genuinely expensive"],
    packingConsiderations: ["Waterproof everything, all seasons", "Layers over bulk — weather flips hourly", "Eye mask for midnight-sun sleep"],
    practicalWarnings: ["Book fjord-season hotels and the Flåm Railway months ahead"],
    tradeOffs: ["Among the world's priciest destinations — value comes from scenery, not comfort per rupee", "Weather can hide the very views you came for"],
    whoShouldAvoid: ["Budget travellers", "Warm-weather-only holidaymakers"],
    extraSources: [TOURISM_BOARD_SOURCE("Visit Norway")],
    confidence: 80,
  }),

  dest({
    slug: "iceland",
    name: "Iceland",
    countryIso2: "IS",
    countryName: "Iceland",
    region: "Northern Europe",
    summary:
      "Erupting geysers, black-sand beaches, glacier lagoons and skies that dance green in winter — a young volcanic island that feels like another planet.",
    positioningLine: "Fire, ice and aurora — Earth showing off.",
    idealTraveller: "Bucket-list adventurers and photographers chasing landscapes that exist nowhere else.",
    minimumNights: 4, idealNights: 6, maximumNights: 10,
    suitablePaces: ["balanced", "active"],
    interests: { nature: 98, adventure: 88, romance: 75, snow: 70, relaxation: 65, wildlife: 50, culture: 45, city: 35, history: 40, food: 55, nightlife: 45, shopping: 30, beach: 15, themeparks: 0 },
    suitability: { family: 68, toddlers: 50, children5To10: 65, teenagers: 82, seniors: 62, honeymoon: 85, solo: 82, firstInternationalTrip: 55 },
    food: { vegetarianFriendly: 55, indianFoodAvailability: 40, halalFriendly: 40, localCuisineScore: 65, streetFoodScore: 50, fineDiningScore: 72 },
    travelPracticality: { averageFlightHoursFromIndia: 13, walkingIntensity: "medium", publicTransportEase: 35, roadTransferBurden: "high", accessibilityScore: 55, medicalAccessScore: 80 },
    budgetBands: ["premium", "luxury"],
    climateTags: ["subarctic", "volatile-weather", "aurora-winter"],
    monthlyIntelligence: buildMonths({
      scores: [55, 58, 60, 62, 72, 85, 88, 85, 75, 62, 55, 58],
      temps: ["cold", "cold", "cold", "cool", "cool", "mild", "mild", "mild", "cool", "cool", "cold", "cold"],
      veryRainy: [10, 11], rainy: [9, 12, 1, 2],
      crowded: [7, 8], quiet: [11, 5],
      highlights: { 7: ["Midnight sun, every highland road open"], 2: ["Prime aurora hunting with longer days than December (verify forecasts)"], 9: ["Aurora season starts while roads stay easy"] },
      warnings: { 12: ["Four hours of daylight and storm-prone roads"], 1: ["Winter driving is serious — guided tours beat self-drive"] },
    }),
    commonTripCombinations: ["Golden Circle + south coast", "Ring Road (10+ nights)", "Iceland stopover en route to North America"],
    commonMistakes: ["Treating winter self-drive casually — storms close roads fast", "Only booking Blue Lagoon on landing day — flight delays forfeit it"],
    packingConsiderations: ["True waterproof shell and layers", "Swimwear for lagoons year-round", "Crampon grips for icy paths in winter"],
    practicalWarnings: ["Aurora is a probability, not a promise — plan joy that doesn't depend on it"],
    tradeOffs: ["Extreme cost — Iceland out-prices even Norway", "Weather owns every plan you make"],
    whoShouldAvoid: ["Budget travellers", "Anyone needing warmth or urban buzz"],
    extraSources: [TOURISM_BOARD_SOURCE("Visit Iceland")],
    confidence: 78,
  }),

  dest({
    slug: "united-states",
    name: "United States",
    countryIso2: "US",
    countryName: "United States",
    region: "North America",
    summary:
      "Manhattan's skyline, the Grand Canyon's silence, Orlando's theme-park universe and Pacific-coast drives — a continent of icons that rewards ambition and planning.",
    positioningLine: "The icons: NYC, the Canyon, Vegas, Orlando — think big.",
    idealTraveller: "Families and bucket-listers ready for a long-haul epic across multiple cities.",
    minimumNights: 8, idealNights: 12, maximumNights: 21,
    suitablePaces: ["balanced", "active"],
    interests: { city: 92, themeparks: 90, nature: 85, shopping: 88, food: 80, nightlife: 80, culture: 75, history: 65, adventure: 70, romance: 70, wildlife: 45, relaxation: 55, beach: 60, snow: 40 },
    suitability: { family: 85, toddlers: 68, children5To10: 85, teenagers: 92, seniors: 68, honeymoon: 78, solo: 78, firstInternationalTrip: 50 },
    food: { vegetarianFriendly: 75, indianFoodAvailability: 88, halalFriendly: 70, localCuisineScore: 82, streetFoodScore: 78, fineDiningScore: 92 },
    travelPracticality: { averageFlightHoursFromIndia: 15, walkingIntensity: "medium", publicTransportEase: 55, roadTransferBurden: "medium", accessibilityScore: 90, medicalAccessScore: 90 },
    budgetBands: ["premium", "luxury"],
    climateTags: ["continental-varied", "four-seasons", "regional-extremes"],
    monthlyIntelligence: buildMonths({
      scores: [45, 48, 58, 75, 82, 80, 75, 75, 85, 88, 70, 72],
      temps: "temperateNorth",
      rainy: [3, 4, 7], humid: [6, 7, 8],
      crowded: [7, 12], quiet: [1, 2],
      highlights: { 10: ["Fall colours from New England to Central Park"], 5: ["Everything open, national parks before peak heat"], 12: ["Holiday-season New York is its own spectacle"] },
      warnings: { 7: ["East-coast humidity and desert-park extreme heat"], 1: ["North-east cold snaps can ground flights"] },
    }),
    commonTripCombinations: ["New York + Niagara + Washington DC", "Vegas + Grand Canyon + LA/San Francisco", "Orlando theme-park week"],
    commonMistakes: ["Cramming both coasts into ten days", "Ignoring internal flight time and jet lag — it's a continent"],
    packingConsiderations: ["Layers for wild regional swings", "Comfortable shoes — American attractions mean miles of walking", "Universal adapter and tipping cash"],
    practicalWarnings: ["Health cover matters here more than anywhere — confirm comprehensive travel insurance"],
    tradeOffs: ["The long-haul flight and jet lag eat two days of any itinerary", "Costs compound fast: tips, taxes, internal flights"],
    whoShouldAvoid: ["Short-break travellers — under a week barely lands", "Tight budgets"],
    extraSources: [TOURISM_BOARD_SOURCE("Brand USA")],
    confidence: 80,
  }),

  dest({
    slug: "canada",
    name: "Canada",
    countryIso2: "CA",
    countryName: "Canada",
    region: "North America",
    summary:
      "Turquoise lakes under Rocky Mountain walls, Niagara's thunder, whale-rich coasts and cities that top livability charts — wilderness with excellent manners.",
    positioningLine: "Rockies, Niagara and civilised wilderness.",
    idealTraveller: "Nature-loving families and couples who want epic outdoors with polished comfort.",
    minimumNights: 7, idealNights: 10, maximumNights: 16,
    suitablePaces: ["relaxed", "balanced"],
    interests: { nature: 95, wildlife: 70, city: 70, adventure: 72, romance: 75, snow: 65, relaxation: 65, food: 70, culture: 65, history: 55, shopping: 65, nightlife: 60, beach: 20, themeparks: 30 },
    suitability: { family: 82, toddlers: 65, children5To10: 80, teenagers: 85, seniors: 72, honeymoon: 82, solo: 80, firstInternationalTrip: 55 },
    food: { vegetarianFriendly: 72, indianFoodAvailability: 85, halalFriendly: 72, localCuisineScore: 75, streetFoodScore: 68, fineDiningScore: 85 },
    travelPracticality: { averageFlightHoursFromIndia: 14.5, walkingIntensity: "medium", publicTransportEase: 60, roadTransferBurden: "medium", accessibilityScore: 88, medicalAccessScore: 90 },
    budgetBands: ["premium", "luxury"],
    climateTags: ["continental", "severe-winter", "glorious-summer"],
    monthlyIntelligence: buildMonths({
      scores: [40, 40, 48, 62, 78, 85, 88, 85, 82, 75, 55, 50],
      temps: "temperateNorth", tempOverrides: { 12: "cold", 3: "cold" },
      rainy: [4, 5, 6],
      crowded: [7, 8], quiet: [11, 3],
      highlights: { 7: ["Rockies' lakes at full turquoise; wildlife everywhere"], 9: ["Larch gold in the mountains, maple red in the east"], 6: ["Long days, whales on both coasts"] },
      warnings: { 1: ["Deep-freeze cold shocks first-timers — this is a ski-trip month"], 11: ["Grey shoulder between colours and snow"] },
    }),
    commonTripCombinations: ["Toronto + Niagara + Rockies", "Vancouver + Rocky Mountaineer", "East-coast fall-colours drive"],
    commonMistakes: ["Underestimating internal distances — Toronto to Banff is a flight, not a drive", "Skipping advance permits for Lake Louise-area parking in summer"],
    packingConsiderations: ["Warm layer even in July for mountain evenings", "Full winter kit December–March", "Bug spray for June lakesides"],
    practicalWarnings: ["Summer Rockies accommodation books out months ahead — commit early"],
    tradeOffs: ["Long-haul flight plus internal flights to reach the Rockies", "Peak-summer prices rival Switzerland"],
    whoShouldAvoid: ["Short-break travellers", "Anyone chasing guaranteed warmth"],
    extraSources: [TOURISM_BOARD_SOURCE("Destination Canada")],
    confidence: 80,
  }),
];
