import type { DestinationIntelligence } from "../../src/types/knowledge";
import { buildMonths, dest, TOURISM_BOARD_SOURCE } from "./builders";

export const DESTINATIONS_5: DestinationIntelligence[] = [
  dest({
    slug: "uzbekistan",
    name: "Uzbekistan",
    countryIso2: "UZ",
    countryName: "Uzbekistan",
    region: "Central Asia",
    summary:
      "Turquoise domes over Registan Square, Silk Road caravanserais and bazaars unchanged in spirit for centuries — history's greatest trade route, hours from India.",
    positioningLine: "The Silk Road, real and affordable — domes, bazaars, legends.",
    idealTraveller: "History and culture lovers who want wow-factor architecture without long flights or big budgets.",
    minimumNights: 4, idealNights: 6, maximumNights: 9,
    suitablePaces: ["balanced", "active"],
    interests: { history: 96, culture: 94, city: 70, food: 72, shopping: 75, nature: 40, romance: 65, relaxation: 45, adventure: 45, nightlife: 35, wildlife: 10, beach: 0, themeparks: 5, snow: 15 },
    suitability: { family: 72, toddlers: 55, children5To10: 65, teenagers: 75, seniors: 75, honeymoon: 68, solo: 85, firstInternationalTrip: 78 },
    food: { vegetarianFriendly: 45, indianFoodAvailability: 55, halalFriendly: 95, localCuisineScore: 80, streetFoodScore: 75, fineDiningScore: 55 },
    travelPracticality: { averageFlightHoursFromIndia: 3, walkingIntensity: "medium", publicTransportEase: 70, roadTransferBurden: "medium", accessibilityScore: 50, medicalAccessScore: 60 },
    budgetBands: ["value", "comfort", "premium"],
    climateTags: ["continental", "hot-dry-summer", "cold-winter"],
    monthlyIntelligence: buildMonths({
      scores: [45, 50, 70, 90, 85, 60, 45, 50, 85, 90, 70, 50],
      temps: "temperateNorth", tempOverrides: { 6: "hot", 7: "hot", 8: "hot", 9: "warm" },
      rainy: [3, 4], dry: [6, 7, 8, 9],
      crowded: [4, 5, 9, 10], quiet: [1, 7, 8],
      highlights: { 4: ["Spring bloom over the madrassas — the classic window"], 10: ["Golden light, harvest bazaars and mild sightseeing days"] },
      warnings: { 7: ["Fierce dry heat — sightseeing only works early and late"], 1: ["Genuinely cold; some heritage courtyards are raw"] },
    }),
    commonTripCombinations: ["Tashkent + Samarkand + Bukhara by fast train", "Add Khiva for the full Silk Road arc"],
    commonMistakes: ["Only visiting Tashkent — the magic is in Samarkand and Bukhara", "Underestimating summer heat on stone plazas"],
    packingConsiderations: ["Modest cover for mosques and madrassas", "Serious sun protection in summer", "Warm layers November–March"],
    practicalWarnings: ["Card acceptance is improving but carry some cash outside big hotels"],
    tradeOffs: ["Vegetarian dining takes planning — the cuisine is meat-led", "Tourism infrastructure is functional rather than polished"],
    whoShouldAvoid: ["Beach seekers and travellers wanting nightlife or resort comfort"],
    extraSources: [TOURISM_BOARD_SOURCE("Uzbekistan Tourism Committee")],
    confidence: 78,
  }),

  dest({
    slug: "almaty",
    name: "Almaty",
    countryIso2: "KZ",
    countryName: "Kazakhstan",
    region: "Central Asia",
    summary:
      "Snow peaks rising straight from leafy boulevards, alpine lakes an hour from coffee shops, skiing in winter and canyon road-trips in summer — the mountain city break India hasn't discovered yet.",
    positioningLine: "Alpine drama a short flight away — lakes, peaks, ski runs.",
    idealTraveller: "Mountain lovers, young couples and friend groups wanting big scenery on a short break.",
    minimumNights: 3, idealNights: 5, maximumNights: 8,
    suitablePaces: ["balanced", "active"],
    interests: { nature: 95, adventure: 85, snow: 88, city: 65, food: 60, culture: 55, shopping: 60, relaxation: 55, romance: 70, history: 45, nightlife: 60, wildlife: 30, beach: 0, themeparks: 15 },
    suitability: { family: 75, toddlers: 60, children5To10: 72, teenagers: 85, seniors: 62, honeymoon: 75, solo: 82, firstInternationalTrip: 75 },
    food: { vegetarianFriendly: 40, indianFoodAvailability: 60, halalFriendly: 90, localCuisineScore: 68, streetFoodScore: 60, fineDiningScore: 65 },
    travelPracticality: { averageFlightHoursFromIndia: 3.5, walkingIntensity: "medium", publicTransportEase: 65, roadTransferBurden: "medium", accessibilityScore: 50, medicalAccessScore: 65 },
    budgetBands: ["value", "comfort", "premium"],
    climateTags: ["continental", "alpine-access", "snow-winter"],
    monthlyIntelligence: buildMonths({
      scores: [68, 70, 60, 65, 75, 85, 88, 88, 85, 75, 60, 70],
      temps: "temperateNorth",
      rainy: [4, 5, 6], dry: [8, 9],
      crowded: [7, 8, 12], quiet: [3, 11],
      highlights: { 7: ["Alpine lakes at full colour; Charyn Canyon road-trips"], 1: ["Shymbulak ski season in full swing"], 12: ["Snow city + ski season begins"] },
      warnings: { 3: ["Slushy shoulder season — mountains half-open"], 11: ["Grey between autumn colour and reliable snow"] },
    }),
    commonTripCombinations: ["Almaty + Charyn Canyon + Kolsai Lakes", "Almaty ski weekend", "Almaty + Tashkent"],
    commonMistakes: ["Day-tripping Big Almaty Lake without warm layers — it's high altitude", "Treating it as a city trip and skipping the mountains"],
    packingConsiderations: ["Layers in every season — city warm, mountains cold", "Sunglasses for snow and altitude", "Sturdy shoes for lake trails"],
    practicalWarnings: ["Mountain roads close in heavy snow — keep flexibility in winter itineraries"],
    tradeOffs: ["English is limited outside tourist services", "Vegetarian options are thin beyond the city centre"],
    whoShouldAvoid: ["Travellers wanting beaches, heritage depth or guaranteed warm weather"],
    extraSources: [TOURISM_BOARD_SOURCE("Kazakh Tourism")],
    confidence: 76,
  }),

  dest({
    slug: "armenia",
    name: "Armenia",
    countryIso2: "AM",
    countryName: "Armenia",
    region: "Caucasus",
    summary:
      "Monasteries carved into cliffs, Mount Ararat filling the horizon, café culture in pink-stone Yerevan and brandy older than most nations — the world's first Christian country, warm and walkable.",
    positioningLine: "Cliff monasteries, Ararat views and Yerevan's easy charm.",
    idealTraveller: "Culture-curious couples and friends who like history with wine, cafés and mountain drives.",
    minimumNights: 3, idealNights: 5, maximumNights: 8,
    suitablePaces: ["relaxed", "balanced"],
    interests: { history: 92, culture: 90, nature: 80, food: 75, romance: 72, city: 65, relaxation: 60, adventure: 50, shopping: 50, nightlife: 55, wildlife: 15, snow: 25, beach: 0, themeparks: 5 },
    suitability: { family: 70, toddlers: 58, children5To10: 65, teenagers: 72, seniors: 75, honeymoon: 74, solo: 84, firstInternationalTrip: 76 },
    food: { vegetarianFriendly: 60, indianFoodAvailability: 50, halalFriendly: 45, localCuisineScore: 82, streetFoodScore: 65, fineDiningScore: 65 },
    travelPracticality: { averageFlightHoursFromIndia: 4, walkingIntensity: "medium", publicTransportEase: 55, roadTransferBurden: "medium", accessibilityScore: 50, medicalAccessScore: 62 },
    budgetBands: ["value", "comfort", "premium"],
    climateTags: ["continental", "dry-summer", "cold-winter"],
    monthlyIntelligence: buildMonths({
      scores: [45, 50, 60, 80, 90, 85, 70, 72, 90, 88, 65, 50],
      temps: "temperateNorth", tempOverrides: { 7: "hot", 8: "hot" },
      rainy: [4, 5], dry: [7, 8, 9],
      crowded: [8, 9, 10], quiet: [1, 2],
      highlights: { 5: ["Green valleys, snow still on Ararat — peak beauty"], 9: ["Grape harvest, golden monastery light and warm days"] },
      warnings: { 7: ["Yerevan bakes in mid-30s dry heat by afternoon"], 1: ["Snow and ice — mountain monasteries need careful driving"] },
    }),
    commonTripCombinations: ["Yerevan + Garni-Geghard + Lake Sevan", "Armenia + Georgia overland"],
    commonMistakes: ["Only staying in Yerevan — the monasteries are the point", "Cramming the far south into a short trip"],
    packingConsiderations: ["Modest cover for monasteries", "Sun hat for dry summer heat", "Real winter kit December–February"],
    practicalWarnings: ["Distances look small but mountain roads are slow — one region per day"],
    tradeOffs: ["Nightlife and shopping are modest", "Winter closes some high monastery roads"],
    whoShouldAvoid: ["Beach and resort travellers", "Anyone allergic to churches and history"],
    extraSources: [TOURISM_BOARD_SOURCE("Tourism Committee of Armenia")],
    confidence: 76,
  }),

  dest({
    slug: "jordan",
    name: "Jordan",
    countryIso2: "JO",
    countryName: "Jordan",
    region: "Middle East",
    summary:
      "Petra's rose-red Treasury at dawn, Wadi Rum's Mars-scape by jeep and a float on the Dead Sea — three of Earth's great travel moments in one compact, welcoming kingdom.",
    positioningLine: "Petra, Wadi Rum, Dead Sea — three wonders, one small country.",
    idealTraveller: "Bucket-listers, photographers and history lovers who don't mind earning views with their feet.",
    minimumNights: 4, idealNights: 6, maximumNights: 9,
    suitablePaces: ["balanced", "active"],
    interests: { history: 96, nature: 88, adventure: 82, culture: 85, romance: 70, relaxation: 60, food: 70, city: 50, wildlife: 20, shopping: 45, nightlife: 30, beach: 40, themeparks: 0, snow: 5 },
    suitability: { family: 74, toddlers: 50, children5To10: 68, teenagers: 85, seniors: 60, honeymoon: 76, solo: 80, firstInternationalTrip: 72 },
    food: { vegetarianFriendly: 70, indianFoodAvailability: 45, halalFriendly: 98, localCuisineScore: 85, streetFoodScore: 75, fineDiningScore: 65 },
    travelPracticality: { averageFlightHoursFromIndia: 5, walkingIntensity: "high", publicTransportEase: 40, roadTransferBurden: "medium", accessibilityScore: 45, medicalAccessScore: 70 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["desert", "mild-spring-autumn", "hot-summer"],
    monthlyIntelligence: buildMonths({
      scores: [55, 60, 80, 90, 88, 75, 60, 60, 80, 90, 85, 60],
      temps: "desert", tempOverrides: { 12: "cool", 1: "cool", 2: "mild" },
      rainy: [1, 2, 12], dry: [5, 6, 7, 8, 9, 10],
      crowded: [4, 10], quiet: [1, 7],
      highlights: { 4: ["Wildflowers at Jerash, perfect Petra hiking weather"], 10: ["Warm Wadi Rum nights and golden canyon light"] },
      warnings: { 7: ["Desert heat makes Petra's trails punishing by mid-morning"], 1: ["Amman can be cold and wet; occasional snow closes roads"] },
    }),
    commonTripCombinations: ["Amman + Petra + Wadi Rum + Dead Sea circuit", "Add Aqaba for Red Sea snorkelling"],
    commonMistakes: ["Giving Petra a half day — it deserves one full day minimum", "Skipping a Wadi Rum overnight, which is the trip's soul"],
    packingConsiderations: ["Proper walking shoes — Petra is kilometres of trail", "Sun protection and refillable water bottle", "Warm layer for desert nights year-round"],
    practicalWarnings: ["Distances between sites mean a driver or tour makes the trip — public transport is thin"],
    tradeOffs: ["It's a walking-heavy destination — comfort depends on fitness", "Costs run higher than Egypt or Turkey for similar days"],
    whoShouldAvoid: ["Travellers with limited mobility — Petra's magic requires distance on foot", "Resort-and-pool holidaymakers"],
    extraSources: [TOURISM_BOARD_SOURCE("Jordan Tourism Board")],
    confidence: 80,
  }),

  dest({
    slug: "zanzibar",
    name: "Zanzibar",
    countryIso2: "TZ",
    countryName: "Tanzania",
    region: "East Africa",
    summary:
      "Powder beaches shading from white to turquoise, Stone Town's carved doors and spice-scented lanes, dhows at sunset — the Indian Ocean's most storied island escape.",
    positioningLine: "Spice-island beaches with Swahili soul and dhow sunsets.",
    idealTraveller: "Honeymooners and beach lovers who want culture and snorkelling with their sunbeds.",
    minimumNights: 4, idealNights: 6, maximumNights: 10,
    suitablePaces: ["relaxed", "balanced"],
    interests: { beach: 96, relaxation: 92, romance: 90, culture: 70, food: 68, nature: 65, adventure: 60, wildlife: 55, history: 65, city: 30, shopping: 45, nightlife: 45, themeparks: 0, snow: 0 },
    suitability: { family: 72, toddlers: 60, children5To10: 70, teenagers: 75, seniors: 65, honeymoon: 95, solo: 70, firstInternationalTrip: 65 },
    food: { vegetarianFriendly: 60, indianFoodAvailability: 75, halalFriendly: 90, localCuisineScore: 75, streetFoodScore: 70, fineDiningScore: 70 },
    travelPracticality: { averageFlightHoursFromIndia: 7, walkingIntensity: "low", publicTransportEase: 30, roadTransferBurden: "medium", accessibilityScore: 40, medicalAccessScore: 50 },
    budgetBands: ["comfort", "premium", "luxury"],
    climateTags: ["tropical", "long-rains-apr-may", "dry-jun-oct"],
    monthlyIntelligence: buildMonths({
      scores: [80, 78, 60, 35, 40, 85, 90, 90, 88, 85, 65, 78],
      temps: "tropical",
      veryRainy: [4, 5], rainy: [3, 11], humid: [1, 2, 3, 4, 11, 12], dry: [7, 8],
      crowded: [12, 1, 8], quiet: [4, 5],
      highlights: { 7: ["Peak dry season — postcard water and cool breezes"], 1: ["Warm seas and vivid snorkelling between the rains"] },
      warnings: { 4: ["Long rains — many beach lodges pause or discount deeply"], 5: ["Rains continue; seaweed can reach some east-coast beaches"] },
    }),
    commonTripCombinations: ["Zanzibar + Serengeti safari", "Stone Town + north-coast beach split"],
    commonMistakes: ["Booking April–May expecting brochure weather", "Ignoring tide tables — east-coast lagoons empty at low tide"],
    packingConsiderations: ["Reef-safe sunscreen and snorkel gear", "Modest wear for Stone Town's lanes", "Light rain layer November and March"],
    practicalWarnings: ["Choose your coast deliberately: north swims all day, east is tidal"],
    tradeOffs: ["Reaching it from India usually means a connection — budget the journey day", "Infrastructure is island-simple outside the resorts"],
    whoShouldAvoid: ["Travellers needing nightlife, malls or step-free everything"],
    extraSources: [TOURISM_BOARD_SOURCE("Zanzibar Commission for Tourism")],
    confidence: 78,
  }),
];
