import type { DestinationKnowledge } from "@/types/destination";
import { buildMonths, seedSources, seedVersion } from "./builders";

type DestinationSeed = Omit<DestinationKnowledge, "id" | "status" | "version" | "sources">;

function dest(seed: DestinationSeed): DestinationKnowledge {
  return {
    ...seed,
    id: seed.slug,
    status: "reviewed",
    version: seedVersion,
    sources: seedSources,
  };
}

export const KTIE_DESTINATIONS: DestinationKnowledge[] = [
  dest({
    slug: "singapore",
    name: "Singapore",
    country: "Singapore",
    region: "Southeast Asia",
    summary:
      "A compact, spotless city-state that mixes gardens, theme parks, hawker food and skyline views. One of the easiest first international trips from India.",
    positioningLine: "Effortless city break with world-class family attractions.",
    minimumNights: 3,
    idealNights: 5,
    maximumNights: 7,
    suitablePaces: ["relaxed", "balanced", "active"],
    interests: { city: 95, food: 90, themeparks: 92, shopping: 88, culture: 70, nature: 60, beach: 40, nightlife: 75, relaxation: 55, romance: 65, history: 55, adventure: 55, wildlife: 65, snow: 0 },
    suitability: { family: 95, toddlers: 90, children5To10: 95, teenagers: 88, seniors: 90, honeymoon: 60, solo: 80, firstInternationalTrip: 95 },
    food: { vegetarianFriendly: 90, indianFoodAvailability: 95, halalFriendly: 90, localCuisineScore: 92, streetFoodScore: 95, fineDiningScore: 90 },
    travelPracticality: { averageFlightHoursFromIndia: 4.5, walkingIntensity: "medium", publicTransportEase: 95, accessibilityScore: 92, medicalAccessScore: 95, visaComplexity: "medium" },
    budgetBands: ["comfort", "premium", "luxury"],
    monthlyIntelligence: buildMonths({
      scores: [78, 80, 80, 75, 72, 72, 74, 74, 72, 70, 65, 70],
      veryRainy: [11, 12], rainy: [1, 4, 10], humid: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      crowded: [6, 12], quiet: [3, 9],
      highlights: { 12: ["Year-end light-ups along Orchard Road"], 6: ["Great Singapore Sale shopping season"] },
      warnings: { 11: ["North-east monsoon showers — keep afternoons flexible"], 12: ["Peak holiday crowds at major attractions"] },
    }),
    signatureExperiences: [
      "Gardens by the Bay and the evening Supertree light show",
      "Sentosa Island day with cable car and beach time",
      "Universal Studios Singapore",
      "Hawker-centre food trail through Chinatown and Little India",
      "Singapore Zoo and River Wonders",
      "Marina Bay skyline walk and Merlion Park",
    ],
    hiddenGems: ["Tiong Bahru heritage neighbourhood cafés", "Southern Ridges canopy walk", "Pulau Ubin island cycling"],
    tradeOffs: ["Compact itinerary options — fewer 'new' sights beyond five nights", "Higher daily costs than most of Southeast Asia"],
    whoShouldAvoid: ["Travellers wanting raw nature or long beach stays as the main event"],
  }),

  dest({
    slug: "dubai",
    name: "Dubai",
    country: "United Arab Emirates",
    region: "Middle East",
    summary:
      "Desert glamour, record-breaking architecture, malls, theme parks and beach resorts — a short flight from India with excellent Indian food availability.",
    positioningLine: "Big-ticket wow factor within a short flight.",
    minimumNights: 4,
    idealNights: 5,
    maximumNights: 8,
    suitablePaces: ["relaxed", "balanced", "active"],
    interests: { city: 92, shopping: 95, themeparks: 88, beach: 70, food: 80, adventure: 78, nightlife: 80, relaxation: 65, culture: 60, romance: 70, history: 50, nature: 45, wildlife: 30, snow: 20 },
    suitability: { family: 90, toddlers: 85, children5To10: 92, teenagers: 90, seniors: 85, honeymoon: 75, solo: 75, firstInternationalTrip: 92 },
    food: { vegetarianFriendly: 85, indianFoodAvailability: 95, halalFriendly: 98, localCuisineScore: 78, streetFoodScore: 70, fineDiningScore: 92 },
    travelPracticality: { averageFlightHoursFromIndia: 3.5, walkingIntensity: "low", publicTransportEase: 85, accessibilityScore: 90, medicalAccessScore: 92, visaComplexity: "low" },
    budgetBands: ["comfort", "premium", "luxury"],
    monthlyIntelligence: buildMonths({
      scores: [88, 88, 82, 72, 55, 40, 35, 35, 50, 70, 85, 90],
      humid: [6, 7, 8, 9], dry: [11, 12, 1, 2, 3],
      crowded: [12, 1], quiet: [6, 7, 8],
      highlights: { 1: ["Dubai Shopping Festival"], 12: ["Pleasant outdoor weather for desert safaris"] },
      warnings: { 6: ["Extreme heat — outdoor plans limited to mornings and evenings"], 7: ["Extreme heat — indoor-focused itinerary recommended"], 8: ["Extreme heat — indoor-focused itinerary recommended"] },
    }),
    signatureExperiences: [
      "Burj Khalifa observation deck at sunset",
      "Desert safari with dune drive and Bedouin-style dinner",
      "Dubai Mall, Dubai Fountain and the aquarium",
      "Abra ride across Dubai Creek and the old souks",
      "Palm Jumeirah beach day",
      "Dubai Frame and old-town Al Fahidi district",
    ],
    hiddenGems: ["Alserkal Avenue arts district", "Hatta mountain reservoir day trip", "Ras Al Khor flamingo sanctuary"],
    tradeOffs: ["Summer months are extremely hot outdoors", "Feels commercial rather than cultural for some travellers"],
    whoShouldAvoid: ["Travellers seeking historic old-world charm or lush landscapes"],
  }),

  dest({
    slug: "bali",
    name: "Bali",
    country: "Indonesia",
    region: "Southeast Asia",
    summary:
      "Temples, rice terraces, surf beaches and wellness retreats. Equally suited to honeymoons, friends' trips and slow family holidays.",
    positioningLine: "Tropical island escape with soul and style.",
    minimumNights: 4,
    idealNights: 6,
    maximumNights: 10,
    suitablePaces: ["relaxed", "balanced"],
    interests: { beach: 92, relaxation: 95, romance: 92, nature: 88, culture: 85, adventure: 78, food: 80, nightlife: 70, city: 40, shopping: 60, history: 65, themeparks: 35, wildlife: 60, snow: 0 },
    suitability: { family: 75, toddlers: 60, children5To10: 72, teenagers: 78, seniors: 65, honeymoon: 95, solo: 85, firstInternationalTrip: 80 },
    food: { vegetarianFriendly: 85, indianFoodAvailability: 60, halalFriendly: 60, localCuisineScore: 85, streetFoodScore: 80, fineDiningScore: 82 },
    travelPracticality: { averageFlightHoursFromIndia: 8, walkingIntensity: "medium", publicTransportEase: 40, accessibilityScore: 55, medicalAccessScore: 65, visaComplexity: "low" },
    budgetBands: ["value", "comfort", "premium", "luxury"],
    monthlyIntelligence: buildMonths({
      scores: [55, 58, 65, 75, 85, 90, 90, 90, 88, 80, 65, 55],
      veryRainy: [1, 2, 12], rainy: [3, 11], humid: [1, 2, 3, 4, 10, 11, 12],
      crowded: [7, 8, 12], quiet: [2, 3],
      highlights: { 6: ["Dry-season perfection for beaches and waterfalls"], 4: ["Green landscapes right after the rains"] },
      warnings: { 1: ["Wet season — expect daily downpours"], 12: ["Wet season and holiday crowds around Christmas"] },
    }),
    signatureExperiences: [
      "Ubud rice terraces and jungle swings",
      "Temple circuit: Tanah Lot, Uluwatu and Tirta Empul",
      "Private-villa stay with pool",
      "Nusa Penida island day trip",
      "Balinese spa and wellness day",
      "Sunset seafood dinner on Jimbaran beach",
    ],
    hiddenGems: ["Sidemen valley rice fields", "Munduk waterfalls in the northern hills", "Amed black-sand snorkelling coast"],
    tradeOffs: ["Traffic between areas can eat into short trips", "Monsoon months (Dec–Feb) bring daily rain"],
    whoShouldAvoid: ["Travellers who want efficient public transport and city polish"],
  }),

  dest({
    slug: "thailand",
    name: "Thailand",
    country: "Thailand",
    region: "Southeast Asia",
    summary:
      "Bangkok's street energy plus island beaches in Phuket or Krabi. Great value, great food and easy visas make it a perennial favourite.",
    positioningLine: "Beaches, street food and city buzz — superb value.",
    minimumNights: 4,
    idealNights: 6,
    maximumNights: 10,
    suitablePaces: ["relaxed", "balanced", "active"],
    interests: { beach: 92, food: 92, nightlife: 88, shopping: 85, culture: 78, relaxation: 85, adventure: 75, city: 80, romance: 78, nature: 70, history: 65, themeparks: 55, wildlife: 65, snow: 0 },
    suitability: { family: 80, toddlers: 70, children5To10: 80, teenagers: 85, seniors: 72, honeymoon: 85, solo: 90, firstInternationalTrip: 90 },
    food: { vegetarianFriendly: 75, indianFoodAvailability: 80, halalFriendly: 70, localCuisineScore: 95, streetFoodScore: 98, fineDiningScore: 85 },
    travelPracticality: { averageFlightHoursFromIndia: 4.5, walkingIntensity: "medium", publicTransportEase: 70, accessibilityScore: 60, medicalAccessScore: 80, visaComplexity: "low" },
    budgetBands: ["value", "comfort", "premium", "luxury"],
    monthlyIntelligence: buildMonths({
      scores: [90, 88, 80, 70, 60, 55, 55, 55, 50, 60, 80, 90],
      veryRainy: [9, 10], rainy: [5, 6, 7, 8], humid: [3, 4, 5, 6, 7, 8, 9, 10],
      crowded: [12, 1, 2], quiet: [9, 10],
      highlights: { 11: ["Loy Krathong lantern season"], 12: ["Cool, dry beach weather"] },
      warnings: { 9: ["Peak monsoon — island boat trips may be cancelled"], 4: ["Hottest month; Songkran water festival crowds"] },
    }),
    signatureExperiences: [
      "Bangkok Grand Palace and river temples",
      "Phi Phi or James Bond Island boat day",
      "Floating market and street-food tour",
      "Phuket or Krabi beach stay",
      "Ethical elephant sanctuary visit",
      "Rooftop dinner over the Bangkok skyline",
    ],
    hiddenGems: ["Koh Lanta's quiet west-coast beaches", "Old-town Chiang Mai temples", "Railay beach rock formations"],
    tradeOffs: ["Popular spots feel crowded in peak season", "Monsoon (Jun–Oct) limits island hopping"],
    whoShouldAvoid: ["Travellers wanting a very quiet, undiscovered feel at headline sights"],
  }),

  dest({
    slug: "vietnam",
    name: "Vietnam",
    country: "Vietnam",
    region: "Southeast Asia",
    summary:
      "Ha Long Bay cruises, lantern-lit Hoi An, buzzing street food and dramatic caves — a rising favourite with excellent value.",
    positioningLine: "Story-rich landscapes at unbeatable value.",
    minimumNights: 5,
    idealNights: 7,
    maximumNights: 12,
    suitablePaces: ["balanced", "active"],
    interests: { culture: 90, food: 92, nature: 88, adventure: 82, history: 85, beach: 70, city: 75, relaxation: 60, romance: 75, shopping: 65, nightlife: 65, themeparks: 40, wildlife: 55, snow: 0 },
    suitability: { family: 70, toddlers: 55, children5To10: 68, teenagers: 80, seniors: 62, honeymoon: 80, solo: 88, firstInternationalTrip: 72 },
    food: { vegetarianFriendly: 70, indianFoodAvailability: 55, halalFriendly: 45, localCuisineScore: 95, streetFoodScore: 95, fineDiningScore: 75 },
    travelPracticality: { averageFlightHoursFromIndia: 5.5, walkingIntensity: "medium", publicTransportEase: 55, accessibilityScore: 50, medicalAccessScore: 65, visaComplexity: "low" },
    budgetBands: ["value", "comfort", "premium"],
    monthlyIntelligence: buildMonths({
      scores: [80, 82, 85, 82, 70, 60, 55, 55, 55, 65, 78, 80],
      veryRainy: [7, 8, 9], rainy: [5, 6, 10], humid: [4, 5, 6, 7, 8, 9],
      crowded: [12, 1], quiet: [9],
      highlights: { 2: ["Cool, clear weather in the north; Tet festival atmosphere"], 3: ["Best all-round month across regions"] },
      warnings: { 9: ["Typhoon season on the central coast"], 7: ["Hot and wet in the north"] },
    }),
    signatureExperiences: [
      "Overnight cruise on Ha Long or Lan Ha Bay",
      "Hoi An old town by lantern light",
      "Hanoi old-quarter street-food walk",
      "Golden Bridge and Ba Na Hills",
      "Mekong Delta boat day",
      "Tailor-made clothing fitting in Hoi An",
    ],
    hiddenGems: ["Ninh Binh's river karsts", "Phong Nha cave region", "Cao Bang's Ban Gioc waterfall"],
    tradeOffs: ["Regions have opposite weather patterns — routing matters", "Long distances between north and south"],
    whoShouldAvoid: ["Travellers wanting a single-base, no-transfers beach holiday"],
  }),

  dest({
    slug: "malaysia",
    name: "Malaysia",
    country: "Malaysia",
    region: "Southeast Asia",
    summary:
      "Kuala Lumpur's skyline, Langkawi's beaches and cool Cameron Highlands tea country — an easy, halal-friendly all-rounder.",
    positioningLine: "Three holidays in one: city, island and highlands.",
    minimumNights: 4,
    idealNights: 6,
    maximumNights: 9,
    suitablePaces: ["relaxed", "balanced"],
    interests: { city: 80, beach: 80, food: 85, nature: 78, shopping: 82, culture: 75, relaxation: 75, themeparks: 70, adventure: 65, nightlife: 65, romance: 70, history: 60, wildlife: 70, snow: 0 },
    suitability: { family: 85, toddlers: 78, children5To10: 85, teenagers: 80, seniors: 80, honeymoon: 75, solo: 80, firstInternationalTrip: 88 },
    food: { vegetarianFriendly: 80, indianFoodAvailability: 92, halalFriendly: 98, localCuisineScore: 90, streetFoodScore: 92, fineDiningScore: 78 },
    travelPracticality: { averageFlightHoursFromIndia: 4.5, walkingIntensity: "low", publicTransportEase: 75, accessibilityScore: 70, medicalAccessScore: 80, visaComplexity: "low" },
    budgetBands: ["value", "comfort", "premium"],
    monthlyIntelligence: buildMonths({
      scores: [78, 80, 78, 72, 70, 72, 74, 72, 65, 60, 55, 65],
      veryRainy: [10, 11], rainy: [4, 5, 9, 12], humid: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      crowded: [12, 6], quiet: [10],
      highlights: { 1: ["Dry west-coast beach weather in Langkawi"], 7: ["Mega Sale shopping season"] },
      warnings: { 11: ["East-coast monsoon; stick to the west coast"] },
    }),
    signatureExperiences: [
      "Petronas Towers and KL skyline evening",
      "Langkawi cable car and island hopping",
      "Batu Caves temple steps",
      "Cameron Highlands tea plantations",
      "George Town street art and food in Penang",
      "Genting Highlands family day",
    ],
    hiddenGems: ["Perhentian Islands' clear water (seasonal)", "Malacca river-front old town", "Taman Negara rainforest canopy walk"],
    tradeOffs: ["Humidity is constant year-round", "East and west coasts have opposite seasons"],
    whoShouldAvoid: ["Travellers chasing a dry, temperate climate"],
  }),

  dest({
    slug: "japan",
    name: "Japan",
    country: "Japan",
    region: "East Asia",
    summary:
      "Tokyo's neon, Kyoto's temples, bullet trains and seasonal spectacle — cherry blossoms in spring, fiery maples in autumn.",
    positioningLine: "A one-of-a-kind blend of tradition and future.",
    minimumNights: 6,
    idealNights: 8,
    maximumNights: 14,
    suitablePaces: ["balanced", "active"],
    interests: { culture: 98, city: 95, food: 95, history: 92, nature: 80, shopping: 88, themeparks: 80, adventure: 60, snow: 70, romance: 80, nightlife: 78, relaxation: 60, beach: 30, wildlife: 45 },
    suitability: { family: 80, toddlers: 65, children5To10: 78, teenagers: 90, seniors: 75, honeymoon: 88, solo: 95, firstInternationalTrip: 65 },
    food: { vegetarianFriendly: 55, indianFoodAvailability: 55, halalFriendly: 45, localCuisineScore: 98, streetFoodScore: 85, fineDiningScore: 98 },
    travelPracticality: { averageFlightHoursFromIndia: 8.5, walkingIntensity: "high", publicTransportEase: 98, accessibilityScore: 85, medicalAccessScore: 92, visaComplexity: "medium" },
    budgetBands: ["premium", "luxury"],
    monthlyIntelligence: buildMonths({
      scores: [60, 62, 85, 92, 80, 60, 55, 55, 65, 85, 90, 70],
      veryRainy: [6], rainy: [7, 9], humid: [6, 7, 8],
      crowded: [3, 4, 10, 11], quiet: [1, 2],
      highlights: { 4: ["Cherry blossom season"], 11: ["Autumn foliage at its peak"] },
      warnings: { 6: ["Rainy season (tsuyu)"], 8: ["Hot, humid and typhoon-prone"] },
    }),
    signatureExperiences: [
      "Shinkansen bullet-train ride between Tokyo and Kyoto",
      "Fushimi Inari's torii gate trail",
      "Tokyo neighbourhoods: Shibuya crossing to Asakusa",
      "Mt Fuji viewpoint day at Hakone or Kawaguchiko",
      "Tea ceremony and kimono stroll in Kyoto",
      "Osaka street-food night in Dotonbori",
    ],
    hiddenGems: ["Nara's temple deer park at opening time", "Kanazawa's samurai and geisha districts", "Koyasan temple stay"],
    tradeOffs: ["Higher budget than Southeast Asia", "Vegetarian dining needs planning outside big cities"],
    whoShouldAvoid: ["Travellers wanting a low-walking, resort-style holiday"],
  }),

  dest({
    slug: "south-korea",
    name: "South Korea",
    country: "South Korea",
    region: "East Asia",
    summary:
      "Seoul's pop culture, palaces and street food, plus Jeju island and autumn hiking — modern Asia with deep tradition.",
    positioningLine: "K-culture energy with palace-town charm.",
    minimumNights: 5,
    idealNights: 7,
    maximumNights: 10,
    suitablePaces: ["balanced", "active"],
    interests: { city: 90, culture: 85, food: 88, shopping: 90, history: 78, nature: 70, nightlife: 82, themeparks: 72, snow: 60, romance: 72, adventure: 60, relaxation: 55, beach: 40, wildlife: 35 },
    suitability: { family: 72, toddlers: 60, children5To10: 70, teenagers: 92, seniors: 68, honeymoon: 75, solo: 90, firstInternationalTrip: 65 },
    food: { vegetarianFriendly: 50, indianFoodAvailability: 50, halalFriendly: 45, localCuisineScore: 92, streetFoodScore: 92, fineDiningScore: 85 },
    travelPracticality: { averageFlightHoursFromIndia: 8, walkingIntensity: "high", publicTransportEase: 95, accessibilityScore: 82, medicalAccessScore: 90, visaComplexity: "medium" },
    budgetBands: ["comfort", "premium"],
    monthlyIntelligence: buildMonths({
      scores: [55, 58, 75, 88, 85, 70, 55, 55, 75, 90, 85, 60],
      veryRainy: [7], rainy: [6, 8], humid: [6, 7, 8], dry: [10, 11, 1],
      crowded: [4, 10], quiet: [1, 2],
      highlights: { 4: ["Spring blossoms across Seoul's palaces"], 10: ["Autumn colours and festival season"] },
      warnings: { 7: ["Monsoon downpours"], 1: ["Sub-zero temperatures — pack for real winter"] },
    }),
    signatureExperiences: [
      "Gyeongbokgung Palace in hanbok dress",
      "Myeongdong street-food and shopping night",
      "N Seoul Tower sunset",
      "Bukchon Hanok village walk",
      "DMZ half-day tour",
      "Jeju island volcanic coast",
    ],
    hiddenGems: ["Jeonju's traditional hanok quarter", "Busan's Gamcheon culture village", "Seoraksan autumn hiking"],
    tradeOffs: ["Language barrier outside tourist cores", "Vegetarian options need planning"],
    whoShouldAvoid: ["Travellers wanting warm beaches year-round"],
  }),

  dest({
    slug: "sri-lanka",
    name: "Sri Lanka",
    country: "Sri Lanka",
    region: "South Asia",
    summary:
      "Tea hills, leopard safaris, ancient citadels and palm-backed beaches packed into one compact island a short hop from India.",
    positioningLine: "Maximum variety, minimum flight time.",
    minimumNights: 4,
    idealNights: 6,
    maximumNights: 10,
    suitablePaces: ["relaxed", "balanced", "active"],
    interests: { nature: 90, wildlife: 90, beach: 85, culture: 82, history: 85, relaxation: 80, adventure: 75, food: 75, romance: 78, city: 45, shopping: 45, nightlife: 40, themeparks: 20, snow: 0 },
    suitability: { family: 80, toddlers: 68, children5To10: 80, teenagers: 78, seniors: 75, honeymoon: 85, solo: 80, firstInternationalTrip: 88 },
    food: { vegetarianFriendly: 88, indianFoodAvailability: 90, halalFriendly: 75, localCuisineScore: 85, streetFoodScore: 75, fineDiningScore: 65 },
    travelPracticality: { averageFlightHoursFromIndia: 2, walkingIntensity: "medium", publicTransportEase: 55, accessibilityScore: 50, medicalAccessScore: 65, visaComplexity: "low" },
    budgetBands: ["value", "comfort", "premium"],
    monthlyIntelligence: buildMonths({
      scores: [90, 90, 85, 75, 60, 60, 65, 70, 65, 55, 60, 80],
      veryRainy: [10, 11], rainy: [5, 9, 12], humid: [4, 5, 6, 9, 10, 11],
      crowded: [12, 1, 2], quiet: [5, 9],
      highlights: { 1: ["Perfect south-west beach season"], 8: ["Kandy Esala Perahera festival; east-coast beaches shine"] },
      warnings: { 10: ["Inter-monsoon rains island-wide"], 5: ["South-west monsoon begins"] },
    }),
    signatureExperiences: [
      "Sigiriya rock fortress climb",
      "Scenic train through tea country to Ella",
      "Yala leopard safari",
      "Galle Fort sunset walls",
      "Kandy Temple of the Tooth",
      "Whale watching in Mirissa (seasonal)",
    ],
    hiddenGems: ["Knuckles range hikes", "Jaffna's distinct northern culture", "Gal Oya boat safari among swimming elephants"],
    tradeOffs: ["Road journeys are slow — distances deceive", "Two monsoons split the island's beach seasons"],
    whoShouldAvoid: ["Travellers wanting nightlife and big-city shopping"],
  }),

  dest({
    slug: "maldives",
    name: "Maldives",
    country: "Maldives",
    region: "Indian Ocean",
    summary:
      "Overwater villas, house reefs and blue lagoons. The definitive fly-and-flop honeymoon, now also open to families and value seekers via guesthouse islands.",
    positioningLine: "The ultimate barefoot-luxury lagoon escape.",
    minimumNights: 3,
    idealNights: 5,
    maximumNights: 7,
    suitablePaces: ["relaxed"],
    interests: { beach: 100, relaxation: 100, romance: 98, adventure: 55, nature: 70, food: 65, wildlife: 70, nightlife: 30, culture: 25, city: 5, shopping: 20, history: 15, themeparks: 0, snow: 0 },
    suitability: { family: 70, toddlers: 60, children5To10: 72, teenagers: 70, seniors: 78, honeymoon: 100, solo: 55, firstInternationalTrip: 85 },
    food: { vegetarianFriendly: 75, indianFoodAvailability: 80, halalFriendly: 95, localCuisineScore: 70, streetFoodScore: 40, fineDiningScore: 90 },
    travelPracticality: { averageFlightHoursFromIndia: 2.5, walkingIntensity: "low", publicTransportEase: 40, accessibilityScore: 60, medicalAccessScore: 55, visaComplexity: "low" },
    budgetBands: ["comfort", "premium", "luxury"],
    monthlyIntelligence: buildMonths({
      scores: [95, 95, 92, 85, 65, 55, 55, 60, 55, 60, 75, 88],
      veryRainy: [6, 9], rainy: [5, 7, 8, 10], humid: [5, 6, 7, 8, 9, 10],
      crowded: [12, 1, 2], quiet: [6, 9],
      highlights: { 2: ["Calm, glassy lagoons and best visibility"], 8: ["Manta and whale-shark season at Hanifaru Bay"] },
      warnings: { 6: ["South-west monsoon — brief squalls likely"], 9: ["Wettest weeks; seaplane delays possible"] },
    }),
    signatureExperiences: [
      "Overwater-villa stay with lagoon steps",
      "Sunset dolphin cruise",
      "House-reef snorkelling with turtles",
      "Sandbank picnic for two",
      "Underwater or over-water fine dining",
      "Sunset fishing the Maldivian way",
    ],
    hiddenGems: ["Local-island guesthouse stays for value", "Bioluminescent plankton on night beaches", "Freediving lessons in ocean pools"],
    tradeOffs: ["One-island stays can feel small after five nights", "Premium resorts price everything à la carte"],
    whoShouldAvoid: ["Travellers who need sightseeing variety and city energy"],
  }),

  dest({
    slug: "mauritius",
    name: "Mauritius",
    country: "Mauritius",
    region: "Indian Ocean",
    summary:
      "Lagoon beaches plus real island life — waterfalls, tea estates, sega music and a big Indian-origin culture. A honeymoon classic that families love too.",
    positioningLine: "Lagoon luxury with an island to explore.",
    minimumNights: 5,
    idealNights: 6,
    maximumNights: 9,
    suitablePaces: ["relaxed", "balanced"],
    interests: { beach: 95, relaxation: 92, romance: 90, nature: 80, adventure: 70, food: 75, culture: 65, wildlife: 60, city: 30, shopping: 50, nightlife: 45, history: 50, themeparks: 25, snow: 0 },
    suitability: { family: 85, toddlers: 78, children5To10: 85, teenagers: 78, seniors: 85, honeymoon: 95, solo: 60, firstInternationalTrip: 85 },
    food: { vegetarianFriendly: 90, indianFoodAvailability: 92, halalFriendly: 85, localCuisineScore: 82, streetFoodScore: 75, fineDiningScore: 80 },
    travelPracticality: { averageFlightHoursFromIndia: 6.5, walkingIntensity: "low", publicTransportEase: 50, accessibilityScore: 65, medicalAccessScore: 70, visaComplexity: "low" },
    budgetBands: ["comfort", "premium", "luxury"],
    monthlyIntelligence: buildMonths({
      scores: [70, 65, 70, 80, 85, 80, 78, 80, 88, 90, 88, 78],
      veryRainy: [1, 2], rainy: [3, 12], humid: [12, 1, 2, 3],
      crowded: [12, 10], quiet: [6],
      highlights: { 10: ["Warm, dry and flamboyant-tree bloom"], 5: ["Calm seas and green interiors"] },
      warnings: { 1: ["Cyclone season possibility"], 2: ["Cyclone season possibility"], 7: ["Windy on the east coast; cooler evenings"] },
    }),
    signatureExperiences: [
      "Catamaran cruise to Île aux Cerfs",
      "Chamarel seven-coloured earth and waterfall",
      "Le Morne beach and mountain backdrop",
      "Port Louis market and street-food morning",
      "Undersea walk or glass-bottom lagoon trip",
      "Tea route tasting at Bois Chéri",
    ],
    hiddenGems: ["Black River Gorges viewpoints", "Rodrigues island side-trip", "Vanilla-farm and rum-distillery south loop"],
    tradeOffs: ["Longer flight than Southeast Asian beach rivals", "Jan–Feb carries cyclone risk"],
    whoShouldAvoid: ["Travellers seeking buzzing nightlife"],
  }),

  dest({
    slug: "seychelles",
    name: "Seychelles",
    country: "Seychelles",
    region: "Indian Ocean",
    summary:
      "Granite boulders, jungle-backed coves and giant tortoises across Mahé, Praslin and La Digue — wilder and quieter than its rivals.",
    positioningLine: "Nature-first island romance, beautifully unpolished.",
    minimumNights: 5,
    idealNights: 7,
    maximumNights: 10,
    suitablePaces: ["relaxed"],
    interests: { beach: 98, nature: 90, romance: 92, relaxation: 95, wildlife: 80, adventure: 60, food: 65, culture: 40, city: 10, shopping: 25, nightlife: 25, history: 30, themeparks: 0, snow: 0 },
    suitability: { family: 68, toddlers: 60, children5To10: 70, teenagers: 65, seniors: 72, honeymoon: 95, solo: 55, firstInternationalTrip: 70 },
    food: { vegetarianFriendly: 65, indianFoodAvailability: 70, halalFriendly: 60, localCuisineScore: 78, streetFoodScore: 50, fineDiningScore: 80 },
    travelPracticality: { averageFlightHoursFromIndia: 5.5, walkingIntensity: "medium", publicTransportEase: 45, accessibilityScore: 50, medicalAccessScore: 60, visaComplexity: "low" },
    budgetBands: ["premium", "luxury"],
    monthlyIntelligence: buildMonths({
      scores: [70, 72, 80, 88, 85, 75, 70, 72, 80, 88, 85, 72],
      veryRainy: [1, 12], rainy: [2, 11], humid: [12, 1, 2, 3],
      crowded: [12, 4, 8], quiet: [6, 9],
      highlights: { 4: ["Glass-calm seas between trade winds"], 10: ["Second calm window — superb snorkelling"] },
      warnings: { 12: ["Wettest weeks of the north-west monsoon"], 7: ["South-east trades bring seaweed to some east-facing beaches"] },
    }),
    signatureExperiences: [
      "Anse Source d'Argent's granite-boulder beach",
      "Cycling around car-free La Digue",
      "Vallée de Mai palm forest (coco de mer)",
      "Island-hopping ferry day: Mahé–Praslin–La Digue",
      "Giant tortoise encounters on Curieuse",
      "Creole dinner with sunset over Beau Vallon",
    ],
    hiddenGems: ["Anse Major coastal hike", "Anse Georgette's quiet perfection", "Cap Lazare nature reserve"],
    tradeOffs: ["Highest price band of the Indian Ocean trio", "Limited nightlife and shopping"],
    whoShouldAvoid: ["Travellers wanting resort mega-facilities and entertainment programmes"],
  }),

  dest({
    slug: "turkey",
    name: "Turkey",
    country: "Turkey",
    region: "Europe & Anatolia",
    summary:
      "Istanbul's minarets and bazaars, Cappadocia's balloon-filled dawns and a turquoise coast — east-meets-west drama at fair prices.",
    positioningLine: "Two continents of drama in one trip.",
    minimumNights: 5,
    idealNights: 7,
    maximumNights: 12,
    suitablePaces: ["balanced", "active"],
    interests: { history: 95, culture: 92, food: 88, city: 82, adventure: 78, romance: 80, beach: 70, shopping: 80, nature: 75, relaxation: 60, nightlife: 65, wildlife: 30, themeparks: 30, snow: 40 },
    suitability: { family: 75, toddlers: 60, children5To10: 72, teenagers: 82, seniors: 70, honeymoon: 88, solo: 80, firstInternationalTrip: 75 },
    food: { vegetarianFriendly: 70, indianFoodAvailability: 55, halalFriendly: 95, localCuisineScore: 92, streetFoodScore: 88, fineDiningScore: 85 },
    travelPracticality: { averageFlightHoursFromIndia: 6.5, walkingIntensity: "high", publicTransportEase: 75, accessibilityScore: 60, medicalAccessScore: 75, visaComplexity: "medium" },
    budgetBands: ["comfort", "premium", "luxury"],
    monthlyIntelligence: buildMonths({
      scores: [55, 58, 70, 85, 90, 85, 75, 75, 90, 88, 72, 58],
      rainy: [1, 2, 12, 11], dry: [7, 8], humid: [7, 8],
      crowded: [7, 8], quiet: [1, 2],
      highlights: { 5: ["Ideal weather everywhere, Cappadocia at its best"], 9: ["Warm seas and thinning crowds"] },
      warnings: { 1: ["Cold and wet in Istanbul; snow inland"], 8: ["Interior heat peaks; book balloons early"] },
    }),
    signatureExperiences: [
      "Sunrise hot-air balloon over Cappadocia",
      "Hagia Sophia and the Blue Mosque",
      "Grand Bazaar and spice-market wander",
      "Bosphorus sunset cruise",
      "Pamukkale's white travertine terraces",
      "Cave-hotel stay in Göreme",
    ],
    hiddenGems: ["Ephesus at opening hour", "Kaş and the quiet Lycian coast", "Balat's colourful old houses in Istanbul"],
    tradeOffs: ["Ambitious multi-stop routings mean internal flights", "Summer interior heat can be intense"],
    whoShouldAvoid: ["Travellers wanting a single-resort, low-movement holiday"],
  }),

  dest({
    slug: "georgia",
    name: "Georgia",
    country: "Georgia",
    region: "Caucasus",
    summary:
      "Tbilisi's balconied old town, Caucasus mountain drives, ancient wine country and monasteries — Europe-adjacent charm at gentle prices.",
    positioningLine: "Mountains, wine and old-world charm, visa-easy.",
    minimumNights: 4,
    idealNights: 6,
    maximumNights: 9,
    suitablePaces: ["balanced", "active"],
    interests: { nature: 90, culture: 82, food: 85, history: 80, adventure: 80, city: 65, romance: 72, relaxation: 60, snow: 65, shopping: 45, nightlife: 60, beach: 35, wildlife: 40, themeparks: 15 },
    suitability: { family: 70, toddlers: 58, children5To10: 68, teenagers: 78, seniors: 65, honeymoon: 78, solo: 85, firstInternationalTrip: 72 },
    food: { vegetarianFriendly: 75, indianFoodAvailability: 50, halalFriendly: 55, localCuisineScore: 90, streetFoodScore: 70, fineDiningScore: 70 },
    travelPracticality: { averageFlightHoursFromIndia: 5, walkingIntensity: "high", publicTransportEase: 55, accessibilityScore: 45, medicalAccessScore: 60, visaComplexity: "low" },
    budgetBands: ["value", "comfort", "premium"],
    monthlyIntelligence: buildMonths({
      scores: [50, 52, 65, 80, 88, 85, 78, 78, 88, 85, 65, 55],
      rainy: [4, 5, 10], dry: [7, 8], humid: [7],
      crowded: [7, 8], quiet: [1, 2, 11],
      highlights: { 5: ["Green valleys and perfect mountain-road conditions"], 9: ["Rtveli grape-harvest season in Kakheti"] },
      warnings: { 1: ["High mountain passes may close (ski areas open)"], 12: ["Short daylight; icy mountain roads"] },
    }),
    signatureExperiences: [
      "Tbilisi old town and sulphur-bath district",
      "Kazbegi day: Gergeti Trinity Church viewpoint",
      "Kakheti wine-country tastings",
      "Mtskheta's UNESCO monasteries",
      "Cable car over Tbilisi at dusk",
      "Traditional supra feast with polyphonic singing",
    ],
    hiddenGems: ["Sighnaghi's walled hilltop lanes", "David Gareja cave monastery", "Martvili canyon boat ride"],
    tradeOffs: ["Mountain excursions involve long, winding drives", "Infrastructure is simpler than Western Europe"],
    whoShouldAvoid: ["Travellers needing step-free access throughout"],
  }),

  dest({
    slug: "azerbaijan",
    name: "Azerbaijan",
    country: "Azerbaijan",
    region: "Caucasus",
    summary:
      "Baku's flame towers beside a medieval walled city, mud volcanoes, burning hillsides and quick mountain escapes — a compact, offbeat city break.",
    positioningLine: "Futuristic Baku with fire-country day trips.",
    minimumNights: 3,
    idealNights: 5,
    maximumNights: 7,
    suitablePaces: ["relaxed", "balanced"],
    interests: { city: 85, culture: 75, history: 72, food: 78, adventure: 60, nature: 60, shopping: 65, nightlife: 70, romance: 65, relaxation: 55, snow: 30, beach: 30, wildlife: 20, themeparks: 20 },
    suitability: { family: 72, toddlers: 62, children5To10: 70, teenagers: 75, seniors: 75, honeymoon: 72, solo: 80, firstInternationalTrip: 80 },
    food: { vegetarianFriendly: 65, indianFoodAvailability: 60, halalFriendly: 90, localCuisineScore: 82, streetFoodScore: 65, fineDiningScore: 75 },
    travelPracticality: { averageFlightHoursFromIndia: 4.5, walkingIntensity: "medium", publicTransportEase: 70, accessibilityScore: 60, medicalAccessScore: 65, visaComplexity: "low" },
    budgetBands: ["value", "comfort", "premium"],
    monthlyIntelligence: buildMonths({
      scores: [55, 58, 68, 82, 88, 82, 70, 70, 85, 88, 70, 58],
      rainy: [3, 4, 11], dry: [7, 8], humid: [7, 8],
      crowded: [6, 7], quiet: [1, 2],
      highlights: { 5: ["Mild Caspian spring — best city-walking weather"], 10: ["Golden autumn in the Caucasus foothills"] },
      warnings: { 7: ["Baku's summer winds and heat"], 1: ["Cold snaps; mountain roads icy"] },
    }),
    signatureExperiences: [
      "Icherisheher old-city walk and Maiden Tower",
      "Flame Towers and Baku boulevard by night",
      "Gobustan rock art and mud volcanoes",
      "Yanar Dag burning mountain",
      "Heydar Aliyev Centre architecture visit",
      "Day trip to Gabala's mountain cable cars",
    ],
    hiddenGems: ["Sheki's Khan's Palace and caravanserai", "Lahij coppersmith village", "Absheron peninsula fire temple"],
    tradeOffs: ["Fewer marquee sights beyond five nights", "Beach scene on the Caspian is limited"],
    whoShouldAvoid: ["Travellers expecting a classic beach holiday"],
  }),

  dest({
    slug: "switzerland",
    name: "Switzerland",
    country: "Switzerland",
    region: "Europe",
    summary:
      "Snow peaks, mirror lakes, scenic trains and storybook villages. The gold standard for honeymoon-grade alpine scenery.",
    positioningLine: "The Alps at their most cinematic.",
    minimumNights: 5,
    idealNights: 7,
    maximumNights: 12,
    suitablePaces: ["relaxed", "balanced", "active"],
    interests: { nature: 98, snow: 95, romance: 92, adventure: 82, relaxation: 78, city: 60, culture: 65, food: 70, history: 60, shopping: 65, wildlife: 40, nightlife: 40, beach: 5, themeparks: 30 },
    suitability: { family: 85, toddlers: 75, children5To10: 85, teenagers: 85, seniors: 82, honeymoon: 98, solo: 75, firstInternationalTrip: 78 },
    food: { vegetarianFriendly: 75, indianFoodAvailability: 70, halalFriendly: 55, localCuisineScore: 80, streetFoodScore: 45, fineDiningScore: 88 },
    travelPracticality: { averageFlightHoursFromIndia: 9, walkingIntensity: "medium", publicTransportEase: 98, accessibilityScore: 88, medicalAccessScore: 95, visaComplexity: "high" },
    budgetBands: ["premium", "luxury"],
    monthlyIntelligence: buildMonths({
      scores: [70, 72, 65, 70, 85, 92, 95, 92, 88, 75, 60, 72],
      rainy: [5, 6, 8], dry: [2],
      crowded: [7, 8, 12], quiet: [11, 3],
      highlights: { 6: ["Green alpine meadows and full waterfalls"], 12: ["Christmas markets and snow-dusted villages"] },
      warnings: { 11: ["Between-season lull — some mountain lifts closed"], 4: ["Snowmelt slush at mid-altitudes"] },
    }),
    signatureExperiences: [
      "Jungfraujoch — Top of Europe rail ascent",
      "Lake Lucerne paddle-steamer cruise",
      "Interlaken and Grindelwald valley day",
      "Glacier Express panoramic train",
      "Zermatt car-free village with Matterhorn views",
      "Swiss chocolate and cheese tastings",
    ],
    hiddenGems: ["Lauterbrunnen's 72-waterfall valley", "Aescher cliff hut hike", "Lavaux vineyard terraces by Lake Geneva"],
    tradeOffs: ["Among the highest daily costs in Europe", "Schengen visa lead time needs planning"],
    whoShouldAvoid: ["Value-focused travellers — costs compound quickly"],
  }),

  dest({
    slug: "france",
    name: "France",
    country: "France",
    region: "Europe",
    summary:
      "Paris icons, Loire châteaux, Riviera glamour and the world's benchmark food culture — a layered classic for romantics and culture lovers.",
    positioningLine: "Romance, art and appetite — the classic done right.",
    minimumNights: 5,
    idealNights: 7,
    maximumNights: 12,
    suitablePaces: ["relaxed", "balanced"],
    interests: { culture: 95, food: 95, romance: 95, history: 92, city: 90, shopping: 92, beach: 55, nature: 60, relaxation: 60, nightlife: 75, adventure: 45, themeparks: 70, wildlife: 20, snow: 45 },
    suitability: { family: 78, toddlers: 68, children5To10: 80, teenagers: 85, seniors: 78, honeymoon: 95, solo: 85, firstInternationalTrip: 70 },
    food: { vegetarianFriendly: 60, indianFoodAvailability: 65, halalFriendly: 60, localCuisineScore: 98, streetFoodScore: 70, fineDiningScore: 99 },
    travelPracticality: { averageFlightHoursFromIndia: 9, walkingIntensity: "high", publicTransportEase: 90, accessibilityScore: 75, medicalAccessScore: 90, visaComplexity: "high" },
    budgetBands: ["premium", "luxury"],
    monthlyIntelligence: buildMonths({
      scores: [55, 58, 68, 80, 88, 90, 85, 80, 90, 82, 62, 60],
      rainy: [1, 2, 11, 12], dry: [7],
      crowded: [7, 8], quiet: [1, 11],
      highlights: { 5: ["Long spring evenings; gardens in bloom"], 9: ["Golden light, grape harvest and fewer queues"] },
      warnings: { 8: ["Parisian August closures; Riviera at peak crowd"], 1: ["Short, grey days in the north"] },
    }),
    signatureExperiences: [
      "Eiffel Tower at sparkling hour",
      "Louvre highlights with a skip-the-line plan",
      "Seine evening cruise",
      "Montmartre and café-terrace mornings",
      "Versailles palace and gardens day",
      "Nice's Promenade and Riviera villages",
    ],
    hiddenGems: ["Annecy's alpine canals", "Colmar's half-timbered lanes", "Luberon hilltop villages in Provence"],
    tradeOffs: ["Peak-season queues at headline sights", "Higher budget; Schengen visa lead time"],
    whoShouldAvoid: ["Travellers who dislike walking-heavy city days"],
  }),

  dest({
    slug: "italy",
    name: "Italy",
    country: "Italy",
    region: "Europe",
    summary:
      "Rome's ruins, Florence's art, Venice's canals and the Amalfi Coast — history, food and romance stacked deeper than anywhere else.",
    positioningLine: "The grand tour: art, coastlines and unforgettable food.",
    minimumNights: 6,
    idealNights: 8,
    maximumNights: 14,
    suitablePaces: ["balanced", "active"],
    interests: { history: 98, culture: 96, food: 96, romance: 92, city: 88, beach: 60, shopping: 85, nature: 60, relaxation: 55, nightlife: 65, adventure: 45, wildlife: 15, themeparks: 30, snow: 40 },
    suitability: { family: 76, toddlers: 62, children5To10: 75, teenagers: 85, seniors: 72, honeymoon: 95, solo: 82, firstInternationalTrip: 68 },
    food: { vegetarianFriendly: 80, indianFoodAvailability: 55, halalFriendly: 55, localCuisineScore: 99, streetFoodScore: 85, fineDiningScore: 95 },
    travelPracticality: { averageFlightHoursFromIndia: 8.5, walkingIntensity: "high", publicTransportEase: 80, accessibilityScore: 60, medicalAccessScore: 88, visaComplexity: "high" },
    budgetBands: ["comfort", "premium", "luxury"],
    monthlyIntelligence: buildMonths({
      scores: [55, 58, 70, 82, 90, 88, 78, 75, 90, 85, 65, 60],
      rainy: [11, 12, 2], dry: [7, 8], humid: [7, 8],
      crowded: [6, 7, 8], quiet: [1, 2, 11],
      highlights: { 5: ["Warm days before the summer surge"], 9: ["Sea still warm; cities exhale after August"] },
      warnings: { 8: ["Ferragosto crowds on every coast"], 7: ["City heat makes midday sightseeing tough"] },
    }),
    signatureExperiences: [
      "Colosseum and Roman Forum walk",
      "Vatican Museums and St Peter's dome",
      "Gondola and back-canal walk in Venice",
      "Florence's Duomo and Uffizi highlights",
      "Amalfi Coast drive: Positano and Ravello",
      "Tuscan long lunch among vineyards",
    ],
    hiddenGems: ["Matera's cave city", "Orvieto and Civita di Bagnoregio", "Procida — the quiet island near Capri"],
    tradeOffs: ["Multi-city routing means packing and moving every few days", "Headline sights need pre-booking"],
    whoShouldAvoid: ["Travellers wanting one base and minimal walking"],
  }),

  dest({
    slug: "greece",
    name: "Greece",
    country: "Greece",
    region: "Europe",
    summary:
      "Athens' Acropolis then whitewashed Cyclades — Santorini sunsets, Mykonos beaches and slow island evenings. A honeymoon staple.",
    positioningLine: "Blue-and-white island romance with ancient roots.",
    minimumNights: 5,
    idealNights: 7,
    maximumNights: 12,
    suitablePaces: ["relaxed", "balanced"],
    interests: { beach: 88, romance: 95, history: 90, relaxation: 85, food: 85, culture: 85, nightlife: 75, city: 60, nature: 60, shopping: 60, adventure: 50, wildlife: 15, themeparks: 10, snow: 15 },
    suitability: { family: 72, toddlers: 60, children5To10: 72, teenagers: 80, seniors: 70, honeymoon: 97, solo: 78, firstInternationalTrip: 72 },
    food: { vegetarianFriendly: 80, indianFoodAvailability: 45, halalFriendly: 50, localCuisineScore: 92, streetFoodScore: 80, fineDiningScore: 85 },
    travelPracticality: { averageFlightHoursFromIndia: 8, walkingIntensity: "high", publicTransportEase: 65, accessibilityScore: 50, medicalAccessScore: 78, visaComplexity: "high" },
    budgetBands: ["comfort", "premium", "luxury"],
    monthlyIntelligence: buildMonths({
      scores: [45, 48, 58, 75, 88, 92, 85, 82, 92, 82, 58, 48],
      rainy: [1, 2, 12, 11], dry: [6, 7, 8],
      crowded: [7, 8], quiet: [1, 2, 3],
      highlights: { 6: ["Warm seas before peak crowds"], 9: ["Best month: warm water, soft light, fewer ferries missed"] },
      warnings: { 8: ["Meltemi winds and peak pricing in the Cyclades"], 12: ["Many island hotels close for winter"] },
    }),
    signatureExperiences: [
      "Acropolis and Plaka old town",
      "Santorini caldera sunset in Oia",
      "Catamaran day around the caldera",
      "Mykonos old-port evenings",
      "Island beach-hopping by local boat",
      "Greek taverna night with live bouzouki",
    ],
    hiddenGems: ["Naxos' mountain villages and long beaches", "Milos' lunar Sarakiniko coast", "Hydra's car-free harbour"],
    tradeOffs: ["Ferry schedules shape the itinerary", "Santorini premiums in July–August are steep"],
    whoShouldAvoid: ["Travellers uncomfortable with steps and cliffside paths"],
  }),

  dest({
    slug: "australia",
    name: "Australia",
    country: "Australia",
    region: "Oceania",
    summary:
      "Sydney's harbour, the Great Barrier Reef and wildlife found nowhere else. A big-trip destination that rewards ten days or more.",
    positioningLine: "Bucket-list nature and easy-going city life.",
    minimumNights: 8,
    idealNights: 10,
    maximumNights: 16,
    suitablePaces: ["balanced", "active"],
    interests: { nature: 95, wildlife: 95, beach: 88, adventure: 88, city: 82, food: 80, relaxation: 60, romance: 75, culture: 65, nightlife: 70, shopping: 70, history: 45, themeparks: 65, snow: 25 },
    suitability: { family: 82, toddlers: 68, children5To10: 82, teenagers: 88, seniors: 72, honeymoon: 85, solo: 85, firstInternationalTrip: 60 },
    food: { vegetarianFriendly: 80, indianFoodAvailability: 78, halalFriendly: 65, localCuisineScore: 85, streetFoodScore: 65, fineDiningScore: 90 },
    travelPracticality: { averageFlightHoursFromIndia: 12, walkingIntensity: "medium", publicTransportEase: 80, accessibilityScore: 85, medicalAccessScore: 95, visaComplexity: "high" },
    budgetBands: ["premium", "luxury"],
    monthlyIntelligence: buildMonths({
      scores: [80, 78, 82, 85, 78, 70, 68, 72, 85, 90, 88, 82],
      veryRainy: [2], rainy: [1, 3, 11], humid: [1, 2, 12],
      crowded: [12, 1], quiet: [5, 6],
      highlights: { 10: ["Spring: whales, wildflowers and mild city days"], 4: ["Autumn calm — reef visibility excellent"] },
      warnings: { 1: ["Tropical north wet season and stingers"], 2: ["Cyclone season in Queensland's north"] },
    }),
    signatureExperiences: [
      "Sydney Opera House and Harbour Bridge climb or cruise",
      "Great Barrier Reef snorkel or dive day",
      "Blue Mountains and wildlife-park day",
      "Great Ocean Road and the Twelve Apostles",
      "Kangaroo and koala encounters",
      "Melbourne laneway coffee-and-art crawl",
    ],
    hiddenGems: ["Lord Howe Island (capped visitors)", "Ningaloo Reef whale sharks", "Tasmania's Cradle Mountain"],
    tradeOffs: ["Long-haul flights and internal distances", "Higher budget; visa lead time required"],
    whoShouldAvoid: ["Travellers with under a week to spare"],
  }),
];

export function getDestinationBySlug(slug: string): DestinationKnowledge | undefined {
  return KTIE_DESTINATIONS.find((d) => d.slug === slug);
}
